import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const categories = [
  { name: 'Linux', slug: 'linux', description: 'Администрирование Linux: ядро, файловые системы, процессы, systemd, пакетный менеджмент', icon: 'Terminal', order: 1 },
  { name: 'Сети', slug: 'networking', description: 'TCP/IP, DNS, маршрутизация, файрволы, VPN, устранение неполадок сети', icon: 'Network', order: 2 },
  { name: 'Bash', slug: 'bash', description: 'Скриптинг, автоматизация, обработка текста, командная строка', icon: 'Code', order: 3 },
  { name: 'Безопасность', slug: 'security', description: 'Харденинг, аутентификация, шифрование, уязвимости, комплаенс', icon: 'Shield', order: 4 },
  { name: 'Docker', slug: 'docker', description: 'Контейнеризация, Dockerfiles, Docker Compose, управление образами', icon: 'Container', order: 5 },
  { name: 'Kubernetes', slug: 'kubernetes', description: 'Архитектура K8s, поды, сервисы, деплойменты, Helm, управление кластером', icon: 'Blocks', order: 6 },
  { name: 'Terraform', slug: 'terraform', description: 'Infrastructure as Code, HCL, управление состоянием, модули, провайдеры', icon: 'Layers', order: 7 },
  { name: 'Ansible', slug: 'ansible', description: 'Управление конфигурацией, плейбуки, роли, инвентарь, автоматизация', icon: 'Play', order: 8 },
  { name: 'AWS', slug: 'aws', description: 'Amazon Web Services: EC2, S3, Lambda, VPC, IAM, облачная архитектура', icon: 'Cloud', order: 9 },
  { name: 'Azure', slug: 'azure', description: 'Microsoft Azure: VMs, Blob Storage, Functions, Active Directory, Bicep', icon: 'CloudRain', order: 10 },
  { name: 'GCP', slug: 'gcp', description: 'Google Cloud: Compute Engine, Cloud Storage, BigQuery, GKE, IAM', icon: 'CloudSun', order: 11 },
  { name: 'DevOps', slug: 'devops', description: 'CI/CD, GitOps, культура DevOps, SRE, управление релизами', icon: 'GitBranch', order: 12 },
  { name: 'Мониторинг', slug: 'monitoring', description: 'Наблюдаемость, Prometheus, Grafana, ELK, алертинг, управление инцидентами', icon: 'Activity', order: 13 },
  { name: 'Базы данных', slug: 'databases', description: 'SQL, PostgreSQL, MySQL, Redis, MongoDB, репликация, бэкап, оптимизация', icon: 'Database', order: 14 },
  { name: 'Веб-серверы', slug: 'web-servers', description: 'Nginx, Apache, обратный прокси, балансировка, SSL/TLS, оптимизация', icon: 'Globe', order: 15 },
]

const questions: { categorySlug: string; title: string; content: string; answer: string; difficulty: string; tags: string[] }[] = [
  // ===== LINUX =====
  { categorySlug: 'linux', title: 'Чем отличается процесс от потока в Linux?', content: 'Объясните фундаментальные различия между процессами и потоками в Linux, включая модель памяти, переключение контекста и механизмы коммуникации.', answer: 'Процесс — независимая единица выполнения с собственным адресным пространством (код, данные, куча, стек). Поток — легковесный подпроцесс, разделяющий адресное пространство процесса, но имеющий собственный стек и регистры.\n\nКлючевые отличия:\n1. **Память**: Процессы имеют отдельные адресные пространства; потоки разделяют одно\n2. **Переключение контекста**: Переключение потоков быстрее (меньше состояния для сохранения)\n3. **Коммуникация**: Потоки общаются через разделяемую память; процессы используют IPC (pipes, sockets, shared memory, signals)\n4. **Создание**: Создание потока дешевле, чем процесса\n5. **Безопасность**: Сбой потока может повредить весь процесс; сбой процесса не затрагивает другие\n6. **Планирование**: В Linux и процессы, и потоки планируются ядром как «задачи» через CFS scheduler\n\nВ ядре Linux 6.x потоки реализованы через clone() с флагами совместного доступа к памяти.', difficulty: 'beginner', tags: ['процессы', 'потоки', 'ядро'] },
  { categorySlug: 'linux', title: 'Как работает процесс загрузки Linux?', content: 'Опишите полную последовательность загрузки Linux от включения до инициализации пользовательского пространства.', answer: 'Процесс загрузки Linux (актуально для ядер 6.x, 2026 год):\n\n1. **BIOS/UEFI POST**: Проверка оборудования при включении\n2. **Загрузчик (GRUB2)**: Находится в EFI-разделе или MBR, загружает ядро и initramfs в память\n3. **Инициализация ядра**: Распаковка, обнаружение оборудования, загрузка драйверов (из initramfs), монтирование корневой ФС\n4. **PID 1 (systemd)**: Первый пользовательский процесс\n5. **Цели systemd**: Последовательно активирует юниты — монтирует ФС, запускает сервисы, достигает default.target\n6. **Getty/Login**: TTY или дисплейный менеджер предлагает вход\n\nКлючевые файлы: /boot/grub2/grub.cfg, /etc/default/grub, /etc/systemd/system/default.target\n\nСовременные дополнения (2026):\n- systemd-boot как альтернатива GRUB для UEFI-систем\n- UKI (Unified Kernel Image) — ядро + initramfs + командная строка в одном EFI-бинарнике\n- systemd-stub для создания UKI\n-Measured Boot через TPM для верификации цепочки загрузки', difficulty: 'intermediate', tags: ['загрузка', 'grub', 'systemd', 'ядро'] },
  { categorySlug: 'linux', title: 'Объясните виртуальную память и OOM Killer в Linux', content: 'Как работает виртуальная память? Что запускает OOM Killer и как он выбирает жертву?', answer: 'Виртуальная память Linux предоставляет каждому процессу изолированное адресное пространство через таблицы страниц, управляемые MMU. Физическая RAM отображается на виртуальные адреса страницами по 4 КБ (или huge pages).\n\n**Ключевые концепции:**\n- **Swap**: Редко используемые страницы выгружаются на диск\n- **Page cache**: Недавно прочитанные данные файлов кэшируются в RAM\n- **Overcommit**: Linux позволяет выделять больше виртуальной памяти, чем физической RAM (vm.overcommit_memory)\n\n**OOM Killer** срабатывает когда:\n- Нет свободной памяти и swap исчерпан\n- Превышен коэффициент overcommit\n- Нет страниц для reclaim\n\n**Выбор жертвы**: OOM Killer оценивает процессы (oom_score) на основе:\n- Потребления памяти (чем больше — тем вероятнее)\n- Приоритета (oom_score_adj от -1000 до +1000)\n- Nice value и процессорного времени\n- Количества дочерних процессов\n\nПрофилактика: Установите oom_score_adj=-1000 для критических процессов, используйте cgroups v2 memory limits, настройте vm.overcommit_ratio.\n\nВ 2026 году рекомендуется использовать cgroups v2 с memory.max и memory.swap.max для жёстких лимитов.', difficulty: 'advanced', tags: ['память', 'oom', 'ядро', 'виртуальная-память'] },
  { categorySlug: 'linux', title: 'Что такое пространства имён и контрольные группы (cgroups) в Linux?', content: 'Объясните Linux namespaces и cgroups, их типы и роль в контейнеризации.', answer: '**Namespaces** изолируют то, что процесс видит:\n1. PID — идентификаторы процессов\n2. NET — сетевой стек\n3. MNT — точки монтирования\n4. UTS — имя хоста\n5. IPC — межпроцессное взаимодействие\n6. USER — идентификаторы пользователей/групп\n7. CGROUP — корневой каталог cgroup\n8. TIME — часы загрузки и монотонные\n\n**Cgroups** ограничивают ресурсы:\n- CPU (cpu, cpuset)\n- Память (memory)\n- Ввод-вывод (io, ранее blkio)\n- Устройства (devices)\n- PID (pids)\n\nВ 2026 году стандарт — **cgroups v2** (единая иерархия, лучше производительность).\n\nВместе они — фундамент Linux-контейнеров (Docker, Podman). Namespaces дают изоляцию; cgroups — ограничение ресурсов.\n\nКоманды: unshare --pid --mount --net, lsns, cat /proc/<pid>/cgroup\nsystemd-run --property=MemoryMax=512M', difficulty: 'intermediate', tags: ['namespaces', 'cgroups', 'контейнеры', 'ядро'] },
  { categorySlug: 'linux', title: 'Как устранить высокую загрузку CPU на сервере Linux?', content: 'Сервер Linux испытывает высокую нагрузку на процессор. Опишите систематический подход к устранению неполадок.', answer: 'Систематический подход:\n\n1. **Определите процесс**: top, htop, ps aux --sort=-%cpu | head -20\n2. **Анализ CPU**: mpstat -P ALL 1 (user vs system vs iowait vs steal)\n3. **Детали процесса**: pidstat -p <pid> 1, strace -c -p <pid>\n4. **Общесистемный анализ**: vmstat 1, sar -u 1 5\n5. **Flame graphs**: perf record -g -p <pid>, perf script | stackcollapse-perf.pl | flamegraph.pl\n6. **Профилирование приложений**: Java: jstack, jmap; Python: py-spy; Node: --prof\n\n**Частые причины:**\n- Бесконечные циклы или CPU-интенсивные алгоритмы\n- Штормы garbage collection (Java, Go)\n- Криптографические операции\n- Компиляция/транспиляция\n- Проблемы ядра (soft lockups, баги драйверов)\n\n**Быстрые меры**: renice, cpulimit, cgroups v2 cpu.max, taskset (привязка к CPU)\n\nВ 2026 году также доступны:\n- eBPF-инструменты (bcc, bpftrace) для низкоуровневого профилирования\n- perf с поддержкой AMD PMU v2 и Intel Intel-Speed-Select\n- Cilium Hubble для наблюдаемости сетевого стека', difficulty: 'intermediate', tags: ['cpu', 'диагностика', 'производительность'] },
  { categorySlug: 'linux', title: 'Объясните файловые разрешения и ACL в Linux', content: 'Опишите модель разрешений Linux, включая традиционные права, специальные биты и ACL.', answer: '**Традиционные разрешения** (rwx для user/group/other):\n- Чтение (r=4), Запись (w=2), Выполнение (x=1)\n- Пример: chmod 755 = rwxr-xr-x\n\n**Специальные биты:**\n- **SUID (4000)**: Выполнение от имени владельца файла (напр., /usr/bin/passwd)\n- **SGID (2000)**: Выполнение от имени группы / новые файлы наследуют группу\n- **Sticky bit (1000)**: Только владелец может удалять (напр., /tmp)\n\n**ACL** (Access Control Lists) — расширение традиционных rwx:\n```bash\n# Просмотр ACL\ngetfacl file.txt\n\n# Права пользователю bob: чтение/запись\nsetfacl -m u:bob:rw file.txt\n\n# ACL по умолчанию для новых файлов в каталоге\nsetfacl -d -m u:bob:rw directory/\n```\n\nACL хранятся как расширенные атрибуты (user.posix_acl_access). При наличии ACL они проверяются перед традиционными разрешениями.\n\nСовременная рекомендация (2026): Используйте ACL для сложных сценариев доступа, а для простых — традиционные разрешения + группы.', difficulty: 'beginner', tags: ['права', 'acl', 'безопасность'] },
  { categorySlug: 'linux', title: 'Что такое systemd и как он управляет сервисами?', content: 'Объясните архитектуру systemd, юнит-файлы, цели и типичные команды управления сервисами.', answer: '**systemd** — система инициализации (PID 1) для современных дистрибутивов Linux.\n\n**Типы юнитов**: service, socket, timer, target, mount, path, slice, scope\n\n**Ключевые каталоги:**\n- /etc/systemd/system/ — локальные переопределения\n- /lib/systemd/system/ — юниты пакетов\n- /run/systemd/system/ — runtime юниты\n\n**Типичные команды:**\n```bash\nsystemctl start/stop/restart/reload <service>\nsystemctl enable/disable <service>   # автозапуск\nsystemctl status <service>\njournalctl -u <service> -f           # логи в реальном времени\nsystemctl list-units --type=service\nsystemctl list-timers --all\n```\n\n**Цели** (замена runlevels):\n- multi-user.target (runlevel 3)\n- graphical.target (runlevel 5)\n- rescue.target, emergency.target\n\n**Кастомные переопределения** (рекомендуемый метод):\n```bash\nsystemctl edit <service>  # создаёт drop-in override\n```\n\nНовое в 2026:\n- systemd-sysupdate для автоматического обновления системы\n- systemd-mount для динамического монтирования\n- Улучшенная поддержка systemd-homed для переносных домашних каталогов', difficulty: 'beginner', tags: ['systemd', 'сервисы', 'init'] },
  { categorySlug: 'linux', title: 'Объясните LVM (Logical Volume Manager)', content: 'Что такое LVM, его компоненты и как управлять логическими томами?', answer: 'LVM обеспечивает гибкое управление дисками путём абстракции физического хранилища.\n\n**Компоненты (снизу вверх):**\n1. **PV (Physical Volume)**: Реальный диск/раздел (pvcreate /dev/sdb1)\n2. **VG (Volume Group)**: Пул PV (vgcreate vg0 /dev/sdb1 /dev/sdc1)\n3. **LV (Logical Volume)**: Логический раздел из VG (lvcreate -L 50G -n data vg0)\n\n**Типичные операции:**\n```bash\n# Расширение LV\nlvextend -L +10G /dev/vg0/data\nresize2fs /dev/vg0/data        # ext4\nxfs_growfs /mnt/data           # XFS\n\n# Снапшот\nlvcreate -L 5G -s -n backup /dev/vg0/data\n\n# Тонкое провижинирование\nlvcreate -T vg0/thinpool -L 100G\nlvcreate -V 50G -T vg0/thinpool -n thinvol\n```\n\n**Преимущества**: Изменение размера на лету, снапшоты, тонкое провижинирование, распределение по нескольким дискам, миграция через pvmove.\n\nВ 2026 году также доступна интеграция LVM с Stratis (менеджер хранения RHEL) для управления через API.', difficulty: 'intermediate', tags: ['lvm', 'хранилище', 'файловые-системы'] },

  // ===== СЕТИ =====
  { categorySlug: 'networking', title: 'Объясните троекратное рукопожатие TCP и закрытие соединения', content: 'Опишите процесс установки и разрыва TCP-соединения с флагами и переходами состояний.', answer: '**Троекратное рукопожатие (установка соединения):**\n1. Клиент → SYN (seq=x) → Сервер (состояние: SYN_SENT)\n2. Сервер → SYN-ACK (seq=y, ack=x+1) → Клиент (состояние: SYN_RCVD)\n3. Клиент → ACK (seq=x+1, ack=y+1) → Сервер (состояние: ESTABLISHED)\n\n**Закрытие соединения (четырёхкратное рукопожатие):**\n1. Активная сторона → FIN → Пассивная сторона (FIN_WAIT_1)\n2. Пассивная сторона → ACK → Активная сторона (FIN_WAIT_2, CLOSE_WAIT)\n3. Пассивная сторона → FIN → Активная сторона (LAST_ACK, TIME_WAIT)\n4. Активная сторона → ACK → Пассивная сторона (CLOSED)\n\n**TIME_WAIT** (2*MSL, обычно 60 сек) обеспечивает:\n- Достижение последнего ACK пассивной стороной\n- Устаревшие/дублированные пакеты от старого соединения отбрасываются\n\nДиагностика: ss -tanp, tcpdump -i eth0, netstat -antp\n\nНовое в 2026: TCP-AO (Authentication Option) заменяет TCP-MD5 для защиты BGP-сессий.', difficulty: 'beginner', tags: ['tcp', 'рукопожатие', 'протоколы'] },
  { categorySlug: 'networking', title: 'Как работает разрешение DNS от начала до конца?', content: 'Опишите полный процесс DNS-разрешения от приложения до авторитетного сервера.', answer: 'Процесс DNS-разрешения:\n\n1. **Приложение** вызывает getaddrinfo() / resolver\n2. **Stub resolver** проверяет /etc/hosts, затем /etc/resolv.conf\n3. **Рекурсивный resolver** (напр., 8.8.8.8) проверяет свой кэш\n4. При промахе кэша → **Корневой сервер** (.) возвращает NS для TLD\n5. **TLD-сервер** (.com) возвращает NS для авторитетного\n6. **Авторитетный сервер** возвращает финальный ответ (A, AAAA, CNAME и т.д.)\n7. Рекурсивный resolver кэширует результат с TTL и возвращает клиенту\n\n**Типы записей:** A/AAAA, CNAME, MX, NS, TXT (SPF, DKIM, DMARC), SRV, SOA\n\n**Диагностика:**\n```bash\ndig example.com A +trace     # полный путь разрешения\nnslookup example.com\nhost -t MX example.com\n```\n\n**Слои кэширования DNS**: Браузер → ОС → Маршрутизатор → Провайдер → Рекурсивный resolver\n\nВ 2026 актуально:\n- DNS-over-HTTPS (DoH) и DNS-over-TLS (DoT) для шифрования запросов\n- DNSSEC для аутентификации ответов\n- Encrypted Client Hello (ECH) — скрывает SNI от наблюдателя', difficulty: 'intermediate', tags: ['dns', 'разрешение', 'протоколы'] },
  { categorySlug: 'networking', title: 'Объясните BGP и его роль в интернет-маршрутизации', content: 'Что такое Border Gateway Protocol, как он работает и почему критически важен для интернета?', answer: '**BGP** — протокол векторного пути, соединяющий автономные системы (AS) в интернете.\n\n**Ключевые концепции:**\n- **AS (Автономная система)**: Сеть под единым административным управлением с уникальным номером AS\n- **eBGP**: Между разными AS (внешний)\n- **iBGP**: Внутри одной AS (внутренний)\n- **Атрибуты пути**: AS-PATH, NEXT-HOP, LOCAL-PREF, MED, COMMUNITY\n\n**Выбор маршрута** (упрощённый приоритет):\n1. Наивысший LOCAL-PREF\n2. Кратчайший AS-PATH\n3. Наименьший MED\n4. eBGP предпочтительнее iBGP\n5. Наименьшая метрика IGP до NEXT-HOP\n6. Старейший маршрут (стабильность)\n\n**Почему BGP важен:**\n- Переносит ~1 млн+ маршрутов в интернете\n- Одна ошибка конфигурации может вызвать утечки маршрутов или чёрные дыры\n- BGP-перехват — реальный вектор атаки\n\n**Безопасность**: RPKI (Resource Public Key Infrastructure) проверяет происхождение маршрутов; BGPsec обеспечивает валидацию пути.\n\nВ 2026: ASPA (AS Provider Authorization) — новый механизм защиты от утечек маршрутов.', difficulty: 'advanced', tags: ['bgp', 'маршрутизация', 'интернет'] },
  { categorySlug: 'networking', title: 'В чём разница между NAT, PAT и DNAT?', content: 'Объясните варианты трансляции сетевых адресов и их сценарии использования.', answer: '**NAT (Network Address Translation)** отображает частные IP в публичные:\n- **SNAT/Source NAT**: Изменяет адрес источника (исходящий трафик)\n- **DNAT/Destination NAT**: Изменяет адрес назначения (проброс портов, балансировка)\n- **PAT/Port Address Translation** (NAT Overload): Множество частных IP используют один публичный через уникальные порты\n\n**Как работает PAT:**\nЧастный: 192.168.1.10:54321 → Публичный: 203.0.113.1:54321 → Интернет\nЧастный: 192.168.1.11:54321 → Публичный: 203.0.113.1:54322 → Интернет (другой порт)\n\n**Примеры nftables (замена iptables в 2026):**\n```bash\n# SNAT\nnft add rule nat postrouting oifname eth0 snat 203.0.113.1\n\n# MASQUERADE (динамический SNAT)\nnft add rule nat postrouting oifname eth0 masquerade\n\n# DNAT (проброс портов)\nnft add rule nat prerouting daddr 203.0.113.1 tcp dport 80 dnat 192.168.1.10:80\n```\n\nВ 2026 nftables полностью заменил iptables во всех основных дистрибутивах.', difficulty: 'intermediate', tags: ['nat', 'файрвол', 'маршрутизация'] },

  // ===== BASH =====
  { categorySlug: 'bash', title: 'Расширение переменных и подстановка параметров в Bash', content: 'Опишите типы расширения параметров в Bash с примерами.', answer: '**Базовое расширение:**\n- $VAR или ${VAR} — значение VAR\n- ${VAR:-default} — значение по умолчанию если не установлено\n- ${VAR:=default} — присвоить значение по умолчанию если не установлено\n- ${VAR:+alternate} — альтернативное значение если VAR установлено\n- ${VAR:?error} — вывести ошибку и выйти если не установлено\n\n**Манипуляция строками:**\n- ${#VAR} — длина строки\n- ${VAR%pattern} — удалить кратчайшее совпадение суффикса\n- ${VAR%%pattern} — удалить длиннейшее совпадение суффикса\n- ${VAR#pattern} — удалить кратчайшее совпадение префикса\n- ${VAR##pattern} — удалить длиннейшее совпадение префикса\n- ${VAR/old/new} — заменить первое совпадение\n- ${VAR//old/new} — заменить все совпадения\n\n**Примеры:**\n```bash\nFILE="archive.tar.gz"\necho ${FILE##*.}     # gz (удаление длиннейшего префикса)\necho ${FILE%.*}      # archive.tar (удаление кратчайшего суффикса)\n```\n\nВ Bash 5.2+ (2026) доступны: ${var@U} (верхний регистр), ${var@L} (нижний регистр), ${var@Q} (экранирование).', difficulty: 'intermediate', tags: ['bash', 'переменные', 'расширение'] },
  { categorySlug: 'bash', title: 'Как эффективно обрабатывать текстовые файлы в Bash?', content: 'Опишите ключевые инструменты обработки текста (grep, sed, awk, sort, uniq) с практическими примерами.', answer: '**grep** — поиск по шаблону:\n```bash\ngrep -r "ошибка" /var/log/          # рекурсивно\ngrep -i "предупреждение" file.log   # без учёта регистра\ngrep -E "ошиб|пред|крит" file.log  # расширенное регулярное выражение\ngrep -v "отладка" file              # инвертированный поиск\n```\n\n**sed** — потоковый редактор:\n```bash\nsed -n "10,20p" file               # печать строк 10-20\nsed "s/старое/новое/g" file         # глобальная замена\nsed -i.bak "s/старое/новое/g" file  # на месте с бэкапом\n```\n\n**awk** — обработка полей:\n```bash\nawk "{print $1, $3}" file          # печать столбцов\nawk -F: "{print $1}" /etc/passwd   # свой разделитель\nawk "$3 > 100 {print $0}" file     # условие\n```\n\n**sort/uniq** — сортировка и дедупликация:\n```bash\nsort file | uniq -c | sort -rn     # подсчёт частоты\n```\n\n**Современные альтернативы (2026):**\n- ripgrep (rg) — быстрее grep для кодовых баз\n- fd — замена find\n- jq/yq — обработка JSON/YAML\n- mlr (Miller) — обработка CSV/TSV как awk для структурированных данных', difficulty: 'beginner', tags: ['bash', 'обработка-текста', 'grep', 'awk', 'sed'] },
  { categorySlug: 'bash', title: 'Напишите надёжный шаблон Bash-скрипта', content: 'Создайте шаблон Bash-скрипта продакшн-качества с обработкой ошибок, логированием и парсингом аргументов.', answer: '```bash\n#!/usr/bin/env bash\nset -euo pipefail\nIFS=$\'\\n\\t\'\n\n# Метаданные скрипта\nreadonly SCRIPT_NAME="$(basename "$0")"\nreadonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\nreadonly LOG_FILE="/var/log/${SCRIPT_NAME}.log"\n\n# Логирование\nlog() { echo "[$(date +\'%Y-%m-%d %H:%M:%S\')] [$1] $2" | tee -a "$LOG_FILE"; }\ninfo()  { log "INFO"  "$1"; }\nwarn()  { log "WARN"  "$1"; }\nerror() { log "ERROR" "$1"; }\n\n# Очистка при выходе\ncleanup() {\n  local exit_code=$?\n  if [[ $exit_code -ne 0 ]]; then\n    error "Скрипт завершился с кодом $exit_code"\n  fi\n  rm -f "$TEMP_FILE" 2>/dev/null || true\n  exit $exit_code\n}\ntrap cleanup EXIT\n\n# Парсинг аргументов\nusage() {\n  cat <<EOF\nИспользование: $SCRIPT_NAME [ОПЦИИ] <вход>\nОпции:\n  -v, --verbose    Подробный вывод\n  -n, --dry-run    Показать что будет сделано\n  -h, --help       Показать справку\nEOF\n  exit 1\n}\n\nVERBOSE=false\nDRY_RUN=false\n\nwhile [[ $# -gt 0 ]]; do\n  case $1 in\n    -v|--verbose) VERBOSE=true; shift ;;\n    -n|--dry-run) DRY_RUN=true; shift ;;\n    -h|--help)    usage ;;\n    -*)           error "Неизвестная опция: $1"; usage ;;\n    *)            INPUT="$1"; shift ;;\n  esac\ndone\n\n[[ -z "${INPUT:-}" ]] && { error "Требуется входной параметр"; usage; }\n\ninfo "Запуск $SCRIPT_NAME"\n# ... основная логика ...\ninfo "Успешно завершено"\n```\n\nКлючевые практики: set -euo pipefail, trap для очистки, логирование с метками времени, парсинг аргументов, readonly для констант.', difficulty: 'intermediate', tags: ['bash', 'скриптинг', 'лучшие-практики'] },

  // ===== БЕЗОПАСНОСТЬ =====
  { categorySlug: 'security', title: 'Как харденинговать сервер Linux?', content: 'Предоставьте полный чеклист для харденинга продакшн-сервера Linux.', answer: '**Уровень ОС:**\n- Обновления: unattended-upgrades или dnf-automatic\n- Удалите ненужные пакеты и сервисы\n- Запретите root-вход по SSH, используйте только ключи\n- PermitRootLogin no, PasswordAuthentication no в sshd_config\n- Файрвол: nftables (замена iptables в 2026)\n- Автоматические обновления безопасности\n\n**Аутентификация:**\n- SSH-ключи ed25519 (рекомендуется)\n- 2FA: google-authenticator-libpam или Duo\n- Fail2ban или CrowdSec\n- umask 027\n- PAM-модули для политик паролей\n\n**Ядро:**\n- kernel.randomize_va_space = 2 (ASLR)\n- Включите SELinux или AppArmor в enforcing-режиме\n- kernel.kptr_restrict = 1\n\n**Сеть:**\n- Закройте все входящие порты кроме необходимых\n- VPN для административного доступа\n- tcp_syncookies = 1\n\n**Аудит и мониторинг:**\n- auditd для логирования системных вызовов\n- Централизованное логирование (rsyslog/journald + удалённый сервер)\n- AIDE или Tripwire для проверки целостности\n- Lynis для автоматического аудита безопасности\n\nВ 2026 также актуально:\n- systemd-sysupdate для автоматического обновления\n- Подпись загрузки через Secure Boot + TPM\n- Статический анализ образов контейнеров (Trivy, Grype)', difficulty: 'intermediate', tags: ['харденинг', 'безопасность', 'linux'] },
  { categorySlug: 'security', title: 'Объясните рукопожатие SSL/TLS и валидацию цепочки сертификатов', content: 'Опишите процесс рукопожатия TLS 1.3 и проверку цепочки сертификатов.', answer: '**Рукопожатие TLS 1.3** (1-RTT, улучшено с 2-RTT в TLS 1.2):\n1. **ClientHello**: Поддерживаемые версии, шифронаборы, key share (DH публичный ключ)\n2. **ServerHello**: Выбранная версия/шифр, сертификат, CertificateVerify, Finished\n3. **Клиент**: Проверяет цепочку сертификатов, отправляет Finished\n4. **Данные приложения** идут немедленно\n\n**Валидация цепочки сертификатов:**\n1. Разобрать сертификат, извлечь издателя\n2. Найти сертификат издателя в цепочке или хранилище доверия\n3. Проверить подпись листового сертификата публичным ключом издателя\n4. Повторить вверх по цепочке: leaf → intermediate → root\n5. Root должен быть в системном хранилище доверия (/etc/ssl/certs/)\n6. Проверки: не истёк, не отозван (CRL/OCSP), имя хоста совпадает с SAN/CN\n\n**Ключевые улучшения TLS 1.3 (2026 стандарт):**\n- Удалены небезопасные алгоритмы (RSA key exchange, CBC, MD5)\n- 0-RTT для возобновлённых сессий (с риском повторного воспроизведения)\n- Forward secrecy обязателен (ephemeral DH)\n- Зашифрованы ServerHello и сертификат\n\nДиагностика: openssl s_client -connect example.com:443 -servername example.com', difficulty: 'advanced', tags: ['tls', 'ssl', 'сертификаты', 'шифрование'] },
  { categorySlug: 'security', title: 'Принцип наименьших привилегий и его реализация', content: 'Объясните принцип наименьших привилегий и практические стратегии реализации в Linux/Cloud.', answer: '**Принцип наименьших привилегий (PoLP)**: Каждый пользователь, процесс и система должны иметь только минимально необходимые привилегии.\n\n**Реализация в Linux:**\n- sudo с конкретными командами: user ALL=(ALL) /usr/bin/systemctl restart nginx\n- polkit для точного управления доступом\n- SELinux/AppArmor для обязательного контроля доступа\n- Запуск сервисов от непривилегированных пользователей\n- Capabilities вместо полного root: setcap cap_net_bind_service=+ep /usr/bin/node\n- Права файлов: 600 для секретов, 750 для каталогов\n\n**Реализация в облаке:**\n- IAM-политики: конкретные ресурсы и действия, никогда *:*\n- Service accounts для приложений с ограниченными ролями\n- Временные учётные данные (STS AssumeRole) вместо долгоживущих ключей\n- Теги ресурсов для условного доступа\n- SCP (Service Control Policies) в AWS Organizations\n\n**Контейнеры:**\n- Запуск от непривилегированного пользователя: USER 1000 в Dockerfile\n- Файловая система только для чтения: securityContext.readOnlyRootFilesystem: true\n- Удалить все capabilities, добавить только нужные\n\n**Kubernetes (2026):**\n- RBAC с конкретными глаголами и ресурсами\n- NetworkPolicies для ограничения коммуникации подов\n- Pod Security Standards (restricted profile)\n- Kyverno/OPA Gatekeeper для принудительного применения политик', difficulty: 'intermediate', tags: ['наименьшие-привилегии', 'iam', 'безопасность', 'rbac'] },

  // ===== DOCKER =====
  { categorySlug: 'docker', title: 'Объясните архитектуру Docker и многослойную файловую систему', content: 'Опишите клиент-серверную архитектуру Docker, слои образов и работу union filesystem.', answer: '**Архитектура Docker:**\n- **Docker Client**: CLI (docker) общается с демоном через REST API\n- **Docker Daemon (dockerd)**: Управляет образами, контейнерами, сетями, томами\n- **containerd**: Супервизор среды выполнения (shim, runc)\n- **runc**: OCI-совместимая среда выполнения, создающая контейнеры\n\n**Многослойная файловая система:**\n- Каждая инструкция Dockerfile создаёт слой только для чтения\n- Слои разделяются между образами (экономия места)\n- Слой контейнера: доступный для записи overlay поверх слей только для чтения\n- **OverlayFS** (overlay2) — драйвер хранения по умолчанию\n- docker history <image> показывает все слои\n\n**Copy-on-Write (CoW):**\n- При изменении файла из нижнего слоя он копируется в доступный для записи слой\n\n**Многоэтапные сборки** уменьшают размер финального образа:\n```dockerfile\nFROM node:22 AS builder\nWORKDIR /app\nCOPY . .\nRUN npm ci && npm run build\n\nFROM node:22-slim\nCOPY --from=builder /app/dist ./dist\nCMD ["node", "dist/server.js"]\n```\n\nВ 2026: Docker BuildKit по умолчанию, поддержка attestations (SBOM, provenance), docker scout для анализа уязвимостей.', difficulty: 'intermediate', tags: ['docker', 'архитектура', 'слои', 'overlayfs'] },
  { categorySlug: 'docker', title: 'Сетевые режимы Docker и когда использовать каждый', content: 'Объясните сетевые драйверы Docker (bridge, host, overlay, macvlan) и их сценарии.', answer: '**Сетевые драйверы:**\n\n1. **bridge** (по умолчанию): Контейнер получает частный IP на docker0 bridge\n   - Проброс портов: -p 8080:80\n   - Между контейнерами: --network mynet для DNS-обнаружения\n   - Сценарий: Однохостовые приложения\n\n2. **host**: Контейнер разделяет сетевой стек хоста\n   - Лучше производительность, нет изоляции сети\n   - Сценарий: Высокопроизводительные сети, агенты мониторинга\n\n3. **overlay**: Мультихостовая сеть (Swarm/K8s)\n   - Зашифрованные VXLAN-туннели между хостами\n   - Встроенное обнаружение сервисов\n   - Сценарий: Docker Swarm, межхостовая коммуникация\n\n4. **macvlan**: Контейнер получает реальный MAC в физической сети\n   - Виден как физическое устройство в LAN\n   - Сценарий: Унаследованные приложения\n\n5. **none**: Без сети\n\n**Пользовательская bridge-сеть (рекомендуется):**\n```bash\ndocker network create myapp-net\ndocker run --network myapp-net --name api myimage\ndocker run --network myapp-net --name db myimage\n# api обращается к db по имени хоста "db"\n```\n\nВ 2026 актуально: Docker Compose v2+ с поддержкой profiles и watch для автоперезагрузки при разработке.', difficulty: 'intermediate', tags: ['docker', 'сети', 'bridge', 'overlay'] },
  { categorySlug: 'docker', title: 'Оптимизация размера Docker-образа и скорости сборки', content: 'Предоставьте стратегии уменьшения размера Docker-образа и ускорения сборки.', answer: '**Оптимизация размера:**\n\n1. **Минимальные базовые образы**: alpine (~5МБ), distroless (без shell), scratch (для статических бинарников Go)\n\n2. **Многоэтапные сборки** (главный выигрыш)\n\n3. **Кэширование слоёв**: Порядок инструкций от менее к более изменяемым\n```dockerfile\nCOPY package.json package-lock.json ./\nRUN npm ci\nCOPY . .\n```\n\n4. **Объединение RUN-команд** для уменьшения слоёв:\n```dockerfile\nRUN apt-get update && \\\n    apt-get install -y --no-install-recommends curl && \\\n    rm -rf /var/lib/apt/lists/*\n```\n\n5. **.dockerignore**\n\n6. **BuildKit** (по умолчанию в 2026):\n```dockerfile\n# syntax=docker/dockerfile:1\nRUN --mount=type=cache,target=/root/.npm npm ci\nRUN --mount=type=secret,id=npmrc npm ci\n```\n\n**Производительность сборки:**\n- BuildKit: DOCKER_BUILDKIT=1 docker build .\n- Кэш-монтирования для пакетных менеджеров\n- Удалённый кэш: --cache-from registry/image:cache\n\nВ 2026 также:\n- Docker Build Cloud для распределённой сборки\n- Attestations: --provenance=true --sbom=true для SBOM и provenance\n- docker scout для анализа уязвимостей в образах', difficulty: 'advanced', tags: ['docker', 'оптимизация', 'buildkit', 'многоэтапная-сборка'] },

  // ===== KUBERNETES =====
  { categorySlug: 'kubernetes', title: 'Объясните архитектуру Kubernetes и роли компонентов', content: 'Опишите компоненты control plane и worker-узлов и их взаимодействие.', answer: '**Control Plane (Master):**\n\n1. **kube-apiserver**: REST API входная точка, валидирует и хранит состояние в etcd\n2. **etcd**: Распределённое хранилище KV, единственный источник истины\n3. **kube-scheduler**: Назначает поды узлам на основе ресурсов, taints, affinity\n4. **kube-controller-manager**: Контроллеры (Deployment, ReplicaSet, Node, Job)\n5. **cloud-controller-manager**: Облачные контроллеры (LB, routes, volumes)\n\n**Worker Node:**\n\n1. **kubelet**: Агент, обеспечивает выполнение контейнеров по PodSpec\n2. **kube-proxy**: Поддерживает сетевые правила (iptables/IPVS)\n3. **Container Runtime**: containerd или CRI-O\n\n**Поток запроса:**\nkubectl → apiserver → etcd → scheduler → kubelet → kube-proxy\n\n**Высокая доступность:**\n- Кластер etcd: 3 или 5 узлов (кворум)\n- Несколько API-серверов за балансировщиком\n- Выборы лидера для scheduler и controllers\n\n**Ключевые аддоны:** CNI (Cilium — стандарт в 2026, Calico), CoreDNS, Ingress Controller (nginx, traefik), Metrics Server, cert-manager\n\nВ 2026: Kubernetes 1.31+ с Gateway API (замена Ingress),.sidecar containers, валидация AdmissionPolicy.', difficulty: 'intermediate', tags: ['kubernetes', 'архитектура', 'control-plane'] },
  { categorySlug: 'kubernetes', title: 'Что такое сервисы Kubernetes и как они работают?', content: 'Объясните типы Service, селекторы и механизмы маршрутизации трафика.', answer: '**Типы сервисов:**\n\n1. **ClusterIP** (по умолчанию): Внутренний IP\n   - Доступен внутри кластера: my-svc.my-ns.svc.cluster.local\n\n2. **NodePort**: Открывает порт на каждом узле (30000-32767)\n\n3. **LoadBalancer**: Создаёт облачный балансировщик\n\n4. **ExternalName**: CNAME на внешний DNS\n\n5. **Headless** (ClusterIP: None): Возвращает IP подов напрямую\n   - StatefulSets (базы данных), обнаружение сервисов\n\n**Маршрутизация трафика:**\n- kube-proxy: iptables/IPVS режим\n- iptables: случайный выбор пода\n- IPVS: алгоритмы rr, lc, wrr, sh\n\n**Gateway API (2026, замена Ingress):**\n```yaml\napiVersion: gateway.networking.k8s.io/v1\nkind: HTTPRoute\nmetadata:\n  name: my-app\nspec:\n  parentRefs:\n  - name: my-gateway\n  rules:\n  - backendRefs:\n    - name: my-service\n      port: 8080\n```\n\nGateway API обеспечивает: HTTPRoute, GRPCRoute, TCPRoute, TLSRoute — более гранулярное управление трафиком чем Ingress.', difficulty: 'intermediate', tags: ['kubernetes', 'сервисы', 'сети'] },
  { categorySlug: 'kubernetes', title: 'Как устранить CrashLoopBackOff пода?', content: 'Опишите систематический подход к диагностике пода в состоянии CrashLoopBackOff.', answer: '**CrashLoopBackOff** означает: контейнер запускается, падает, Kubernetes перезапускает его повторно.\n\n**Пошаговая диагностика:**\n\n1. **Статус пода:**\n```bash\nkubectl get pods\nkubectl describe pod <pod-name>  # Смотрите Events и Last State\n```\n\n2. **Логи:**\n```bash\nkubectl logs <pod-name>              # текущий контейнер\nkubectl logs <pod-name> --previous    # предыдущий упавший\n```\n\n3. **Частые причины и решения:**\n\n| Причина | Симптом | Решение |\n|---------|---------|--------|\n| Нет ConfigMap/Secret | Exit 1, «файл не найден» | Проверить монтирование |\n| OOMKilled | Last State: OOMKilled | Увеличить resources.limits.memory |\n| Не прошла health check | «unhealthy» | Исправить probe |\n| Ошибка запуска приложения | Стек-трейс в логах | Исправить код |\n| Нет прав доступа | «permission denied» | Исправить SecurityContext |\n\n4. **Интерактивная отладка:**\n```bash\nkubectl debug <pod-name> -it --image=busybox  # K8s 1.25+\n```\n\n5. **Проверка лимитов ресурсов:**\n```bash\nkubectl describe pod <pod-name> | grep -A5 Limits\n```\n\nВ 2026: kubectl debug поддерживает ephemeral containers, node debugging и профиль отладки.', difficulty: 'beginner', tags: ['kubernetes', 'диагностика', 'поды'] },

  // ===== TERRAFORM =====
  { categorySlug: 'terraform', title: 'Объясните состояние Terraform и его управление', content: 'Что такое состояние Terraform, почему оно важно и как управлять им в команде?', answer: '**Состояние Terraform** отображает реальные ресурсы на вашу конфигурацию. Это источник истины о том, что Terraform создал.\n\n**Почему состояние важно:**\n- Отслеживает ID ресурсов и метаданные\n- Хранит вычисляемые атрибуты (IP, ARN)\n- Позволяет terraform plan показать различия\n- Связывает ресурсы конфигурации с реальными\n\n**Удалённое состояние** (обязательно для команд):\n```hcl\nterraform {\n  backend "s3" {\n    bucket = "tf-state-prod"\n    key    = "infra/terraform.tfstate"\n    region = "us-east-1"\n    dynamodb_table = "tf-lock"\n    encrypt = true\n  }\n}\n```\n\n**Блокировка состояния**: Предотвращает параллельные операции (DynamoDB для S3, нативно для GCS)\n\n**Команды управления состоянием:**\n```bash\nterraform state list\nterraform state show aws_instance.web\nterraform state mv aws_instance.a aws_instance.b\nterraform state rm aws_instance.old\nterraform import aws_instance.web i-12345\n```\n\nВ 2026: OpenTofu (форк Terraform с открытой лицензией) набирает популярность. Terraform 1.9+ поддерживает циклы for_each в module blocks и функции-предикаты.\n\nРекомендация: Используйте S3+DynamoDB, GCS или Terraform Cloud для удалённого состояния с блокировками.', difficulty: 'intermediate', tags: ['terraform', 'состояние', 'iac'] },

  // ===== ANSIBLE =====
  { categorySlug: 'ansible', title: 'Объясните архитектуру и поток выполнения Ansible', content: 'Опишите как Ansible работает без агентов, систему инвентаря и выполнение плейбуков.', answer: '**Архитектура Ansible:**\n- **Управляющий узел**: Где запускается Ansible (не требует демона)\n- **Управляемые узлы**: Целевые хосты (нужен только Python + SSH)\n- **Инвентарь**: Список хостов (INI/YAML/динамический)\n- **Модули**: Единицы работы (copy, yum, systemd и др.)\n- **Плейбуки**: YAML-оркестрация задач\n\n**Поток выполнения:**\n1. Чтение инвентаря и плейбука\n2. Генерация Python-скрипта из модуля\n3. SCP скрипта на целевой хост (~/.ansible/tmp/)\n4. Выполнение скрипта через SSH\n5. Возврат JSON-результата\n6. Удаление скрипта с целевого хоста\n\n**Инвентарь:**\n```ini\n[webservers]\nweb[01:03].example.com\n\n[dbservers]\ndb01.example.com ansible_host=10.0.1.50\n\n[production:children]\nwebservers\ndbservers\n```\n\n**Команды ad-hoc:**\n```bash\nansible all -m ping\nansible webservers -m shell -a "uptime"\n```\n\nВ 2026: Ansible Automation Platform (AAP) 2.5+, ansible-navigator как основной CLI, переход на ansible-core + коллекции.\n\nКлючевой конфиг: ansible.cfg (текущий каталог > ~/.ansible.cfg > /etc/ansible/ansible.cfg)', difficulty: 'beginner', tags: ['ansible', 'архитектура', 'инвентарь'] },

  // ===== AWS =====
  { categorySlug: 'aws', title: 'Объясните архитектуру AWS VPC и проектирование подсетей', content: 'Опишите компоненты VPC, типы подсетей, маршрутизацию и лучшие практики сетевого дизайна.', answer: '**Компоненты VPC:**\n- **VPC**: Изолированная виртуальная сеть (CIDR, напр., 10.0.0.0/16)\n- **Подсети**: Сегменты VPC CIDR\n  - Публичные: Маршрут к Internet Gateway\n  - Частные: Без прямого интернет-доступа\n  - Изолированные: Без интернета и NAT\n- **Route Tables**: Направляют трафик\n- **Internet Gateway (IGW)**: Подключение VPC к интернету\n- **NAT Gateway**: Исходящий интернет для частных подсетей\n- **Security Groups**: Stateful файрвол уровня инстанса\n- **NACLs**: Stateless файрвол уровня подсети\n\n**Лучшие практики архитектуры:**\n```\nVPC 10.0.0.0/16\n├── AZ-a\n│   ├── Публичная  10.0.1.0/24  (ALB, Bastion)\n│   ├── Частная    10.0.2.0/24  (Серверы приложений)\n│   └── Данные     10.0.3.0/24  (RDS, ElastiCache)\n├── AZ-b\n│   ├── Публичная  10.0.11.0/24\n│   ├── Частная    10.0.12.0/24\n│   └── Данные     10.0.13.0/24\n```\n\nВ 2026: VPC Lattice для сервис-меш между сервисами, IPv6 по умолчанию для новых VPC, VPC Block Public Access для запрета публичного доступа.', difficulty: 'intermediate', tags: ['aws', 'vpc', 'сети'] },
  { categorySlug: 'aws', title: 'Лучшие практики AWS IAM', content: 'Опишите лучшие практики безопасности AWS IAM, включая политики, роли и управление доступом.', answer: '**Лучшие практики IAM:**\n\n1. **Root-аккаунт**: Никогда не используйте ключи доступа, включите MFA, создайте IAM-пользователя для повседневной работы\n\n2. **Принцип наименьших привилегий:**\n```json\n{\n  "Version": "2012-10-17",\n  "Statement": [{\n    "Effect": "Allow",\n    "Action": ["s3:GetObject", "s3:PutObject"],\n    "Resource": "arn:aws:s3:::my-bucket/data/*"\n  }]\n}\n```\n\n3. **Роли, а не пользователи** для сервисов (EC2, Lambda, ECS)\n4. **Временные учётные данные** через STS AssumeRole\n5. **IAM Access Analyzer** для выявления неиспользуемых/чрезмерных политик\n6. **Permission boundaries** для ограничения максимальных прав роли\n7. **SCPs (Service Control Policies)** на уровне организации\n8. **Ротация ключей доступа** каждые 90 дней\n9. **CloudTrail** для аудита API-вызовов\n\nВ 2026: IAM Identity Center (замена SSO) — централизованное управление доступом. Поддержка централизованных политик через Terraform/CDK.\n\nИнструменты: aws iam simulate-principal-policy, IAM Access Analyzer, cloudsplaining', difficulty: 'intermediate', tags: ['aws', 'iam', 'безопасность'] },

  // ===== AZURE =====
  { categorySlug: 'azure', title: 'Сравните Azure Resource Manager и классическое развёртывание', content: 'Объясните модель ARM и чем она отличается от классической модели развёртывания.', answer: '**ARM (Azure Resource Manager):**\n- Resource Groups для логической группировки\n- Декларативные шаблоны (ARM JSON, Bicep)\n- RBAC на уровне групп ресурсов\n- Теги для организации и биллинга\n- Параллельное развёртывание ресурсов\n\n**Bicep** (предпочтительнее ARM JSON в 2026):\n```bicep\nresource storageAccount \'Microsoft.Storage/storageAccounts@2023-05-01\' = {\n  name: \'st${uniqueString(resourceGroup().id)}\'\n  location: resourceGroup().location\n  sku: { name: \'Standard_LRS\' }\n  kind: \'StorageV2\'\n}\n```\n\n**Почему ARM лучше:**\n1. Infrastructure as Code: повторяемые развёртывания\n2. Тонкий RBAC на уровне ресурса\n3. Управление затратами: теги + группы ресурсов\n4. Согласованность: один API для всех сервисов Azure\n5. Автоматизация: CI/CD интеграция\n\nКлассическая модель полностью устарела — все новые ресурсы используют ARM.\n\nВ 2026: Azure Deployment Stacks для управления жизненным циклом развёртываний, Azure Verified Modules для проверенных Bicep-модулей.', difficulty: 'beginner', tags: ['azure', 'arm', 'развёртывание'] },

  // ===== GCP =====
  { categorySlug: 'gcp', title: 'Объясните IAM GCP и иерархию организации', content: 'Опишите модель IAM Google Cloud, иерархию организация/папка/проект и паттерны управления доступом.', answer: '**Иерархия организации GCP:**\n```\nОрганизация (домен)\n  └── Папки (опционально, группировка)\n       └── Проекты\n            └── Ресурсы (VMs, buckets и т.д.)\n```\n\n**Модель IAM:**\n- **Кто**: Участник (пользователь, service account, группа, домен)\n- **Что может делать**: Роль (примитивная, предопределённая, кастомная)\n- **С каким ресурсом**: Ресурс (org, папка, проект, ресурс)\n\n**Типы ролей:**\n1. **Примитивные**: Owner, Editor, Viewer (избегать в продакшене)\n2. **Предопределённые**: roles/storage.objectAdmin, roles/compute.instanceAdmin\n3. **Кастомные**: Детализированные, только на уровне организации\n\n**Лучшие практики:**\n- Группы для управления участниками\n- Роли на максимально высоком уровне (наследование)\n- Service accounts для рабочих нагрузок\n- **Workload Identity** для подов GKE (без ключей service account)\n- Organization Policy для ограничений\n\nВ 2026: IAM Recommender анализирует 90 дней доступа и предлагает удаление избыточных разрешений. Policy Intelligence для автоматизации управления правами.', difficulty: 'intermediate', tags: ['gcp', 'iam', 'организация'] },

  // ===== DEVOPS =====
  { categorySlug: 'devops', title: 'Объясните паттерны проектирования CI/CD пайплайнов', content: 'Опишите распространённые архитектуры CI/CD пайплайнов, антипаттерны и лучшие практики надёжных деплоев.', answer: '**Паттерны пайплайнов:**\n\n1. **Последовательный**: Build → Test → Staging → Production\nПростой, но медленный\n\n2. **Параллельное тестирование**: Build → [Unit | Integration | Security] → Deploy\nБыстрая обратная связь\n\n3. **GitOps**: PR → CI → Merge → ArgoCD синхронизирует из git\nGit — единый источник истины\n\n**Стратегии деплоя:**\n- Rolling update: Постепенная замена\n- Blue/Green: Два идентичных окружения, переключение трафика\n- Canary: Небольшой % трафика на новую версию\n- Feature flags: Переключение функций без деплоя\n\n**Антипаттерны:**\n- Флаковые тесты в CI\n- Деплой в пятницу\n- Ручные approval gates, блокирующие на дни\n- Не версионировать инфраструктуру вместе с кодом\n\nВ 2026:\n- GitHub Actions — стандарт де-факто для CI/CD\n- GitOps через ArgoCD/Flux для K8s\n- Dagger для программируемых пайплайнов на Go/Python/TypeScript\n- SBOM и подписи артефактов (Sigstore/Cosign) в каждом пайплайне\n- Platform Engineering: Internal Developer Platforms (IDP) на базе Backstage', difficulty: 'intermediate', tags: ['ci-cd', 'devops', 'пайплайны', 'деплой'] },

  // ===== МОНИТОРИНГ =====
  { categorySlug: 'monitoring', title: 'Проектирование стратегии мониторинга и алертинга', content: 'Как спроектировать эффективный мониторинг, алертинг и наблюдаемость для продакшн-систем?', answer: '**Три столпа наблюдаемости:**\n1. **Метрики**: Числовые временные ряды (CPU, задержка, частота ошибок)\n2. **Логи**: Записи событий с контекстом (предпочтительно структурированный JSON)\n3. **Трейсы**: Поток запросов через распределённые сервисы\n\n**Принципы алертинга:**\n1. Алерты на симптомах, а не причинах (влияние на пользователя)\n2. Каждый алерт должен быть действенным\n3. Уровни серьёзности: P1 (пейджер) vs P2 (тикет) vs P3 (лог)\n4. Пороги на SLI (задержка p99, частота ошибок >1%)\n5. Избегайте усталости от алертов\n\n**Метод RED** (для сервисов):\n- **R**ate: Запросов в секунду\n- **E**rrors: Процент ошибок\n- **D**uration: Распределение задержки (p50, p95, p99)\n\n**Метод USE** (для ресурсов):\n- **U**tilization: Процент использования\n- **S**aturation: Длина очереди\n- **E**rrors: Количество ошибок\n\n**Стек инструментов (2026):**\n- Метрики: Prometheus + Grafana (или VictoriaMetrics для масштаба)\n- Логи: Grafana Loki или Elasticsearch\n- Трейсы: Grafana Tempo или Jaeger\n- Алертинг: Alertmanager или Grafana OnCall\n- OpenTelemetry — стандарт сбора телеметрии\n\n**SLO-фреймворк**: SLI (метрика) → SLO (цель) → Бюджет ошибок (1 - SLO)', difficulty: 'advanced', tags: ['мониторинг', 'алертинг', 'наблюдаемость', 'slo'] },

  // ===== БАЗЫ ДАННЫХ =====
  { categorySlug: 'databases', title: 'Объясните MVCC и VACUUM в PostgreSQL', content: 'Как PostgreSQL обрабатывает конкурентный доступ с MVCC? Почему VACUUM важен?', answer: '**MVCC (Multi-Version Concurrency Control):**\nКаждая транзакция видит согласованный срез данных на определённый момент времени.\n\n**Как это работает:**\n1. Каждая строка имеет xmin (ID вставившей транзакции) и xmax (ID удалившей/обновившей транзакции)\n2. Транзакция видит строку если: xmin зафиксирована И (xmax пуста ИЛИ xmax не зафиксирована)\n3. UPDATE = DELETE старой строки + INSERT новой (создаёт новую версию)\n4. Читатели никогда не блокируют писателей и наоборот\n\n**Проблема: Мёртвые кортежи**\n- Удалённые/обновлённые строки оставляют «мёртвые кортежи»\n- Они занимают место на диске и замедляют сканирование\n\n**VACUUM:**\n- Обычный VACUUM: Помечает место мёртвых кортежей как повторно используемое\n- VACUUM FULL: Перестраивает таблицу, возвращает диск ОС (эксклюзивная блокировка!)\n- Autovacuum: Запускается автоматически на основе порогов\n\n**Настройка autovacuum:**\n```sql\nALTER TABLE my_table SET (autovacuum_vacuum_scale_factor = 0.05);\n```\n\nВ 2026: PostgreSQL 17+ с улучшенным autovacuum, incremental sort, логической репликацией DDL.\n\nКонтроль: SELECT relname, n_dead_tup FROM pg_stat_user_tables;', difficulty: 'advanced', tags: ['postgresql', 'mvcc', 'vacuum', 'базы-данных'] },
  { categorySlug: 'databases', title: 'Стратегии бэкапа и аварийного восстановления баз данных', content: 'Опишите стратегии резервного копирования и планирование аварийного восстановления.', answer: '**Типы бэкапов:**\n1. **Полный**: Полная копия всех данных (ежедневно/еженедельно)\n2. **Инкрементальный**: Только изменения с последнего бэкапа (ежечасно)\n3. **WAL/Непрерывный**: Point-in-Time Recovery (PITR)\n\n**PostgreSQL:**\n```bash\n# Логический бэкап\npg_dump -Fc mydb > mydb.dump\n\n# Физический бэкап (PITR)\npg_basebackup -D /backup/base -Ft -z -P\n```\n\n**Целевые показатели RPO/RTO:**\n| Стратегия | RPO | RTO |\n|-----------|-----|-----|\n| Ежедневный полный | 24ч | Часы |\n| WAL-стриминг | Секунды | Минуты |\n| Синхронная репликация | Ноль | Секунды |\n| Hot standby | Ноль | Секунды |\n\n**Планирование DR:**\n- Определите RPO (макс. потеря данных) и RTO (макс. простой) для каждого приложения\n- Регулярно тестируйте восстановление (ежемесячно)\n- Автоматизируйте failover через Patroni (PostgreSQL) или Orchestrator (MySQL)\n- Кросс-региональная репликация для географической избыточности\n\nВ 2026: Cloud-native решения (AWS RDS Multi-AZ, Cloud SQL, Neon serverless) упрощают DR.\n\nИнструменты: pgBackRest, Barman, WAL-G для объектных хранилищ.', difficulty: 'intermediate', tags: ['базы-данных', 'бэкап', 'аварийное-восстановление'] },

  // ===== ВЕБ-СЕРВЕРЫ =====
  { categorySlug: 'web-servers', title: 'Настройка Nginx как обратного прокси с балансировкой нагрузки', content: 'Настройте Nginx как обратный прокси с несколькими upstream-серверами.', answer: '**Базовый обратный прокси:**\n```nginx\nupstream backend {\n    least_conn;\n    server 10.0.1.10:8080 weight=3;\n    server 10.0.1.11:8080 weight=2;\n    server 10.0.1.12:8080 backup;\n    keepalive 32;\n}\n\nserver {\n    listen 80;\n    server_name app.example.com;\n\n    location / {\n        proxy_pass http://backend;\n        proxy_http_version 1.1;\n        proxy_set_header Connection "";\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n        proxy_connect_timeout 5s;\n        proxy_read_timeout 30s;\n    }\n}\n```\n\n**Методы балансировки:**\n- round_robin (по умолчанию)\n- least_conn: Наименьшее активных соединений\n- ip_hash: Привязка сессии по IP клиента\n- hash $request_uri: Удобно для кэширования\n\nВ 2026: Nginx Plus с health checks, sticky sessions, API для динамической конфигурации upstream.\n\nДля K8s: Ingress Controller (nginx-ingress) или Gateway API с NGINX Gateway Fabric.', difficulty: 'intermediate', tags: ['nginx', 'обратный-прокси', 'балансировка'] },
  { categorySlug: 'web-servers', title: 'Лучшие практики настройки SSL/TLS для веб-серверов', content: 'Настройте безопасный SSL/TLS для Nginx по стандартам 2026 года.', answer: '**Конфигурация Nginx TLS (Mozilla Modern, 2026):**\n```nginx\nserver {\n    listen 443 ssl http2;\n    server_name example.com;\n\n    ssl_certificate /etc/ssl/certs/example.com.crt;\n    ssl_certificate_key /etc/ssl/private/example.com.key;\n\n    # Только TLS 1.3\n    ssl_protocols TLSv1.3;\n    ssl_prefer_server_ciphers off;\n\n    # OCSP Stapling\n    ssl_stapling on;\n    ssl_stapling_verify on;\n    resolver 1.1.1.1 8.8.8.8 valid=300s;\n\n    # Заголовки безопасности\n    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;\n    add_header X-Content-Type-Options nosniff;\n    add_header X-Frame-Options SAMEORIGIN;\n\n    # Сессия\n    ssl_session_timeout 1d;\n    ssl_session_cache shared:SSL:50m;\n    ssl_session_tickets off;\n}\n```\n\n**Автоматизация сертификатов:**\n```bash\ncertbot --nginx -d example.com\ncertbot renew --dry-run\n```\n\nДля Kubernetes: cert-manager с Let\'s Encrypt или корпоративным CA.\n\n**Тестирование**: ssllabs.com, testssl.sh\n\nВ 2026: Post-quantum криптография (ML-KEM/Kyber) начинает внедряться в TLS. Encrypted Client Hello (ECH) скрывает SNI.', difficulty: 'intermediate', tags: ['nginx', 'ssl', 'tls', 'безопасность'] },
]

async function main() {
  console.log('🌱 Заполнение базы данных...')

  // Очистка существующих данных
  await prisma.questionTag.deleteMany()
  await prisma.aiExplanation.deleteMany()
  await prisma.progress.deleteMany()
  await prisma.userNote.deleteMany()
  await prisma.contentVersion.deleteMany()
  await prisma.updateLog.deleteMany()
  await prisma.syncState.deleteMany()
  await prisma.question.deleteMany()
  await prisma.tag.deleteMany()
  await prisma.category.deleteMany()
  await prisma.user.deleteMany()

  // Создание категорий
  for (const cat of categories) {
    await prisma.category.create({ data: cat })
  }
  console.log(`✅ Создано ${categories.length} категорий`)

  // Создание тегов
  const allTags = new Set<string>()
  questions.forEach(q => q.tags.forEach(t => allTags.add(t)))
  for (const tagName of allTags) {
    await prisma.tag.create({ data: { name: tagName, slug: tagName } })
  }
  console.log(`✅ Создано ${allTags.size} тегов`)

  // Создание вопросов
  let created = 0
  for (const q of questions) {
    const category = await prisma.category.findUnique({ where: { slug: q.categorySlug } })
    if (!category) continue

    const slug = q.title.toLowerCase().replace(/[^a-zа-яё0-9]+/g, '-').replace(/^-|-$/g, '') + '-' + Date.now().toString(36)

    const question = await prisma.question.create({
      data: {
        title: q.title,
        slug,
        content: q.content,
        answer: q.answer,
        difficulty: q.difficulty,
        source: 'github',
        categoryId: category.id,
      },
    })

    // Связь с тегами
    for (const tagName of q.tags) {
      const tag = await prisma.tag.findUnique({ where: { slug: tagName } })
      if (tag) {
        await prisma.questionTag.create({ data: { questionId: question.id, tagId: tag.id } })
      }
    }
    created++
  }
  console.log(`✅ Создано ${created} вопросов`)

  // Демо-пользователь
  await prisma.user.create({
    data: {
      email: 'demo@sysadmin.academy',
      name: 'Демо-пользователь',
      level: 'Новичок',
      xp: 0,
      role: 'admin',
    },
  })
  console.log('✅ Создан демо-пользователь')

  // ИИ-объяснения для всех вопросов
  const allQuestions = await prisma.question.findMany({ include: { category: true } })
  for (const q of allQuestions) {
    await prisma.aiExplanation.create({
      data: {
        questionId: q.id,
        beginnerExplanation: `Это фундаментальная концепция в ${q.category?.name || 'системном администрировании'}. Представьте это как строительный блок — сначала разберитесь в базовых принципах, а затем постепенно углубляйте понимание. Ключевая идея проста: сосредоточьтесь на том, как компоненты работают вместе, и почему они устроены именно так.`,
        intermediateExplanation: `${q.title} включает несколько ключевых компонентов, работающих вместе в ${q.category?.name || 'данной области'}. Понимание их взаимодействий критически важно для эффективного системного администрирования. Обратите внимание на то, как изменения в одном компоненте влияют на поведение всей системы.`,
        advancedExplanation: `На продвинутом уровне ${q.title} требует глубокого понимания внутренних механизмов и влияния на производительность в ${q.category?.name || 'данной области'}. Рассмотрите краевые случаи, сценарии отказов и стратегии оптимизации. Архитектурные решения здесь имеют долгосрочные последствия.`,
        realWorldExample: `В продакшн-среде эта концепция напрямую влияет на надёжность системы. Например, при расследовании инцидента в продакшене понимание данной темы помогает быстро определить корневую причину и реализовать эффективное исправление.`,
        interviewTips: `Когда вас спрашивают об этом на собеседовании, начните с чёткого определения, затем приведите практический пример из вашего опыта. Упомяните распространённые ошибки и как их избежать. Покажите, что вы разбираетесь как в теории, так и на практике. Подготовьте конкретные цифры и метрики из реального опыта.`,
        relatedTopics: (q.category?.name || '') + ', системный дизайн, диагностика, производительность',
        model: 'ai-generated',
      },
    })
  }
  console.log(`✅ Создано ИИ-объяснений: ${allQuestions.length}`)

  // Состояние синхронизации
  await prisma.syncState.create({
    data: {
      repoUrl: 'https://github.com/trimstray/test-your-sysadmin-skills',
      status: 'idle',
    },
  })
  console.log('✅ Создано состояние синхронизации')

  console.log('\n🎉 Заполнение базы данных завершено!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
