import { PrismaClient } from '@prisma/client'

const databaseUrl = process.env.DATABASE_URL || ''
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: databaseUrl.includes('neon.tech')
        ? databaseUrl + (databaseUrl.includes('connect_timeout') ? '' : '&connect_timeout=60&pool_timeout=60&connection_limit=5')
        : databaseUrl
    }
  }
})

const categories = [
  { name: 'Основы Linux', slug: 'linux-fundamentals', description: 'Основы Linux/Unix: командная строка, базовые утилиты, структура системы, ядро, загрузка, процессы', icon: 'Terminal', order: 1 },
  { name: 'Системное администрирование', slug: 'sysadmin', description: 'Управление пользователями и процессами, дисками и файловыми системами, загрузчиками, сервисами, пакетами, мониторинг системы', icon: 'Settings', order: 2 },
  { name: 'Серверы Linux', slug: 'linux-servers', description: 'Настройка web, DNS, DHCP, баз данных, файловых серверов, почтовых серверов, SSH', icon: 'Server', order: 3 },
  { name: 'Хранилище Linux', slug: 'linux-storage', description: 'Управление дисками, разделами, RAID, LVM, ZFS, Stratis, NFS, iSCSI, автомонтирование', icon: 'HardDrive', order: 4 },
  { name: 'Безопасность Linux', slug: 'linux-security', description: 'Права доступа, ACL, SELinux, AppArmor, PAM, пользователи и пароли, файрволы, аудит', icon: 'Shield', order: 5 },
  { name: 'Сети', slug: 'networking', description: 'TCP/IP, DNS, маршрутизация, файрволы, VPN, устранение неполадок сети', icon: 'Network', order: 6 },
  { name: 'Bash', slug: 'bash', description: 'Скриптинг, автоматизация, обработка текста, командная строка', icon: 'Code', order: 7 },
  { name: 'Docker', slug: 'docker', description: 'Контейнеризация, Dockerfiles, Docker Compose, управление образами', icon: 'Container', order: 8 },
  { name: 'Kubernetes', slug: 'kubernetes', description: 'Архитектура K8s, поды, сервисы, деплойменты, Helm, управление кластером', icon: 'Blocks', order: 9 },
  { name: 'Terraform', slug: 'terraform', description: 'Infrastructure as Code, HCL, управление состоянием, модули, провайдеры', icon: 'Layers', order: 10 },
  { name: 'Ansible', slug: 'ansible', description: 'Управление конфигурацией, плейбуки, роли, инвентарь, автоматизация', icon: 'Play', order: 11 },
  { name: 'AWS', slug: 'aws', description: 'Amazon Web Services: EC2, S3, Lambda, VPC, IAM, облачная архитектура', icon: 'Cloud', order: 12 },
  { name: 'Azure', slug: 'azure', description: 'Microsoft Azure: VMs, Blob Storage, Functions, Active Directory, Bicep', icon: 'CloudRain', order: 13 },
  { name: 'GCP', slug: 'gcp', description: 'Google Cloud: Compute Engine, Cloud Storage, BigQuery, GKE, IAM', icon: 'CloudSun', order: 14 },
  { name: 'DevOps', slug: 'devops', description: 'CI/CD, GitOps, культура DevOps, SRE, управление релизами', icon: 'GitBranch', order: 15 },
  { name: 'Мониторинг', slug: 'monitoring', description: 'Наблюдаемость, Prometheus, Grafana, ELK, алертинг, управление инцидентами', icon: 'Activity', order: 16 },
  { name: 'Базы данных', slug: 'databases', description: 'SQL, PostgreSQL, MySQL, Redis, MongoDB, репликация, бэкап, оптимизация', icon: 'Database', order: 17 },
  { name: 'Веб-серверы', slug: 'web-servers', description: 'Nginx, Apache, обратный прокси, балансировка, SSL/TLS, оптимизация', icon: 'Globe', order: 18 },
  { name: 'eBPF', slug: 'ebpf', description: 'eBPF-программы, BCC, bpftrace, XDP, наблюдаемость ядра', icon: 'Zap', order: 19 },
  { name: 'Облачная безопасность', slug: 'cloud-security', description: 'IAM, WAF, защита облака, комплаенс, аудит, постквантовая криптография', icon: 'Lock', order: 20 },
]

type Q = { c: string; t: string; q: string; a: string; d: string; tags: string[] }

const questions: Q[] = [
// ================================================================
// КНИГА 1: LINUX FUNDAMENTALS — основы Linux/Unix
// Командная строка, базовые утилиты, структура системы
// ================================================================
{c:'linux-fundamentals',t:'Как устроена файловая иерархия Linux?',q:'Опишите назначение основных каталогов в корневой файловой системе Linux согласно FHS.',a:'Согласно Filesystem Hierarchy Standard (FHS), корневая файловая система Linux организована так:\n\n## Основные элементы\n\n- **`/bin`** — основные исполняемые файлы пользователя (ls, cp, mv, bash)\n- **`/sbin`** — системные исполняемые файлы (fdisk, mkfs, systemctl)\n- **`/boot`** — файлы загрузчика и ядра (vmlinuz, initramfs, GRUB)\n- **`/dev`** — файлы устройств (sda, tty, null, random)\n- **`/etc`** — конфигурационные файлы системы и приложений\n- **`/home`** — домашние каталоги пользователей\n- **`/root`** — домашний каталог суперпользователя\n- **`/lib` и `/lib64`** — разделяемые библиотеки и модули ядра\n- **`/media` и `/mnt`** — точки монтирования съёмных и временных файловых систем\n- **`/opt`** — дополнительные программные пакеты\n- **`/proc`** — виртуальная ФС с информацией о процессах и ядре\n- **`/sys`** — виртуальная ФС для взаимодействия с драйверами\n- **`/tmp`** — временные файлы, очищаемые при перезагрузке\n- **`/usr`** — пользовательские программы и библиотеки (вторичная иерархия)\n- **`/var`** — изменяемые данные: логи, почта, кэш, базы данных.\n\nВ современных дистрибутивах `/bin` и `/sbin` часто являются символическими ссылками на `/usr/bin` и `/usr/sbin` (merge usr).',d:'beginner',tags:['fhs','файловая-система','структура']},
{c:'linux-fundamentals',t:'Как работает процесс загрузки Linux?',q:'Опишите полную последовательность загрузки Linux от включения до инициализации пользовательского пространства.',a:'Процесс загрузки Linux в 2026 году:\n\n## Этапы\n\n1. **BIOS/UEFI POST** — проверка оборудования при включении;\n2. **Загрузчик GRUB2 или systemd-boot** — находится в EFI-разделе, загружает ядро и initramfs в память;\n3. **Инициализация ядра** — распаковка, обнаружение оборудования, загрузка драйверов из initramfs, монтирование корневой файловой системы;\n4. **PID 1 (systemd)** — первый пользовательский процесс;\n5. **Цели systemd** — последовательно активирует юниты: монтирует ФС, запускает сервисы, достигает default.target;\n6. **Getty/Login** — TTY или дисплейный менеджер предлагает вход. Современные дополнения 2026: systemd-boot как альтернатива GRUB для UEFI-систем; UKI (Unified Kernel Image) — ядро, initramfs и командная строка объединены в один EFI-бинарник; Measured Boot через TPM для верификации цепочки загрузки.',d:'intermediate',tags:['загрузка','grub','systemd','ядро']},
{c:'linux-fundamentals',t:'Чем отличается процесс от потока в Linux?',q:'Объясните фундаментальные различия между процессами и потоками в Linux, включая модель памяти, переключение контекста и механизмы коммуникации.',a:'Процесс — независимая единица выполнения с собственным адресным пространством.\n\nПоток — легковесный подпроцесс, разделяющий адресное пространство родителя, но имеющий собственный стек и регистры.  Ключевые отличия: процессы обладают отдельными адресными пространствами, потоки разделяют одно.\nПереключение потоков быстрее, поскольку сохраняется меньше состояния.  Потоки общаются через разделяемую память, процессы используют IPC — каналы, сокеты, сигналы.\nСоздание потока обходится дешевле.  Сбой потока может повредить весь процесс, тогда как сбой процесса не затрагивает остальные.\nВ ядре Linux 6. x и процессы, и потоки планируются как задачи через CFS scheduler.\nПотоки реализованы через системный вызов clone() с флагами совместного доступа к памяти.',d:'beginner',tags:['процессы','потоки','ядро']},
{c:'linux-fundamentals',t:'Что такое ядро Linux и как загружать модули?',q:'Объясните роль ядра Linux, отличие монолитного ядра от модульного, и управление модулями ядра.',a:'Ядро Linux — монолитное с поддержкой загружаемых модулей.\n\n## Основные элементы\n\n- Оно управляет процессором, памятью, устройствами, файловыми системами и сетевым стеком. Монолитное ядро выполняет все функции в одном адресном пространстве для максимальной производительности. Модульная архитектура позволяет загружать и выгружать компоненты (драйверы, файловые системы, сетевые протоколы) без перезагрузки. Управление модулями: lsmod — список загруженных модулей\n- **insmod MODULE** — загрузить модуль\n- **rmmod MODULE** — выгрузить модуль\n- **modprobe MODULE** — загрузить с зависимостями\n- **`modprobe -r MODULE`** — выгрузить с зависимостями\n- **modinfo MODULE** — информация о модуле. Конфигурация: `/etc/modprobe.d/` для параметров и чёрных списков. В 2026 году ядро Linux 6.x поддерживает eBPF-программы как новый тип модулей для наблюдаемости и фильтрации без написания кода ядра.',d:'intermediate',tags:['ядро','модули','драйверы']},
{c:'linux-fundamentals',t:'Как работают каналы и перенаправление ввода-вывода?',q:'Объясните pipes, перенаправление stdout/stderr, here-documents и process substitution.',a:'Перенаправление ввода-вывода:\n\n## Основные элементы\n\n- **command > file** — stdout в файл (перезапись)\n- **command >> file** — stdout в файл (добавление)\n- **command 2> file** — stderr в файл\n- **command &> file** — stdout и stderr в файл\n- **command < file** — stdin из файла\n- **command 2>&1** — stderr перенаправить туда же, куда stdout. Каналы (pipes) передают stdout одной команды на stdin другой: ls -la | grep ".txt" | wc -l. Данные проходят через буфер ядра размером 64 КБ. Here-documents позволяют передать многострочный текст: cat << EOF ... EOF. Here-string: read VAR <<< "value". Process substitution передаёт вывод команды как файл: diff <(sort file1) <(sort file2), создавая файловый дескриптор в `/dev/fd/.` Именованные каналы (FIFO): mkfifo `/tmp/pipe` — работают как файлы, данные читаются и пишутся разными процессами. Tee-фильтр: команда | tee file — дублирует stdout в файл и на экран одновременно.',d:'beginner',tags:['pipes','перенаправление','ввод-вывод']},
{c:'linux-fundamentals',t:'Что такое /proc и /sys в Linux?',q:'Объясните виртуальные файловые системы /proc и /sys, их структуру и практическое применение.',a:'/proc — виртуальная файловая система (procfs), предоставляющая информацию о процессах и ядре.\n\n## Основные элементы\n\n- **Каждый процесс имеет каталог `/proc/PID/` с файлами: cmdline** — командная строка запуска\n- **status** — статус и память\n- **fd/** — открытые файловые дескрипторы\n- **maps** — отображение памяти\n- **environ** — переменные окружения. Общесистемные параметры: `/proc/cpuinfo` — информация о процессорах\n- **`/proc/meminfo`** — статистика памяти\n- **`/proc/loadavg`** — нагрузка\n- **`/proc/mounts`** — монтированные ФС\n- **`/proc/partitions`** — дисковые разделы\n- **`/proc/version`** — версия ядра. `/sys` (sysfs) — интерфейс к объектам ядра: `/sys/devices/` — дерево устройств\n- **`/sys/class/`** — устройства по классам (net, block)\n- **`/sys/block/`** — блочные устройства\n- **`/sys/module/`** — модули ядра. Практика: чтение параметров через cat `/proc/sys/net/ipv4/ip_forward`\n- запись через echo 1 > `/proc/sys/net/ipv4/ip_forward`\n- лучше использовать `sysctl -w net.ipv4.ip_forward=1.`',d:'intermediate',tags:['proc','sys','ядро','виртуальные-фс']},
{c:'linux-fundamentals',t:'Как работает планировщик задач Linux?',q:'Объясните алгоритм CFS, приоритеты процессов, nice values и real-time scheduling.',a:'CFS (Completely Fair Scheduler) — стандартный планировщик Linux. Принцип:\n\nкаждый процесс получает справедливую долю процессорного времени.  CFS использует красно-чёрное дерево для отслеживания виртуального времени выполнения (vruntime) каждого процесса.\nЗадача с наименьшим vruntime выбирается следующей.  Приоритеты: nice value от -20 (наивысший) до +19 (низший), по умолчанию 0.\nТолько root может установить отрицательное значение.  Каждый шаг nice примерно на 10% меняет долю CPU.\nReal-time планирование: SCHED_FIFO и SCHED_RR для задач реального времени с приоритетами от 1 до 99.  Real-time задачи всегда имеют приоритет над обычными.\nSCHED_DEADLINE для задач с жёсткими дедлайнами.  Управление: chrt для изменения политики планирования, renice для nice value, taskset для привязки к CPU.',d:'advanced',tags:['планировщик','cfs','процессы','ядро']},
{c:'linux-fundamentals',t:'Объясните сигналы в Linux',q:'Что такое сигналы, как они обрабатываются и какие наиболее часто используются?',a:'Сигналы — уведомления ядра или процессов о событиях.\n\n## Этапы\n\n1. Процесс может перехватить большинство сигналов и обработать их, либо использовать обработчик по умолчанию. Основные сигналы: SIGHUP (\n2. — перезагрузка конфигурации; SIGINT (\n3. — прерывание с клавиатуры (Ctrl+C); SIGQUIT (\n4. — завершение с дампом памяти (Ctrl+\\); SIGKILL (\n5. — принудительное завершение (нельзя перехватить); SIGTERM (\n6. 1\n7. — корректное завершение; SIGSTOP (\n8. 1\n9. — остановка (нельзя перехватить); SIGCONT (\n10. 1\n11. — продолжение; SIGUSR1`/SIGUSR2` — пользовательские сигналы. Отправка: kill -SIGNAL PID; killall -SIGNAL NAME; pkill -f pattern. Обработка в Bash: trap "handler" SIGNAL. Пример: trap "rm -f `$TMPFILE`; exit" EXIT INT TERM. SIGKILL и SIGSTOP невозможно перехватить, заблокировать или игнорировать — ядро гарантирует их доставку. SIGTERM предпочтительнее SIGKILL, так как позволяет процессу корректно освободить ресурсы.',d:'beginner',tags:['сигналы','процессы','управление']},
{c:'linux-fundamentals',t:'Как работает пакетный менеджмент в Linux?',q:'Сравните пакетные менеджеры apt, dnf, zypper и pacman. Как управлять пакетами в разных дистрибутивах?',a:'APT (Debian/Ubuntu):\n\n## Основные элементы\n\n- **apt update** — обновить индексы\n- **apt upgrade** — обновить пакеты\n- **apt install PKG** — установить\n- **apt remove PKG** — удалить\n- **apt search QUERY** — найти\n- **apt show PKG** — информация. Конфигурация: `/etc/apt/sources.list` и `/etc/apt/sources.list.d/.` DNF (Fedora`/RHEL` 8+): dnf install`/remove/search/info`\n- dnf update\n- dnf list installed\n- **dnf clean all. Группы**: dnf group install "Development Tools". Модули: dnf module list\n- **dnf module enable nodejs:18. Zypper (openSUSE)**: zypper install`/remove/search/info`\n- **zypper up** — обновление\n- **zypper dup** — обновление дистрибутива\n- **zypper lr** — репозитории. Pacman (Arch): `pacman -S PKG — установить`\n- **`pacman -R PKG`** — удалить\n- **`pacman -Syu`** — обновить систему\n- **`pacman -Ss QUERY`** — найти\n- **`pacman -Qi PKG`** — информация. Универсальные решения 2026: Flatpak и Snap для дистрибутивно-независимых пакетов\n- nix для воспроизводимого управления пакетами.',d:'beginner',tags:['пакеты','apt','dnf','pacman']},
{c:'linux-fundamentals',t:'Что такое пространства имён и контрольные группы?',q:'Объясните Linux namespaces и cgroups, их типы и роль в контейнеризации.',a:'Namespaces изолируют то, что процесс видит:\n\n## Основные элементы\n\n- **PID** — идентификаторы процессов\n- **NET** — сетевой стек\n- **MNT** — точки монтирования\n- **UTS** — имя хоста\n- **IPC** — межпроцессное взаимодействие\n- **USER** — идентификаторы пользователей и групп\n- **CGROUP** — корневой каталог cgroup\n- **TIME** — часы. Cgroups ограничивают ресурсы: CPU (cpu, cpuset)\n- память (memory)\n- ввод-вывод (io)\n- устройства (devices)\n- **PID (pids). В 2026 году стандарт** — cgroups v2 с единой иерархией и лучшей производительностью. Вместе namespaces и cgroups — фундамент Linux-контейнеров. Namespaces дают изоляцию, cgroups — ограничение ресурсов. Команды: `unshare --pid --mount --net`\n- lsns\n- cat `/proc/PID/cgroup`\n- systemd-run --property=MemoryMax=512M.',d:'intermediate',tags:['namespaces','cgroups','контейнеры','ядро']},
{c:'linux-fundamentals',t:'Объясните виртуальную память и OOM Killer',q:'Как работает виртуальная память? Что запускает OOM Killer и как он выбирает жертву?',a:'Виртуальная память Linux предоставляет каждому процессу изолированное адресное пространство через таблицы страниц, управляемые MMU.\n\nФизическая RAM отображается на виртуальные адреса страницами по 4 КБ или huge pages.  Ключевые концепции: swap выгружает редко используемые страницы на диск; page cache хранит недавно прочитанные данные файлов в RAM; overcommit позволяет выделять больше виртуальной памяти, чем физической RAM.\nOOM Killer срабатывает, когда нет свободной памяти и swap исчерпан, превышен коэффициент overcommit, или нет страниц для reclaim.  Выбор жертвы основан на oom_score: потребление памяти, приоритет oom_score_adj от -1000 до +1000, nice value, количество дочерних процессов.\nПрофилактика: установите oom_score_adj=-1000 для критических процессов, используйте cgroups v2 memory limits, настройте vm. overcommit_ratio.',d:'advanced',tags:['память','oom','ядро','виртуальная-память']},
{c:'linux-fundamentals',t:'Как устранить высокую загрузку CPU на сервере?',q:'Сервер Linux испытывает высокую нагрузку на процессор. Опишите систематический подход к устранению неполадок.',a:'Систематический подход:\n\n## Этапы\n\n1. Определите процесс: top, htop, ps aux --sort=-%cpu | `head -20`;\n2. Анализ CPU: `mpstat -P ALL 1 для разделения user`/system/iowait/steal`;`\n3. Детали процесса: `pidstat -p PID 1, strace -c -p PID;`\n4. Общесистемный анализ: vmstat 1, `sar -u 1 5;`\n5. Flame graphs: perf `record -g -p PID;`\n6. **Профилирование: Java** — jstack, jmap; Python — py-spy; Node — --prof. Частые причины: бесконечные циклы, штормы garbage collection, криптографические операции, компиляция, проблемы ядра. Быстрые меры: renice, cpulimit, cgroups v2 cpu.max, taskset для привязки к CPU.\n\n## Актуальность 2026\n\nВ 2026: eBPF-инструменты (bcc, bpftrace) для низкоуровневого профилирования; Cilium Hubble для наблюдаемости сетевого стека.',d:'intermediate',tags:['cpu','диагностика','производительность']},
{c:'linux-fundamentals',t:'Как работают файловые системы ext4, XFS и Btrfs?',q:'Сравните основные файловые системы Linux: ext4, XFS и Btrfs.',a:'ext4: журнал-файловая система, стандарт для большинства дистрибутивов.\n\n## Основные элементы\n\n- **Максимальный размер файла 16 ТБ, ФС** — 1 ЭБ. Журналирование: ordered (по умолчанию), writeback, journal. Инструменты: mkfs.ext4, tune2fs, e2fsck, resize2fs. XFS: высокопроизводительная ФС от SGI, стандарт в RHEL. Отлично работает с большими файлами и параллельным IO. Только увеличение (не уменьшение). Инструменты: mkfs.xfs, xfs_repair, xfs_growfs, xfs_fsr. Btrfs: Copy-on-Write ФС с встроенными снапшотами, компрессией, дедупликацией, RAID, чек-суммами. Инструменты: mkfs.btrfs, btrfs subvolume create`/snapshot`, btrfs balance, btrfs scrub. Рекомендации 2026: ext4 — для надёжности и совместимости\n- **XFS** — для больших файлов и высокой нагрузки\n- **Btrfs** — для снапшотов и компрессии (SUSE, Synology).',d:'intermediate',tags:['файловые-системы','ext4','xfs','btrfs']},
{c:'linux-fundamentals',t:'Что такое systemd и как он управляет сервисами?',q:'Объясните архитектуру systemd, юнит-файлы, цели и типичные команды управления сервисами.',a:'systemd — система инициализации (PID 1) для современных дистрибутивов Linux. Типы юнитов:\n\n## Основные элементы\n\n- **service, socket, timer, target, mount, path, slice, scope. Ключевые каталоги: `/etc/systemd/system/`** — локальные переопределения\n- **`/lib/systemd/system/`** — юниты пакетов\n- **`/run/systemd/system/`** — runtime юниты. Команды: systemctl start`/stop/restart/reload` SERVICE\n- systemctl enable`/disable` SERVICE для автозапуска\n- systemctl status SERVICE\n- `journalctl -u SERVICE -f для логов`\n- systemctl list-units --type=service\n- **systemctl `list-timers --all`. Цели заменяют runlevels**: multi-user.target (runlevel 3)\n- graphical.target (runlevel 5)\n- **rescue.target, emergency.target. Кастомные переопределения**: systemctl edit SERVICE создаёт drop-in override. Новое\n\nв 2026: systemd-sysupdate для автоматического обновления системы; systemd-mount для динамического монтирования; улучшенная поддержка systemd-homed.',d:'beginner',tags:['systemd','сервисы','init']},
{c:'linux-fundamentals',t:'Как работает механизм inotify в Linux?',q:'Объясните inotify, его применение для мониторинга файловых событий и ограничения.',a:'inotify — подсистема ядра Linux для мониторинга событий файловой системы:\n\n## Основные элементы\n\n- создание, удаление, модификация, перемещение, доступ к файлам и каталогам. Работает через файловый дескриптор, события читаются через read(). Использование: inotify_init() — создать дескриптор\n- **inotify_add_watch()** — добавить наблюдение\n- **read()** — читать события. Утилиты: inotifywait (пакет inotify-tools) — командная строка. Пример: `inotifywait -m -r `/data` — мониторинг каталога рекурсивно`\n- **`inotifywait -e modify,create,delete `/var/log``** — фильтр по событиям. Применение: автозапуск тестов при изменении кода\n- синхронизация файлов\n- горячая перезагрузка конфигурации\n- аудит доступа к файлам\n- **индексация для поиска. Ограничения**: `/proc/sys/fs/inotify/max_user_watches` (обычно 8192)\n- не работает с NFS (события только локальные)\n- **каждый watch** — overhead в ядре.\n\n## Актуальность 2026\n\nВ 2026: fanotify — более мощная альтернатива для системного аудита.',d:'intermediate',tags:['inotify','мониторинг','файловая-система']},
{c:'linux-fundamentals',t:'Как использовать основные утилиты командной строки?',q:'Опишите назначение и ключевые опции утилит: ls, cp, mv, rm, find, xargs, tee, wc, cut, sort, uniq, tr.',a:'ls — список файлов:\n\nls -la (подробно с скрытыми), ls -lh (читаемые размеры), ls -lt (по времени), ls -lS (по размеру).  cp — копирование: cp -r src/ dst/ (рекурсивно), cp -a (архивный режим, сохраняет всё), cp -u (только новые).\nmv — перемещение/переименование: mv old new.  rm — удаление: `rm -r dir/ (рекурсивно), rm -f (без подтверждения).`\nfind — поиск: find / -name "*. conf" -mtime -7 (изменённые за 7 дней), find / -type f -size +100M (файлы больше 100 МБ), find / -perm -4000 (SUID-файлы).\nxargs — передача аргументов: find .  -name "*.\nlog" | xargs rm.  tee — дублирование вывода: echo "text" | tee file.\ntxt.  wc — подсчёт: `wc -l file (строки), wc -w (слова), wc -c (байты).`\ncut — извлечение столбцов: cut -d: -f1 `/etc/passwd.`  sort — сортировка: sort -n (числовая), sort -r (обратная), sort -u (уникальные).\nuniq — дедупликация: sort file | `uniq -c (подсчёт).`  tr — замена символов: tr "A-Z" "a-z" (в нижний регистр), `tr -d "0-9" (удалить цифры).`',d:'beginner',tags:['утилиты','команды','cli']},
{c:'linux-fundamentals',t:'Как работает механизм swap в Linux?',q:'Объясните назначение swap, типы (раздел и файл), параметры настройки и влияние на производительность.',a:'Swap — пространство на диске, куда ядро выгружает редко используемые страницы памяти. Назначение:\n\nрасширение доступной памяти, защита от OOM, возможность гибернации. Типы: swap-раздел (mkswap `/dev/sda2`, swapon `/dev/sda2`) и swap-файл (dd if=`/dev/zero` of=`/swapfile` bs=1M count=4096, chmod 600 `/swapfile`, mkswap `/swapfile`, swapon `/swapfile`). Параметры: vm.swappiness (0-100) — склонность к swap, по умолчанию 60. Для десктопов: 10-30 (меньше swap, больше RAM). Для серверов БД: 1-10 (минимум swap). Проверка: `swapon --show`, `free -h`, cat `/proc/swaps.` Удаление: swapoff `/swapfile`, rm `/swapfile.` Постоянная конфигурация: `/etc/fstab` — `/swapfile` none swap sw 0 0. В 2026: zswap — сжатый кэш swap в RAM, уменьшает IO диска; zram — сжатый RAM-диск как swap, эффективен для систем с малой памятью. Для SSD: swap полезен, но следите за износом через SMART.',d:'intermediate',tags:['swap','память','производительность']},
{c:'linux-fundamentals',t:'Как настроить переменные окружения в Linux?',q:'Объясните типы переменных окружения, файлы конфигурации оболочки и методы экспорта.',a:'Типы переменных:\n\n## Основные элементы\n\n- локальные (только в текущем shell), окружения (доступны дочерним процессам), системные (для всех пользователей). Установка: VAR=value — локальная\n- **export VAR=value** — переменная окружения\n- **unset VAR** — удаление. Файлы конфигурации Bash: `/etc/profile` — общесистемный логин\n- **`/etc/bash.bashrc`** — общесистемный интерактивный\n- **~/.bash_profile или ~/.profile** — пользовательский логин\n- **~/.bashrc** — пользовательский интерактивный. Порядок загрузки: login shell читает `/etc/profile`, затем первый найденный из ~/.bash_profile, ~/.bash_login, ~/.profile. Интерактивный non-login: ~/.bashrc. Системные переменные: `/etc/environment` (KEY=VALUE без export)\n- **`/etc/profile.d/`*.sh (скрипты с export). Просмотр: env** — все переменные окружения\n- **printenv VAR** — конкретная\n- **echo `$VAR`** — значение. Частые переменные: PATH — пути поиска программ\n- **HOME** — домашний каталог\n- **USER** — текущий пользователь\n- **LANG** — локаль\n- **EDITOR** — текстовый редактор\n- **PS1** — приглашение командной строки.',d:'beginner',tags:['переменные','окружение','bash','конфигурация']},

// ================================================================
// КНИГА 2: SYSTEM ADMINISTRATION — системное администрирование
// Управление пользователями, процессами, дисками, загрузчиками,
// сервисами, пакетами, мониторинг
// ================================================================
{c:'sysadmin',t:'Как управлять пользователями в Linux?',q:'Опишите создание, модификацию и удаление пользователей, структуру /etc/passwd и /etc/shadow.',a:'Создание:\n\n## Основные элементы\n\n- useradd -m -s `/bin/bash` -G docker,sudo username. Опция -m создаёт домашний каталог, -s задаёт оболочку, -G — дополнительные группы. Модификация: usermod -aG group username — добавить в группу\n- **`usermod -L username`** — заблокировать\n- **`usermod -U`** — разблокировать\n- **`usermod -s `/bin/zsh` username`** — сменить оболочку\n- **`usermod -d `/new/home` username`** — сменить домашний каталог. Удаление: userdel username — без домашнего каталога\n- **`userdel -r username`** — с домашним каталогом и почтой. Структура `/etc/passwd`: username:x:UID:GID:comment:home:shell. Поле x указывает, что пароль хранится в `/etc/shadow.` Структура `/etc/shadow`: username:hash:lastchange:min:max:warn:inactive:expire. Формат хеша: $id$salt$hash, где id=6 — SHA-512, id=y — yescrypt (стандарт 2026). Группы: `/etc/group` — имя:password:GID:members. Управление: groupadd, groupmod, groupdel, `gpasswd -a user group.`',d:'beginner',tags:['пользователи','useradd','passwd']},
{c:'sysadmin',t:'Как управлять группами в Linux?',q:'Опишите создание групп, добавление пользователей в группы и управление членством.',a:'Группы позволяют организовать пользователей для совместного доступа к ресурсам. Создание:\n\n## Основные элементы\n\n- **groupadd developers** — создать группу\n- **`groupadd -g 2000 testers`** — с конкретным GID. Модификация: `groupmod -n newname oldname — переименовать`\n- **`groupmod -g 2001 testers`** — сменить GID. Удаление: groupdel developers. Управление членством: usermod -aG developers username — добавить пользователя в группу\n- **`gpasswd -a username developers`** — альтернативный способ\n- **`gpasswd -d username developers`** — удалить из группы\n- **`gpasswd -M user1,user2,user3 developers`** — установить список членов. Первичная группа: указана в `/etc/passwd` (GID)\n- **дополнительная** — в `/etc/group.` Команда groups username показывает все группы пользователя. Команда newgrp developers временно切换ает первичную группу. Специальные группы: wheel`/sudo` — права суперпользователя\n- **docker** — управление Docker\n- **www-data** — веб-сервер.\n\n## Актуальность 2026\n\nВ 2026: sssd для интеграции с LDAP`/Active` Directory.',d:'beginner',tags:['группы','usermod','членство']},
{c:'sysadmin',t:'Как управлять процессами в Linux?',q:'Опишите мониторинг процессов, управление приоритетами и job control.',a:'Мониторинг:\n\n## Основные элементы\n\n- **ps aux** — все процессы\n- **`ps -ef`** — полный формат\n- **`ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem`** — кастомный вывод\n- **top и htop** — интерактивный мониторинг\n- **`pgrep -f pattern`** — найти PID по шаблону. Управление приоритетами: `nice -n 10 command — запустить с пониженным приоритетом`\n- **`renice -n 5 -p PID`** — изменить приоритет\n- **диапазон nice: -20 (наивысший) до 19 (низший). Job control: command &** — запустить в фоне\n- **jobs** — список фоновых задач\n- **fg %1** — вывести на передний план\n- **bg %1** — продолжить в фоне\n- **Ctrl+Z** — приостановить\n- **disown %1** — отвязать от оболочки. Сигналы: `kill -TERM PID — корректное завершение`\n- **`kill -KILL PID`** — принудительное\n- **killall process_name** — по имени. Системные лимиты: `/proc/PID/limits`\n- `ulimit -a`\n- `/etc/security/limits.conf.`',d:'beginner',tags:['процессы','ps','nice','jobs']},
{c:'sysadmin',t:'Как настроить cron и планирование задач?',q:'Объясните формат crontab, anacron, systemd timers и лучшие практики.',a:'Формат crontab:\n\n## Основные элементы\n\n- **Минута Час День_месяца Месяц День_недели Команда. Примеры: 0 2 * * * `/opt/backup.sh`** — каждый день в 2:00\n- ***/15 * * * * `/opt/check.sh`** — каждые 15 минут\n- **0 0 1 * * `/opt/monthly.sh`** — первого числа каждого месяца. Специальные строки: @yearly, @monthly, @weekly, @daily, @hourly, @reboot — при загрузке. Управление: `crontab -e — редактировать`\n- **`crontab -l`** — показать\n- **`crontab -r`** — удалить. Anacron: для машин, которые не работают постоянно. Выполняет пропущенные задачи. Конфигурация в `/etc/anacrontab.` Systemd timers (рекомендация 2026): [Unit] Description=Backup\n- [Timer] OnCalendar=*-*-* 02:00:00 Persistent=true\n- **[Install] WantedBy=timers.target. Лучшая практика**: всегда указывайте полный путь\n- перенаправляйте вывод\n- используйте flock для предотвращения параллельного запуска.',d:'intermediate',tags:['cron','anacron','systemd-timers']},
{c:'sysadmin',t:'Как работает система логирования в Linux?',q:'Опишите journald, rsyslog, ротацию логов и централизованный сбор.',a:'Journald (systemd):\n\n## Основные элементы\n\n- **journalctl** — все логи\n- **`journalctl -u nginx`** — логи сервиса\n- **`journalctl -f`** — в реальном времени\n- `journalctl --since "1 hour ago"`\n- **`journalctl -p err`** — только ошибки\n- **`journalctl -b`** — текущая загрузка\n- **`journalctl -b -1`** — предыдущая. Хранилище: `/var/log/journal/` (постоянное). Конфигурация: `/etc/systemd/journald.conf` — Storage=persistent, SystemMaxUse=500M. Rsyslog: `/etc/rsyslog.conf` и `/etc/rsyslog.d/.` Формат: facility.severity action. Пример: authpriv.* `/var/log/secure`\n- *.info\n- **mail.none `/var/log/messages.` Ротация: logrotate** — автоматическое сжатие и удаление. Конфигурация: `/etc/logrotate.conf` и `/etc/logrotate.d/.` Параметры: daily`/weekly/monthly`, rotate 7, compress, missingok, notifempty, postrotate. Централизованный сбор: Fluentd, Vector или Logstash отправляют логи в Elasticsearch, Loki или ClickHouse.\n\n## Актуальность 2026\n\nВ 2026: Grafana Loki с Promtail — популярное решение с эффективным сжатием.',d:'intermediate',tags:['логирование','journald','rsyslog','logrotate']},
{c:'sysadmin',t:'Как настроить GRUB2 и параметры ядра?',q:'Объясните конфигурацию GRUB2, параметры загрузки ядра и восстановление после сбоя загрузчика.',a:'Конфигурация GRUB2:\n\n## Основные элементы\n\n- **`/etc/default/grub`** — основные параметры. GRUB_DEFAULT=0 — пункт по умолчанию\n- **GRUB_TIMEOUT=5** — таймаут меню\n- **GRUB_CMDLINE_LINUX** — параметры ядра для обычной загрузки. После редактирования: update-grub (Debian`/Ubuntu`) или grub2-mkconfig -o `/boot/grub2/grub.cfg` (RHEL). Полезные параметры ядра: quiet — меньше сообщений\n- **systemd.unit=rescue.target** — rescue mode\n- **maxcpus=1** — ограничить CPU\n- **mem=4G** — ограничить память. Восстановление: загрузиться с Live USB, смонтировать корневую ФС, chroot, grub-install `/dev/sda.` Для UEFI: grub-install --target=x86_64-efi --efi-directory=`/boot/efi.` В 2026: systemd-boot — альтернатива для UEFI. Проще: bootctl install, конфигурация в `/boot/loader/entries/.` UKI (Unified Kernel Image) объединяет ядро, initramfs и параметры в единый EFI-бинарник.',d:'advanced',tags:['grub','загрузчик','ядро','параметры']},
{c:'sysadmin',t:'Как мониторить ресурсы системы в реальном времени?',q:'Опишите инструменты мониторинга CPU, памяти, диска и сети.',a:'CPU: top/htop — интерактивный мониторинг; mpstat -P ALL 1 — по ядрам; vmstat 1 — сводка CPU/памяти/IO; sar -u 1 5 — историческая статистика.\n\n## Основные элементы\n\n- **Память: `free -h`** — RAM и swap\n- **vmstat 1** — подробная\n- **slabtop** — кэши ядра\n- **cat `/proc/meminfo`** — детальная\n- **smem** — по процессам с USS`/PSS/RSS.` Диск: `iostat -xz 1 — загрузка и задержки`\n- **iotop** — по процессам\n- **`df -h`** — место на ФС\n- **`du -sh `/path``** — размер каталога\n- **lsblk** — блочные устройства\n- **ncdu** — интерактивный анализатор. Сеть: `ss -tunlp — сокеты`\n- **nethogs** — трафик по процессам\n- **iftop** — по соединениям\n- **nload** — загрузка интерфейсов. Комплексные: glances — единая панель\n- **btop** — современный htop\n- **netdata** — веб-мониторинг. eBPF: bpftrace, BCC tools (biosnoop, ext4slower, tcplife) — наблюдаемость на уровне ядра.',d:'intermediate',tags:['мониторинг','top','iostat','производительность']},
{c:'sysadmin',t:'Как настроить sudo и его безопасность?',q:'Объясните конфигурацию sudoers, принцип наименьших привилегий и аудит команд.',a:'sudo позволяет выполнять команды от имени другого пользователя с контролем и логированием. Конфигурация:\n\n## Основные элементы\n\n- **`/etc/sudoers` редактируется ТОЛЬКО через visudo. Формат: user ALL=(ALL:ALL) ALL** — полный доступ\n- **%group ALL=(ALL) ALL** — группе. Ограниченные права: operator ALL=(root) `/usr/bin/systemctl` restart nginx — только одна команда\n- **operator ALL=(root) NOPASSWD: `/usr/bin/htop`** — без пароля. Alias-ы: User_Alias ADMINS = alice, bob\n- Cmnd_Alias BACKUP = `/usr/bin/rsync`, `/usr/local/bin/backup.sh`\n- **ADMINS ALL=(root) BACKUP. Безопасность**: Defaults timestamp_timeout=15\n- Defaults logfile="`/var/log/sudo.log`"\n- Defaults lecture=always\n- **Defaults rootpw. Аудит**: `/var/log/auth.log` (Debian) или `/var/log/secure` (RHEL) содержат записи.\n\n## Актуальность 2026\n\nВ 2026: sudo_logsrvd для централизованного логирования.',d:'intermediate',tags:['sudo','sudoers','привилегии','аудит']},
{c:'sysadmin',t:'Как управлять службами через systemd?',q:'Опишите создание кастомных юнит-файлов, drop-in переопределения и устранение неполадок.',a:'Структура service-юнита:\n\n[Unit] Description=My Service, After=network. target; [Service] Type=simple, ExecStart=`/usr/bin/app`, Restart=on-failure, RestartSec=5, User=app, Environment=NODE_ENV=production; [Install] WantedBy=multi-user.\ntarget.  Drop-in переопределения: systemctl edit SERVICE создаёт `/etc/systemd/system/SERVICE.`\nservice. d`/override.`\nconf.  Пример: [Service] MemoryMax=512M.\nУстранение: systemctl status SERVICE; journalctl -u SERVICE -n 50; systemctl daemon-reload; systemctl reset-failed.  Таймеры: [Timer] OnCalendar=hourly, Persistent=true.\nПреимущества перед cron: логирование, зависимости, RandomizedDelaySec.  Resource control: systemctl set-property SERVICE MemoryMax=1G CPUQuota=200%.',d:'intermediate',tags:['systemd','юниты','сервисы']},
{c:'sysadmin',t:'Как настроить backup-стратегию?',q:'Опишите типы бэкапов, инструменты и стратегию 3-2-1.',a:'Типы: Full — полная копия, просто восстановление, долго; Incremental — изменения с предыдущего бэкапа, быстро, сложно восстановление; Differential — с последнего полного, баланс.\n\n## Основные элементы\n\n- **Стратегия 3-2-1**: 3 копии, на 2 типах носителей, 1 вне площадки. Инструменты: rsync -avz --delete `/data/` backup-server:`/backup/data/` — инкрементальная\n- **restic backup /`data --repo s3:bucket`/repo``** — дедуплицированные зашифрованные\n- **Borg Backup** — эффективная дедупликация\n- **Bacula`/Bareos`** — корпоративные. Автоматизация: systemd timer или cron\n- проверка целостности (restic check, borg check)\n- **тест восстановления. Шифрование**: restic и Borg поддерживают на стороне клиента.\n\n## Актуальность 2026\n\nВ 2026: объектные хранилища (S3) как целевой бакенд; immutable backups от шифровальщиков; Velero для K8s.',d:'intermediate',tags:['бэкап','rsync','restic','стратегия']},
{c:'sysadmin',t:'Как управлять USB-устройствами и съёмными носителями?',q:'Опишите udev, правила для устройств, автомонтирование и безопасность USB.',a:'udev — менеджер устройств в Linux, создаёт файлы устройств в /dev/ динамически. Правила udev:\n\n## Основные элементы\n\n- **`/etc/udev/rules.d/`** — локальные\n- **`/lib/udev/rules.d/`** — от пакетов. Формат правила: ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="1234", ATTR{idProduct}=="5678", SYMLINK+="mydevice", MODE="0660", GROUP="storage". Команды: udevadm `info -a -n `/dev/sdb` — атрибуты устройства`\n- **udevadm `control --reload-rules`** — перезагрузить правила\n- **udevadm trigger** — применить. Автомонтирование через udisks2: автоматически монтирует USB в `/run/media/username/LABEL.` Или через autofs: `/etc/auto.master` — `/mnt/usb` `/etc/auto.usb` --timeout=30. Безопасность: запретить USB через udev: SUBSYSTEM=="usb", ATTR{authorized}=="0". Групповая политика: OPTIONS+="ignore_device".\n\n## Актуальность 2026\n\nВ 2026: USBGuard — whitelist USB-устройств через сертификаты.',d:'intermediate',tags:['udev','usb','автомонтирование','устройства']},
{c:'sysadmin',t:'Как работает PAM и зачем он нужен?',q:'Объясните архитектуру PAM, типичные модули и настройку политик аутентификации.',a:'PAM (Pluggable Authentication Modules) — архитектура подключаемых модулей аутентификации.\n\n## Основные элементы\n\n- **Позволяет настраивать политики входа без перекомпиляции. Конфигурация: `/etc/pam.d/`** — каталог с файлами для каждого сервиса. Формат: тип контроль модуль аргументы. Типы: auth — аутентификация\n- **account** — управление учётной записью\n- **password** — управление паролями\n- **session** — сессионные действия. Управление: required — модуль должен пройти\n- **requisite** — немедленный отказ\n- **sufficient** — прохождения достаточно\n- **optional** — игнорируется. Модули: pam_unix.so — стандартная проверка\n- **pam_tally2.so** — подсчёт неудачных попыток\n- **pam_pwquality.so** — политика сложности\n- **pam_google_authenticator.so** — 2FA TOTP\n- **pam_limits.so** — лимиты ресурсов. Пример: password requisite pam_pwquality.so try_first_pass retry=3 minlen=12 dcredit=-1 ucredit=-1.',d:'intermediate',tags:['pam','аутентификация','модули']},

// ================================================================
// КНИГА 3: LINUX SERVERS — настройка типичных серверов
// Web, DNS, DHCP, база данных, файловые серверы
// ================================================================
{c:'linux-servers',t:'Как настроить веб-сервер Nginx?',q:'Опишите базовую и продвинутую конфигурацию Nginx: виртуальные хосты, обратный прокси, SSL/TLS.',a:'Базовая конфигурация:\n\n## Основные элементы\n\n- **`/etc/nginx/nginx.conf`** — глобальные настройки\n- **`/etc/nginx/sites-available/` и sites-enabled/** — виртуальные хосты. Простой сервер: server { listen 80\n- server_name example.com\n- root `/var/www/html`\n- index index.html\n- location / { try_files $uri $uri/ =404\n- **} }. Обратный прокси**: location `/api/` { proxy_pass http:/`/backend`:3000/\n- proxy_set_header Host $host\n- proxy_set_header X-Real-IP $remote_addr\n- proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for\n- **}. SSL`/TLS` (2026)**: server { listen 443 ssl http2\n- ssl_certificate `/etc/letsencrypt/live/example.com/fullchain.pem`\n- ssl_certificate_key `/etc/letsencrypt/live/example.com/privkey.pem`\n- ssl_protocols TLSv1.3\n- **}. Оптимизация**: worker_processes auto\n- gzip on\n- client_max_body_size 50M\n- **proxy_cache_path. Let us Encrypt**: `certbot --nginx -d example.com.`',d:'intermediate',tags:['nginx','веб-сервер','прокси','ssl']},
{c:'linux-servers',t:'Как настроить Apache HTTP Server?',q:'Опишите конфигурацию Apache: виртуальные хосты, модули, .htaccess и сравнение с Nginx.',a:'Apache HTTP Server — один из старейших веб-серверов. Конфигурация:\n\n## Основные элементы\n\n- **`/etc/httpd/conf/httpd.conf` (RHEL) или `/etc/apache2/` (Debian). Виртуальные хосты**: `/etc/apache2/sites-available/example.com.conf` — VirtualHost *:80, ServerName example.com, DocumentRoot `/var/www/html`, ErrorLog, CustomLog. Модули: a2enmod rewrite — включить\n- **a2dismod autoindex** — отключить. Ключевые модули: mod_ssl, mod_rewrite, mod_proxy, mod_headers, mod_security. .htaccess: AllowOverride All в конфигурации\n- **правила перезаписи, авторизация, кэширование. Сравнение с Nginx: Apache** — process`/thread` per connection (mpm_prefork`/event`)\n- **Nginx** — event-driven, эффективнее при высокой нагрузке. Apache лучше для .htaccess, dynamic content через mod_php. Nginx лучше для статических файлов и проксирования. В 2026: Apache с mpm_event приближается к Nginx по производительности. Рекомендация: Nginx фронтенд + Apache бэкенд.',d:'intermediate',tags:['apache','веб-сервер','модули']},
{c:'linux-servers',t:'Как настроить DNS-сервер BIND?',q:'Опишите настройку авторитетного и кэширующего DNS-сервера, создание зон и управление записями.',a:'BIND — наиболее распространённый DNS-сервер. Конфигурация:\n\n`/etc/named.` conf (RHEL) или `/etc/bind/named.`\nconf (Debian).  Кэширующий: options { listen-on port 53 { any; }; allow-query { 192.\n168. 1.\n0/24; }; recursion yes; forwarders { 8. 8.\n8. 8; 1.\n1. 1.\n1; }; }.  Авторитетная зона: zone "example.\ncom" IN { type master; file "example. com.\nzone"; }.  Файл зоны: `$TTL` 86400, @ IN SOA ns1.\nexample. com.\nadmin. example.\ncom.  (2026010101 3600 900 604800 86400), @ IN NS ns1, @ IN A 192.\n168. 1.\n10, www IN CNAME @, mail IN A 192. 168.\n1. 20, @ IN MX 10 mail, @ IN TXT "v=spf1 mx -all".\nПроверка: named-checkconf; named-checkzone example. com zonefile; dig @localhost example.\ncom A.  Безопасность: DNSSEC (dnssec-keygen, dnssec-signzone), TSIG, rate limiting.\n\n## Альтернативы\n\nАльтернативы: Unbound (рекурсивный), PowerDNS (SQL-бэкенд), CoreDNS (Kubernetes).',d:'intermediate',tags:['dns','bind','зоны','сервер']},
{c:'linux-servers',t:'Как настроить кэширующий DNS Unbound?',q:'Опишите установку и конфигурацию Unbound как локального кэширующего DNS-резолвера.',a:'Unbound — валидирующий, рекурсивный, кэширующий DNS-резолвер. Преимущества:\n\nDNSSEC встроена, низкое потребление памяти, высокая производительность.  Установка: apt install unbound или dnf install unbound.\nКонфигурация `/etc/unbound/unbound.` conf: server: interface: 0.\n0. 0.\n0, access-control: 192. 168.\n1. 0/24 allow, num-threads: 2, cache-min-ttl: 300, cache-max-ttl: 86400, prefetch: yes.\nDNSSEC: auto-trust-anchor-file: "`/var/lib/unbound/root.` key".\nФорвардинг: forward-zone: name: ". ", forward-addr: 8.\n8. 8.\n8, forward-addr: 1. 1.\n1. 1.\nЛокальные записи: local-data: "myapp. home.\nIN A 192. 168.\n1. 50".\nПроверка: unbound-checkconf; dig @localhost example. com; unbound-control dump_cache.\n\n## Актуальность 2026\n\nВ 2026: DoH-форвардинг, aggressive NSEC для уменьшения запросов.',d:'intermediate',tags:['dns','unbound','кэширование']},
{c:'linux-servers',t:'Как настроить DHCP-сервер?',q:'Опишите настройку isc-dhcp-server, параметры аренды, резервирование адресов и устранение неполадок.',a:'DHCP автоматически назначает IP-адреса клиентам. Установка:\n\n## Основные элементы\n\n- **apt install isc-dhcp-server. Конфигурация `/etc/dhcp/dhcpd.conf`**: subnet 192.168.1.0 netmask 255.255.255.0 { range 192.168.1.100 192.168.1.200\n- option domain-name-servers 8.8.8.8, 1.1.1.1\n- option domain-name "example.com"\n- option routers 192.168.1.1\n- default-lease-time 600\n- max-lease-time 7200\n- **}. Резервирование**: host printer { hardware ethernet 00:11:22:33:44:55\n- fixed-address 192.168.1.50\n- **}. Запуск**: systemctl `enable --now isc-dhcp-server. Проверка: dhcp-lease-list`\n- **cat `/var/lib/dhcp/dhcpd.leases.` Диагностика**: tcpdump -i eth0 port 67 or port 68. Альтернатива: dnsmasq — DNS+DHCP для малых сетей. Kea — современный DHCP от ISC с REST API.',d:'beginner',tags:['dhcp','ip-адресация','сеть']},
{c:'linux-servers',t:'Как настроить PostgreSQL-сервер?',q:'Опишите установку, конфигурацию, управление пользователями, бэкап и репликацию PostgreSQL.',a:'Установка:\n\n## Основные элементы\n\n- **apt install postgresql. Управление**: `sudo -u postgres psql`\n- CREATE USER appuser WITH PASSWORD "secret"\n- **CREATE DATABASE appdb OWNER appuser. Конфигурация postgresql.conf**: listen_addresses = "*"\n- max_connections = 100\n- shared_buffers = 256MB\n- effective_cache_size = 1GB\n- **wal_level = replica. Аутентификация pg_hba.conf**: host appdb appuser 192.168.1.0/24 scram-sha-256. Бэкап: pg_dump appdb > backup.sql\n- pg_dumpall > full_backup.sql\n- **pg_basebackup -D `/backup` -Ft -z. Восстановление: psql appdb < backup.sql. Репликация: первичный** — wal_level=replica, max_wal_senders=3\n- **резервный** — primary_conninfo. В 2026: логическая репликация через PUBLICATION`/SUBSCRIPTION.` Мониторинг: pg_stat_activity, pg_stat_database, EXPLAIN ANALYZE.',d:'intermediate',tags:['postgresql','базы-данных','репликация']},
{c:'linux-servers',t:'Как настроить файловый сервер Samba?',q:'Опишите настройку Samba для совместного доступа между Linux и Windows.',a:'Samba реализует SMB/CIFS для совместного доступа. Установка:\n\n## Основные элементы\n\n- **apt install samba. Конфигурация `/etc/samba/smb.conf`**: [global] workgroup = WORKGROUP, security = user. Публичный ресурс: [public] path = `/srv/samba/public`, browseable = yes, writable = yes, guest ok = yes, create mask = 0664. Приватный: [shared] path = `/srv/samba/shared`, writable = yes, valid users = @smbgroup, create mask = 0660. Управление: `smbpasswd -a username`\n- **`pdbedit -L`. Запуск**: systemctl `enable --now smb nmb. Проверка: testparm`\n- **`smbclient -L localhost. Подключение: Windows`** — \\\\server\\shared\n- **Linux** — mount -t cifs /`/server/shared` `/mnt/smb` -o username=user,vers=3.0.\n\n## Актуальность 2026\n\nВ 2026: SMB3 с шифрованием (smb encrypt = required), интеграция с AD через winbind.',d:'intermediate',tags:['samba','smb','файловый-сервер']},
{c:'linux-servers',t:'Как настроить почтовый сервер Postfix + Dovecot?',q:'Опишите базовую настройку: Postfix для SMTP, Dovecot для IMAP, SSL/TLS, антиспам.',a:'Postfix (SMTP):\n\n`/etc/postfix/main.` cf: myhostname = mail.\nexample. com, mydomain = example.\ncom, mydestination = $myhostname, localhost, $mydomain, inet_interfaces = all, home_mailbox = Maildir/.  SSL`/TLS`: smtpd_tls_cert_file, smtpd_tls_key_file, smtpd_use_tls=yes.\nDovecot (IMAP): `/etc/dovecot/dovecot.` conf: protocols = imap pop3, mail_location = maildir:~`/Maildir`, ssl = required.\nАутентификация: disable_plaintext_auth = yes, auth_mechanisms = plain login.  Проверка: telnet mail.\nexample. com 25; openssl `s_client -connect mail.`\nexample. com:993.\nАнтиспам: SPF-запись в DNS; DKIM через OpenDKIM; DMARC-политика; SpamAssassin или Rspamd.\n\n## Актуальность 2026\n\nВ 2026: MTA-STS для принудительного TLS, DANE для DNSSEC-верификации.',d:'advanced',tags:['postfix','dovecot','почта','smtp']},
{c:'linux-servers',t:'Как настроить SSH-сервер и обезопасить его?',q:'Опишите конфигурацию sshd, ключи, 2FA и методы защиты.',a:'Конфигурация /etc/ssh/sshd_config:\n\nPort 22 (можно изменить); PermitRootLogin no; PasswordAuthentication no; PubkeyAuthentication yes; MaxAuthTries 3; AllowUsers admin@192. 168.\n1. *.\nГенерация ключей: ssh-keygen -t ed25519 (рекомендация 2026); ssh-copy-id user@server.  2FA: libpam-google-authenticator; AuthenticationMethods publickey,keyboard-interactive.\nPort Knocking: knockd слушает последовательность подключений.  Fail2Ban: [sshd] enabled = true, maxretry = 3, bantime = 3600.\n\n## Актуальность 2026\n\nВ 2026: SSH-сертификаты (ssh-ca), FIDO2-ключи (sk-ssh-ed25519), криптографические хардware-токены.',d:'intermediate',tags:['ssh','безопасность','аутентификация']},
{c:'linux-servers',t:'Как настроить NFS-сервер и клиента?',q:'Опишите настройку NFS-сервера, экспорт каталогов, монтирование на клиенте.',a:'Сервер:\n\n## Основные элементы\n\n- **apt install nfs-server. `/etc/exports`**: `/data` 192.168.1.0/24(rw,sync,no_subtree_check) *(ro,sync). Параметры: rw`/ro`\n- sync`/async`\n- **no_root_squash** — не менять root\n- **no_subtree_check. Запуск**: systemctl enable --now nfs-server. Применение: exportfs -arv. Проверка: exportfs -v\n- **`showmount -e localhost. Клиент`**: mount -t nfs -o vers=4,rw,hard,intr server:`/data` `/mnt/data.` `/etc/fstab`: server:`/data` `/mnt/data` nfs4 vers=4,rw,hard 0 0. NFSv4: единый корень экспорта, Kerberos (sec=krb5), idmapd, firewall только порт 2049. Диагностика: rpcinfo -p server\n- `nfsstat -s`\n- **`tcpdump -i eth0 port 2049. В 2026: NFSv4.2`** — server-side copy, sparse files.',d:'intermediate',tags:['nfs','файловый-сервер','экспорт']},
{c:'linux-servers',t:'Как настроить обратный прокси и балансировку в Nginx?',q:'Опишите upstream, алгоритмы балансировки, health checks и SSL-терминацию.',a:'Upstream: upstream backend { server 192.\n\n## Основные элементы\n\n- 168.1.10:8080\n- server 192.168.1.11:8080\n- server 192.168.1.12:8080 backup\n- **}. Алгоритмы**: round-robin (по умолчанию)\n- **least_conn** — наименьшее число соединений\n- **ip_hash** — привязка по IP клиента\n- **hash $request_uri consistent** — по URI. Health checks: passive — max_fails=3, fail_timeout=30s\n- **active (Plus)** — health_check interval=5s. SSL-терминация: server { listen 443 ssl\n- ssl_certificate `/path/cert.pem`\n- location / { proxy_pass http:/`/backend`\n- proxy_set_header X-Forwarded-Proto https\n- **} }. Rate limiting**: limit_req_zone $binary_remote_addr zone=api:10m rate=10r`/s.`\n\n## Актуальность 2026\n\nВ 2026: HTTP/3 (QUIC), gRPC-проксирование.',d:'intermediate',tags:['nginx','балансировка','прокси']},
{c:'linux-servers',t:'Как настроить MySQL-сервер?',q:'Опишите установку, конфигурацию, пользователей, бэкап и оптимизацию MySQL.',a:'Установка:\n\n## Основные элементы\n\n- **apt install mysql-server. Безопасность: mysql_secure_installation** — установить root-пароль, удалить анонимных, тестовую БД. Пользователи: CREATE USER "appuser"@"%" IDENTIFIED BY "secret"\n- CREATE DATABASE appdb\n- GRANT ALL PRIVILEGES ON appdb.* TO "appuser"@"%"\n- **FLUSH PRIVILEGES. Конфигурация `/etc/mysql/mysql.conf.d/mysqld.cnf`**: innodb_buffer_pool_size = 1G\n- max_connections = 200\n- innodb_log_file_size = 256M\n- slow_query_log = 1\n- **long_query_time = 2. Бэкап**: `mysqldump -u root -p appdb > backup.sql`\n- **`mysql -u root -p appdb < backup.sql. Репликация`**: CHANGE MASTER TO MASTER_HOST="primary", MASTER_USER="repl", MASTER_PASSWORD="pass"\n- **START SLAVE. Мониторинг**: SHOW PROCESSLIST\n- SHOW STATUS LIKE "Threads%"\n- EXPLAIN SELECT ...',d:'intermediate',tags:['mysql','базы-данных','репликация']},
{c:'linux-servers',t:'Как настроить LDAP-сервер OpenLDAP?',q:'Опишите установку и конфигурацию OpenLDAP для централизованного управления учётными записями.',a:'OpenLDAP — реализация LDAP-сервера для централизованной аутентификации. Установка:\n\n## Основные элементы\n\n- **apt install slapd ldap-utils. Начальная конфигурация: dpkg-reconfigure slapd** — домен, пароль администратора. Структура DIT: dc=example,dc=com — корень\n- **ou=People** — пользователи\n- **ou=Groups** — группы. Добавление записей: ldapadd -x -D "cn=admin,dc=example,dc=com" -W -f users.ldif. Формат LDIF: dn: uid=john,ou=People,dc=example,dc=com\n- **objectClass**: inetOrgPerson\n- **uid**: john\n- **sn**: Doe\n- **givenName**: John\n- **mail**: john@example.com\n- **userPassword**: {SSHA}hash. Клиентская настройка: apt install libnss-ldapd libpam-ldapd\n- **`/etc/nsswitch.conf`** — passwd, group, shadow: files ldap. Интеграция с SSH: в `/etc/pam.d/sshd` добавьте pam_ldap.so.\n\n## Актуальность 2026\n\nВ 2026: FreeIPA — комплексное решение с Web-UI, DNS, Kerberos, сертификатами поверх 389 Directory Server.',d:'advanced',tags:['ldap','openldap','аутентификация','централизация']},

// ================================================================
// КНИГА 4: LINUX STORAGE — управление дисками, разделами,
// RAID, LVM и технологиями хранения
// ================================================================
{c:'linux-storage',t:'Что такое MBR и GPT и в чём разница?',q:'Сравните таблицы разделов MBR и GPT, их ограничения и сценарии использования.',a:'MBR (Master Boot Record):\n\n## Основные элементы\n\n- максимум 4 первичных раздела (или 3 + 1 расширенный), максимальный размер раздела 2 ТБ, одна копия таблицы, нет избыточности. GPT (GUID Partition Table): до 128 разделов, размер до 9.4 ЗБ, уникальные GUID, основная и резервная копия, CRC32 контрольные суммы, protective MBR для совместимости. Инструменты: fdisk — для MBR и GPT\n- **gdisk** — специализированный для GPT\n- **parted** — универсальный. Примеры: parted `/dev/sda` mklabel gpt\n- parted `/dev/sda` mkpart primary ext4 1MiB 100GiB\n- **gdisk `/dev/sda`** — интерактивный. EFI System Partition (ESP): тип EF00, FAT32, `/boot/efi`, минимум 100 МБ. Рекомендация 2026: GPT для всех новых установок. UEFI + GPT — стандарт. MBR только для legacy-систем.',d:'beginner',tags:['mbr','gpt','разделы','диски']},
{c:'linux-storage',t:'Как создать и управлять разделами диска?',q:'Опишите использование fdisk, gdisk и parted для создания, удаления и изменения разделов.',a:'fdisk (MBR и GPT):\n\n## Основные элементы\n\n- **fdisk `/dev/sda`** — интерактивный. Команды: m — помощь\n- **p** — показать таблицу\n- **n** — новый раздел\n- **d** — удалить\n- **t** — изменить тип\n- **w** — записать\n- **q** — выйти. Пример: n (new), p (primary), 1 (number), Enter (default start), +50G (size), w (write). gdisk (GPT): аналогичный интерфейс, но для GPT. Типы разделов: EF00 — EFI System\n- **8300** — Linux filesystem\n- **8200** — Linux swap\n- **FD00** — Linux RAID. parted: parted `/dev/sda` mklabel gpt\n- parted `/dev/sda` mkpart primary ext4 1MiB 50GiB\n- parted `/dev/sda` rm 1\n- **parted `/dev/sda` print. Важное: после создания раздела** — partprobe `/dev/sda` или partx -a `/dev/sda` для обновления таблицы в ядре. Форматирование: mkfs.ext4 `/dev/sda1`\n- mkfs.xfs `/dev/sda1`\n- **mkswap `/dev/sda2.` Монтирование**: mount `/dev/sda1` `/mnt/data.`',d:'beginner',tags:['fdisk','gdisk','parted','разделы']},
{c:'linux-storage',t:'Объясните уровни RAID и их применение',q:'Опишите RAID 0, 1, 5, 6, 10: принцип работы, преимущества, недостатки.',a:'RAID 0 (Striping):\n\nданные чередуются по дискам, нет избыточности.  Плюс: максимальная скорость.\nМинус: потеря одного диска = потеря всех данных.  RAID 1 (Mirroring): зеркалирование на два диска.\nПлюс: отказоустойчивость при потере одного диска.  Минус: 50% эффективности.\nRAID 5 (Striping + parity): минимум 3 диска, выдерживает потерю одного.  Плюс: 67-94% эффективности.\nМинус: медленная запись, долгая перестройка.  RAID 6 (Double parity): минимум 4 диска, выдерживает потерю двух.\nRAID 10 (1+0): зеркала в stripe.  Плюс: скорость + отказоустойчивость.\nМинус: 50% эффективности.  Программный RAID: mdadm --create `/dev/md0` --level=5 --raid-devices=3 `/dev/sd`{b,c,d}.\nМониторинг: cat `/proc/mdstat`; `mdadm --detail `/dev/md0.``\n\n## Актуальность 2026\n\nВ 2026: mdadm остаётся стандартом программного RAID.',d:'intermediate',tags:['raid','массивы','отказоустойчивость']},
{c:'linux-storage',t:'Объясните LVM (Logical Volume Manager)',q:'Что такое LVM, его компоненты и как управлять логическими томами?',a:'LVM обеспечивает гибкое управление дисками через абстракцию. Компоненты:\n\n## Основные элементы\n\n- **PV (Physical Volume)** — реальный диск, pvcreate `/dev/sdb1`\n- **VG (Volume Group)** — пул PV, vgcreate vg0 `/dev/sdb1` `/dev/sdc1`\n- **LV (Logical Volume)** — логический раздел, lvcreate -L 50G -n data vg0. Операции: lvextend -L +10G `/dev/vg0/data` — расширение\n- **resize2fs `/dev/vg0/data`** — расширение ext4\n- **xfs_growfs `/mnt/data`** — расширение XFS\n- **`lvcreate -L 5G -s -n backup `/dev/vg0/data``** — снапшот\n- **`lvcreate -T vg0`/thinpool` -L 100G`** — тонкое провижинирование\n- **`lvcreate -V 50G -T vg0`/thinpool` -n thinvol. Преимущества`**: изменение размера на лету, снапшоты, тонкое провижинирование, распределение по дискам, миграция через pvmove.\n\n## Актуальность 2026\n\nВ 2026: интеграция со Stratis.',d:'intermediate',tags:['lvm','хранилище','файловые-системы']},
{c:'linux-storage',t:'Что такое ZFS и когда её использовать?',q:'Объясните архитектуру ZFS, её ключевые возможности и отличие от традиционных файловых систем.',a:'ZFS — файловая система и менеджер томов. Ключевые возможности:\n\n## Основные элементы\n\n- целостность данных через контрольные суммы каждого блока\n- Copy-on-Write\n- мгновенные снапшоты\n- встроенная компрессия (lz4, zstd)\n- дедупликация\n- встроенный RAID (raidz1/2/3)\n- кэш в RAM (ARC) и на SSD (L2ARC)\n- **синхронная запись на ZIL`/SLOG.` Пулы и датасеты**: zpool create tank `/dev/sda` `/dev/sdb`\n- zfs create tank`/data`\n- zfs set compression=lz4 tank`/data`\n- **zfs set mountpoint=`/data` tank`/data.` Снапшоты**: zfs snapshot tank`/data`@backup\n- **zfs send tank`/data`@backup | zfs recv backup`/data.` RAIDZ: raidz1** — как RAID 5\n- **raidz2** — как RAID 6\n- **raidz3** — тройная чётность. Когда использовать: NAS, бэкап-серверы, хранилища ВМ. Минимум 1 ГБ RAM на 1 ТБ хранилища для ARC.',d:'advanced',tags:['zfs','файловые-системы','хранилище']},
{c:'linux-storage',t:'Как настроить iSCSI-хранилище?',q:'Опишите настройку iSCSI target и initiator, аутентификацию и мультипатинг.',a:'iSCSI — протокол блочного доступа к хранилищу по IP. Target (сервер):\n\n## Основные элементы\n\n- **targetcli** — create backstores`/fileio` name=disk1 size=10G, create iscsi iqn.2026-01.com.example:storage, create lun0 `/backstores/fileio/disk1.` Initiator (клиент): `iscsiadm -m discovery -t st -p 192.168.1.10`\n- `iscsiadm -m node -T iqn... -p 192.168.1.10 --login`\n- **автоматическое**: iscsiadm -m node -T ... --op update -n node.startup -v automatic. Аутентификация CHAP: iscsiadm -m node -T ... --op update -n node.session.auth.authmethod -v CHAP. Multipath: multipath-tools, `/etc/multipath.conf.` Команды: multipath -ll\n- **`multipath -v2`. Производительность**: отдельная сеть для iSCSI (VLAN), jumbo frames (MTU 9000).',d:'advanced',tags:['iscsi','хранилище','блочный-доступ']},
{c:'linux-storage',t:'Как работает automount (autofs)?',q:'Объясните настройку autofs для автоматического монтирования по требованию.',a:'Autofs автоматически монтирует файловые системы при обращении и отмонтирует после таймаута. Установка:\n\napt install autofs.  Конфигурация: `/etc/auto.`\nmaster — точка_монтирования файл_карты --timeout=60.  Пример: `/mnt/nfs` `/etc/auto.`\nnfs --timeout=300.  Файл карты `/etc/auto.`\nnfs: `server1 -rw`,soft,intr nfs-server:`/export/data.`  Wildcard: * -rw server:`/export/`&.\nПрямые карты: /- `/etc/auto.` direct — `/mnt/``backup -rw backup-server:`/backup.``\nLDAP-карты: для централизованного управления.  Запуск: systemctl `enable --now autofs.`\nПроверка: `automount -m`.  Преимущества: экономия ресурсов, прозрачность, централизованное управление.\nНедостаток: задержка при первом обращении.  В 2026: systemd.\nautomount через x-systemd. automount в `/etc/fstab.`',d:'intermediate',tags:['autofs','автомонтирование','nfs']},
{c:'linux-storage',t:'Как настроить fstab и параметры монтирования?',q:'Объясните формат /etc/fstab, параметры монтирования и systemd.automount.',a:'/etc/fstab формат: устройство точка_монтирования тип параметры дамп проверка.\n\n## Основные элементы\n\n- **Примеры**: `/dev/vg0/data` `/data` ext4 defaults 0 2\n- UUID=xxx `/boot` ext4 defaults 1 2\n- `/dev/sda1` none swap sw 0 0\n- **tmpfs `/tmp` tmpfs defaults,size=4G 0 0. Параметры**: defaults (rw,suid,dev,exec,auto,nouser,async)\n- **noatime** — не обновлять время доступа\n- nodiratime\n- data=journal`/ordered/writeback` (ext4)\n- compress=zstd (btrfs)\n- **noexec** — без исполнения\n- **nosuid. systemd.automount**: x-systemd.automount,x-systemd.idle-timeout=600. Сетевые ФС: server:`/data` `/mnt/nfs` nfs4 _netdev,auto,x-systemd.automount 0 0. Безопасность: nosuid,nodev,noexec для съёмных и сетевых ФС. Диагностика: `mount -a`\n- findmnt\n- blkid.',d:'beginner',tags:['fstab','монтирование','автомонтирование']},
{c:'linux-storage',t:'Что такое Stratis и как он упрощает управление хранилищем?',q:'Объясните Stratis, его архитектуру и отличие от LVM.',a:'Stratis — менеджер локального хранилища от Red Hat, построен поверх LVM, xfs и device-mapper. Скрывает сложность:\n\n## Основные элементы\n\n- **вместо PV`/VG/LV`** — pool и filesystem. Снапшоты, тонкое провижинирование и мониторинг встроены. Создание: stratis pool create mypool `/dev/sdb` `/dev/sdc`\n- stratis filesystem create mypool myfs\n- **stratis filesystem snapshot mypool myfs mysnap. Монтирование**: `/dev/stratis/mypool/myfs` `/data` xfs defaults 0 0. Мониторинг: stratis pool list\n- stratis filesystem list\n- **stratis blockdev list. Автоматические функции**: тонкое провижинирование по умолчанию\n- автоматическое расширение при увеличении пула\n- **прозрачное шифрование через Clevis. Ограничения (2026)**: только xfs\n- нет дедупликации\n- нет встроенной компрессии\n- **только локальное хранилище. Рекомендация**: Stratis для упрощённого управления на RHEL\n- LVM`/ZFS` для тонкого контроля.',d:'intermediate',tags:['stratis','lvm','хранилище','rhel']},
{c:'linux-storage',t:'Как проверить и восстановить файловые системы?',q:'Опишите fsck, e2fsck, xfs_repair и стратегии восстановления данных.',a:'fsck — универсальный инструмент проверки. Для ext2/3/4:\n\n## Основные элементы\n\n- **`e2fsck -f -y `/dev/sda1``** — принудительная проверка с автоисправлением\n- **`e2fsck -p `/dev/sda1``** — автоматическое исправление безопасных проблем. Для XFS: xfs_repair `/dev/sda1` — проверка и восстановление (размонтировать сначала)\n- **`xfs_repair -n `/dev/sda1``** — только проверка без изменений. Важное: fsck нельзя запускать на примонтированной ФС! Исключение: ext4 с journal может восстанавливаться при загрузке. Автоматическая проверка: `tune2fs -c 30 `/dev/sda1` — каждые 30 монтирований`\n- **`tune2fs -i 30d `/dev/sda1``** — каждые 30 дней. Для Btrfs: btrfs scrub start `/mnt/data` — проверка чек-сумм\n- btrfs scrub status `/mnt/data`\n- **btrfs rescue** — восстановление. Восстановление данных: testdisk — восстановление разделов\n- **photorec** — восстановление файлов по сигнатурам.\n\n## Актуальность 2026\n\nВ 2026: e2fsck с поддержка metadata_csum_seed для быстрого изменения UUID.',d:'intermediate',tags:['fsck','восстановление','файловые-системы']},
{c:'linux-storage',t:'Как настроить программный RAID через mdadm?',q:'Опишите создание, управление, мониторинг и восстановление RAID-массивов mdadm.',a:'Создание RAID 1:\n\n## Основные элементы\n\n- **mdadm --create `/dev/md0` --level=1 --raid-devices=2 `/dev/sdb1` `/dev/sdc1.` RAID 5**: mdadm --create `/dev/md1` --level=5 --raid-devices=3 `/dev/sd`{d,e,f}1. Проверка: cat `/proc/mdstat` — статус\n- **`mdadm --detail `/dev/md0``** — подробности. Сохранение конфигурации: `mdadm --detail --scan >> `/etc/mdadm/mdadm.conf``\n- **`update-initramfs -u`. Мониторинг**: mdadm --monitor --mail=admin@example.com --delay=300 `/dev/md0.` Восстановление после сбоя: mdadm `/dev/md0` --add `/dev/sdb1` — добавить заменённый диск\n- **watch cat `/proc/mdstat`** — следить за перестройкой. Удаление: `mdadm --stop `/dev/md0``\n- **`mdadm --zero-superblock `/dev/sdb1.` Производительность`**: `mdadm --detail `/dev/md0` | grep UUID`\n- echo "MAILADDR admin@example.com" >> `/etc/mdadm/mdadm.conf.`\n\n## Актуальность 2026\n\nВ 2026: mdadm остаётся стандартом, интеграция с systemd для мониторинга.',d:'intermediate',tags:['raid','mdadm','массивы','восстановление']},

// ================================================================
// КНИГА 5: LINUX SECURITY — безопасность
// Права, ACL, SELinux, пользователи и пароли, файрволы, аудит
// ================================================================
{c:'linux-security',t:'Как работают файловые разрешения в Linux?',q:'Опишите модель разрешений Linux, включая традиционные права и специальные биты.',a:'Традиционные разрешения:\n\n## Этапы\n\n1. rwx для user`/group/other.` Чтение r=4, Запись w=2, Выполнение x=1. Пример: chmod 755 = rwxr-xr-x; chmod 640 = rw-r-----. Специальные биты: SUID (\n2. 4\n3. 0\n4. 0\n5. — выполнение от имени владельца файла, например `/usr/bin/passwd`; SGID (\n6. 2\n7. 0\n8. 0\n9. — выполнение от имени группы, новые файлы наследуют группу каталога; Sticky bit (\n10. 1\n11. 0\n12. 0\n13. — только владелец может удалять файлы в каталоге, например `/tmp.` Команды: chmod 4755 file — установить SUID; chmod 2755 dir — установить SGID; chmod 1777 `/tmp` — sticky bit. Символический формат: chmod u+s file; chmod g+s dir; chmod +t dir. umask определяет права по умолчанию для новых файлов: umask 022 — файлы 644, каталоги 755; umask 027 — файлы 640, каталоги 750. Проверка: stat file; `ls -la`.',d:'beginner',tags:['права','chmod','suid','sgid']},
{c:'linux-security',t:'Объясните ACL (Access Control Lists) в Linux',q:'Опишите расширенные списки контроля доступа, их настройку и применение.',a:'ACL расширяют традиционные разрешения rwx, позволяя задавать права конкретным пользователям и группам сверх стандартных owner/group/other. Просмотр:\n\n## Основные элементы\n\n- **getfacl file.txt** — показать все ACL-записи. Установка: `setfacl -m u:bob:rw file.txt — права пользователю bob`\n- **`setfacl -m g:devs:rx file.txt`** — права группе devs\n- **`setfacl -m u:bob:rx dir/`** — ACL на каталог. Default ACL (наследуются новыми файлами): setfacl -d -m u:bob:rw directory/. Удаление: setfacl -x u:bob file.txt — удалить запись\n- **`setfacl -b file.txt`** — удалить все ACL. Маска: setfacl -m m::r file.txt — ограничивает максимальные права для именованных пользователей и групп. ACL хранятся как расширенные атрибуты (user.posix_acl_access). При наличии ACL ls показывает символ "+" после прав: -rw-rw-r--+. Используйте ACL для сложных сценариев доступа, а для простых — традиционные разрешения плюс группы.',d:'intermediate',tags:['acl','права','setfacl','getfacl']},
{c:'linux-security',t:'Как харденинговать сервер Linux?',q:'Предоставьте полный чеклист для харденинга продакшн-сервера Linux.',a:'Уровень ОС:\n\nавтоматические обновления безопасности; удалите ненужные пакеты и сервисы; запретите root-вход по SSH; PermitRootLogin no, PasswordAuthentication no; файрвол nftables (2026).  Аутентификация: SSH-ключи ed25519; 2FA через google-authenticator-libpam; Fail2ban или CrowdSec; umask 027; PAM-модули для политик паролей.\nЯдро: kernel. randomize_va_space = 2 (ASLR); SELinux или AppArmor в enforcing; kernel.\nkptr_restrict = 1.  Сеть: закройте все входящие порты кроме необходимых; VPN для административного доступа; tcp_syncookies = 1.\nАудит и мониторинг: auditd для логирования системных вызовов; централизованное логирование; AIDE или Tripwire для проверки целостности; Lynis для автоматического аудита.\n\n## Актуальность 2026\n\nВ 2026: systemd-sysupdate; Secure Boot + TPM; Trivy`/Grype` для образов; постквантовая криптография для долгосрочных секретов.',d:'intermediate',tags:['харденинг','безопасность','linux']},
{c:'linux-security',t:'Объясните SELinux: режимы, контексты и булевы значения',q:'Что такое SELinux, как он работает, и как устранять проблемы с доступом?',a:'SELinux (Security-Enhanced Linux) — система обязательного контроля доступа (MAC), встроенная в ядро.\n\n## Основные элементы\n\n- **Каждый процесс и файл имеет контекст безопасности. Три режима: Enforcing** — политика применяется, нарушения блокируются\n- **Permissive** — нарушения логируются, но не блокируются\n- **Disabled** — отключён. Контексты: `ps -eZ — процессов`\n- **`ls -Z`** — файлов. Формат: user:role:type:level. Тип — основа решений о доступе: httpd_sys_content_t для веб-контента\n- **httpd_sys_rw_content_t для записи. Управление: setenforce 0/1** — переключение\n- **getenforce** — текущий режим\n- **fixfiles relabel** — перемаркировка. Булевы: `getsebool -a — все`\n- **`setsebool -P httpd_can_network_connect on`** — постоянное изменение. Устранение: `ausearch -m avc -ts recent — последние отказы`\n- **`audit2allow -w -a`** — объяснение\n- **`audit2allow -a -M mypolicy`** — генерация модуля\n- **`semodule -i mypolicy.pp`** — установка.',d:'advanced',tags:['selinux','mac','безопасность','контроль-доступа']},
{c:'linux-security',t:'Как работает AppArmor?',q:'Объясните архитектуру AppArmor, профили и сравнение с SELinux.',a:'AppArmor — система обязательного контроля доступа (MAC), альтернатива SELinux.\n\n## Основные элементы\n\n- Использует профили для ограничения доступа программ к файлам, сети, capabilities. Преимущества перед SELinux: проще в настройке\n- профили основаны на путях, а не на метках\n- легче создавать новые профили\n- **меньше overhead. Недостатки**: менее гранулярный контроль\n- **защита только по путям (символические ссылки могут быть проблемой). Профили: `/etc/apparmor.d/`** — каталог профилей\n- **aa-status** — список загруженных\n- **aa-enforce `/etc/apparmor.d/usr.sbin.nginx`** — включить\n- **aa-complain** — режим логирования без блокировки\n- **aa-disable** — отключить. Создание профиля: aa-genprof `/usr/bin/myapp` — интерактивное создание\n- **aa-logprof** — обновление на основе логов. Состояния: enforce — блокировка\n- **complain** — логирование\n- **disabled** — отключено. В 2026: AppArmor используется в Ubuntu, SUSE и snap-пакетах. SELinux — в RHEL`/Fedora.` Выбор зависит от дистрибутива.',d:'intermediate',tags:['apparmor','mac','профили','безопасность']},
{c:'linux-security',t:'Как настроить файрвол nftables?',q:'Опишите настройку nftables, замену iptables, базовые правила и схемы фильтрации.',a:'nftables — замена iptables, стандарт с ядра 3.13. Преимущества:\n\n## Основные элементы\n\n- унифицированный синтаксис для IPv4`/IPv6`\n- лучшая производительность\n- атомарные изменения\n- **поддержка наборов и словарей. Базовая конфигурация**: nft add table inet filter\n- nft add chain inet filter input { type filter hook input priority 0 \\\n- policy drop \\\n- }\n- nft add rule inet filter input iif lo accept\n- nft add rule inet filter input ct state established,related accept\n- **nft add rule inet filter input tcp dport { 22, 80, 443 } accept. NAT**: nft add table ip nat\n- nft add chain ip nat postrouting { type nat hook postrouting priority 100 \\\n- }\n- **nft add rule ip nat postrouting oifname eth0 masquerade. Сохранение**: nft list ruleset > `/etc/nftables.conf.` firewalld — обёртка над nftables: `firewall-cmd --permanent --add-service=http`\n- `firewall-cmd --reload`.\n\n## Актуальность 2026\n\nВ 2026 nftables полностью заменил iptables.',d:'intermediate',tags:['nftables','файрвол','iptables','сеть']},
{c:'linux-security',t:'Как настроить auditd для аудита системы?',q:'Опишите настройку auditd, правила аудита, поиск событий и интеграцию с SELinux.',a:'auditd — подсистема аудита Linux для отслеживания системных вызовов и доступа к файлам. Установка:\n\n## Основные элементы\n\n- **apt install auditd или dnf install audit. Конфигурация: `/etc/audit/auditd.conf`** — max_log_file = 50, num_logs = 5, max_log_file_action = ROTATE. Правила: `/etc/audit/rules.d/audit.rules.` Примеры: -w `/etc/``passwd -p wa -k identity — отслеживать изменения passwd`\n- -w `/etc/``sudoers -p wa -k sudo_config`\n- **-a always,`exit -F arch=b64 -S chmod,chown -F auid>=1000 -k perm_mod`** — изменения прав пользователями\n- **-a always,`exit -F arch=b64 -S execve -F auid>=1000 -k user_exec`** — выполнение команд. Поиск: `ausearch -k identity — по ключу`\n- **`ausearch -m avc`** — SELinux-отказы\n- **`ausearch -ua bob`** — действия пользователя\n- **`ausearch -ts today`** — за сегодня. Отчёты: aureport — сводный\n- **`aureport -x`** — по выполненным командам\n- **`aureport -f`** — по файлам.\n\n## Актуальность 2026\n\nВ 2026: интеграция с SIEM для централизованного анализа.',d:'intermediate',tags:['auditd','аудит','мониторинг','безопасность']},
{c:'linux-security',t:'Как обнаружить и предотвратить руткиты?',q:'Опишите методы обнаружения руткитов, инструменты и профилактику.',a:'Руткит — вредоносная программа, скрывающая своё присутствие.\n\n## Основные элементы\n\n- Бывает пользовательского уровня (заменяет ps, ls, netstat) и уровня ядра (загружает модуль). Инструменты: rkhunter --check — сканирование, сравнение хешей, проверка скрытых процессов\n- **chkrootkit** — аналогичный с другими сигнатурами. AIDE (Advanced Intrusion Detection Environment): aideinit — инициализация\n- **`aide --check`** — проверка\n- **`aide --update`** — обновление базы. Профилактика: Secure Boot предотвращает загрузку неподписанных модулей\n- включите IMA`/EVM` верификацию\n- SELinux`/AppArmor` в enforcing\n- **ограничьте загрузку модулей**: echo 1 > `/proc/sys/kernel/modules_disabled`\n- регулярные обновления\n- мониторинг изменений в `/etc`, `/usr.`\n\n## Актуальность 2026\n\nВ 2026: eBPF-мониторинг для обнаружения аномалий в реальном времени; интеграция с SIEM.',d:'advanced',tags:['руткиты','aide','обнаружение','безопасность']},
{c:'linux-security',t:'Как настроить политику паролей в Linux?',q:'Опишите настройку сложности паролей через PAM, срок действия и историю паролей.',a:'Настройка через PAM-модуль pam_pwquality (замена pam_cracklib). Конфигурация:\n\n## Основные элементы\n\n- **`/etc/security/pwquality.conf` или `/etc/pam.d/system-auth.` Параметры: minlen = 12** — минимальная длина\n- **dcredit = -1** — минимум 1 цифра\n- **ucredit = -1** — минимум 1 заглавная\n- **lcredit = -1** — минимум 1 строчная\n- **ocredit = -1** — минимум 1 спецсимвол\n- **maxrepeat = 3** — максимум повторов\n- **difok = 5** — минимум отличных символов от старого\n- **enforce_for_root** — применять к root. Срок действия: `chage -M 90 username — пароль истекает через 90 дней`\n- **`chage -m 7`** — минимум дней между сменами\n- **`chage -W 14`** — предупреждение за 14 дней\n- **`chage -l username`** — информация. История паролей: pam_pwhistory — remember=12 в `/etc/pam.d/system-auth`\n- **`/etc/security/opasswd`** — файл истории. Блокировка: pam_faillock — deny=5 unlock_time=900 — блокировка после 5 неудачных попыток на 15 минут.\n\n## Актуальность 2026\n\nВ 2026: yescrypt как стандартный хеш (замена SHA-512).',d:'intermediate',tags:['пароли','pam','политика','безопасность']},
{c:'linux-security',t:'Как работает шифрование дисков в Linux?',q:'Опишите LUKS, шифрование разделов, ключи и восстановление.',a:'LUKS (Linux Unified Key Setup) — стандарт шифрования дисков в Linux. Создание:\n\n## Основные элементы\n\n- **cryptsetup luksFormat `/dev/sdb1`** — инициализация (внимание: уничтожает данные!)\n- **cryptsetup luksOpen `/dev/sdb1` encrypted** — открыть\n- **mkfs.ext4 `/dev/mapper/encrypted`** — форматировать\n- **mount `/dev/mapper/encrypted` `/mnt/secure`** — монтировать. Управление ключами: cryptsetup luksAddKey `/dev/sdb1` — добавить ключ\n- **cryptsetup luksRemoveKey `/dev/sdb1`** — удалить\n- **cryptsetup luksDump `/dev/sdb1`** — информация\n- **максимум 8 слотов ключей. Автомонтирование: `/etc/crypttab`** — encrypted `/dev/sdb1` none luks\n- **`/etc/fstab`** — `/dev/mapper/encrypted` `/mnt/secure` ext4 defaults 0 2. Шифрование корневой файловой системы: при установке дистрибутива выберите LUKS\n- **ключ хранится в initramfs или вводится при загрузке. Clevis и Tang**: автоматическая расшифровка через NBDE (Network-Bound Disk Encryption). В 2026: LUKS2 с Argon2id (замена PBKDF2), поддержка HW-OPAL, интеграция с TPM 2.0.',d:'advanced',tags:['luks','шифрование','диск','безопасность']},
{c:'linux-security',t:'Как настроить Fail2ban для защиты от брутфорса?',q:'Опишите установку, конфигурацию, кастомные фильтры и интеграцию с файрволом.',a:'Fail2ban — инструмент для автоматической блокировки IP-адресов после неудачных попыток входа. Установка:\n\n## Основные элементы\n\n- **apt install fail2ban. Конфигурация**: `/etc/fail2ban/jail.local` (не редактируйте jail.conf!). Базовая настройка: [DEFAULT] bantime = 3600, findtime = 600, maxretry = 3, banaction = nftables-multiport. SSH: [sshd] enabled = true, port = ssh, filter = sshd, logpath = `/var/log/auth.log.` Кастомный фильтр: `/etc/fail2ban/filter.d/myapp.conf` — [Definition] failregex = ^.*Authentication failure.*from <HOST>.*$, ignoreregex =. Мониторинг: fail2ban-client status — список jail\n- **fail2ban-client status sshd** — статистика SSH\n- **fail2ban-client set sshd unbanip 1.2.3.4** — разбанить. Интеграция с nftables: banaction = nftables-multiport.\n\n## Актуальность 2026\n\nВ 2026: CrowdSec — современная альтернатива с collaborative intelligence, блокировка на основе репутации IP в реальном времени.',d:'intermediate',tags:['fail2ban','брутфорс','защита','файрвол']},
{c:'linux-security',t:'Объясните рукопожатие TLS 1.3 и сертификаты',q:'Опишите процесс рукопожатия TLS 1.3 и проверку цепочки сертификатов.',a:'Рукопожатие TLS 1.3 (1-RTT):\n\n## Этапы\n\n1. **ClientHello** — версии, шифронаборы, key share;\n2. **ServerHello** — выбранная версия/шифр, сертификат, CertificateVerify, Finished;\n3. Клиент проверяет цепочку, отправляет Finished;\n4. Данные приложения идут немедленно. Валидация цепочки: разобрать сертификат, извлечь издателя; найти сертификат издателя; проверить подпись публичным ключом издателя; повторить вверх: leaf, intermediate, root; root должен быть в `/etc/ssl/certs/`; проверки: не истёк, не отозван (CRL`/OCSP`), имя хоста совпадает с SAN`/CN.` Улучшения TLS 1.3: удалены RSA key exchange, CBC, MD5; 0-RTT для возобновлённых сессий; forward secrecy обязателен; зашифрованы ServerHello и сертификат. Диагностика: openssl `s_client -connect example.com:443 -servername example.com.`',d:'advanced',tags:['tls','ssl','сертификаты','шифрование']},
{c:'linux-security',t:'Как защитить SSH-сервер?',q:'Опишите лучшие практики безопасности SSH: ключи, конфигурация, 2FA, аудит.',a:'Конфигурация /etc/ssh/sshd_config:\n\nPort 2222 (нестандартный порт); PermitRootLogin no; PasswordAuthentication no; PubkeyAuthentication yes; MaxAuthTries 3; LoginGraceTime 30; AllowUsers admin@192. 168.\n1. *.\nКлючи: ssh-keygen -t ed25519 -C "comment" (рекомендация 2026); ssh-copy-id -i ~/. ssh`/id_ed25519.`\npub user@server.  2FA: apt install libpam-google-authenticator; в sshd_config: AuthenticationMethods publickey,keyboard-interactive; настройка PAM в `/etc/pam.`\nd`/sshd.`  Аудит: логирование в `/var/log/auth.`\nlog; анализ через ausearch; мониторинг через fail2ban.  Ограничение доступа: AllowUsers, AllowGroups, Match User admin Address 192.\n168. 1.\n0/24.  Jump host: ProxyJump в ~/.\nssh`/config.`\n\n## Актуальность 2026\n\nВ 2026: SSH-сертификаты (ssh-ca) вместо trust-on-first-use; FIDO2-ключи; криптографические hardware-токены.',d:'intermediate',tags:['ssh','безопасность','аутентификация']},

// ================================================================
// ДОПОЛНИТЕЛЬНЫЕ ТЕМЫ (Сети, Bash, Docker, K8s, Terraform, etc.)
// ================================================================
{c:'networking',t:'Объясните троекратное рукопожатие TCP',q:'Опишите процесс установки и разрыва TCP-соединения.',a:'Установка:\n\n## Этапы\n\n1. Клиент отправляет SYN (seq=x);\n2. Сервер отвечает SYN-ACK (seq=y, ack=x+1);\n3. Клиент отправляет ACK (ack=y+1), соединение ESTABLISHED. Закрытие:\n4. Активная сторона FIN;\n5. Пассивная ACK (FIN_WAIT_2, CLOSE_WAIT);\n6. Пассивная FIN (LAST_ACK);\n7. Активная ACK + TIME_WAIT (2*MSL). TIME_WAIT обеспечивает достижение последнего ACK и устаревание пакетов. Диагностика: `ss -tanp`; `tcpdump -i eth0.`\n\n## Актуальность 2026\n\nВ 2026: TCP-AO заменяет TCP-MD5 для BGP; TCP Fast Open уменьшает задержку.',d:'beginner',tags:['tcp','рукопожатие','протоколы']},
{c:'networking',t:'Как работает DNS-разрешение?',q:'Опишите полный процесс DNS-разрешения от приложения до авторитетного сервера.',a:'Процесс:\n\n## Этапы\n\n1. Приложение вызывает getaddrinfo();\n2. Stub resolver проверяет `/etc/hosts`, затем `/etc/resolv.conf`;\n3. Рекурсивный resolver проверяет кэш;\n4. Корневой сервер возвращает NS для TLD;\n5. TLD-сервер возвращает NS для авторитетного;\n6. Авторитетный возвращает ответ;\n7. Рекурсивный кэширует с TTL. Типы записей: A`/AAAA`, CNAME, MX, NS, TXT (SPF, DKIM, DMARC), SRV, SOA. Диагностика: dig example.com A +trace; nslookup example.com.\n\n## Актуальность 2026\n\nВ 2026: DNS-over-HTTPS (DoH) и DNS-over-TLS (DoT); DNSSEC; Encrypted Client Hello (ECH) скрывает SNI.',d:'intermediate',tags:['dns','разрешение','протоколы']},
{c:'networking',t:'Объясните BGP и его роль в интернет-маршрутизации',q:'Что такое Border Gateway Protocol и почему он критически важен?',a:'BGP — протокол векторного пути, соединяющий автономные системы (AS). eBGP — между разными AS; iBGP — внутри одной AS. Атрибуты пути:\n\n## Основные элементы\n\n- **AS-PATH, NEXT-HOP, LOCAL-PREF, MED, COMMUNITY. Выбор маршрута**: наивысший LOCAL-PREF, кратчайший AS-PATH, наименьший MED, eBGP предпочтительнее iBGP. BGP переносит более 1 млн маршрутов\n- **одна ошибка** — утечки маршрутов или чёрные дыры. Безопасность: RPKI проверяет происхождение\n- BGPsec валидирует путь.\n\n## Актуальность 2026\n\nВ 2026: ASPA (AS Provider Authorization) — защита от утечек маршрутов.',d:'advanced',tags:['bgp','маршрутизация','интернет']},
{c:'bash',t:'Расширение переменных и подстановка параметров',q:'Опишите типы расширения параметров в Bash с примерами.',a:'Базовое:\n\n## Основные элементы\n\n- `$VAR`\n- **`${VAR`:-default}** — по умолчанию\n- **`${VAR`:=default}** — присвоить\n- **`${VAR`:+alternate}** — альтернативное\n- **`${VAR`:?error}** — ошибка. Строки: ${#VAR} — длина\n- **`${VAR`%pattern}** — удалить кратчайший суффикс\n- **`${VAR`%%pattern}** — длиннейший\n- **`${VAR`#pattern}** — кратчайший префикс\n- **`${VAR`##pattern}** — длиннейший\n- **`${VAR``/old/new`}** — заменить первое\n- **`${VAR`/`/old/new`}** — все. Пример: FILE="archive.tar.gz"\n- `${FILE`##*.} = gz\n- **`${FILE`%.*} = archive.tar. Bash 5.2+: ${var@U}** — верхний регистр\n- **${var@L}** — нижний\n- **${var@Q}** — экранирование.',d:'intermediate',tags:['bash','переменные','расширение']},
{c:'bash',t:'Как эффективно обрабатывать текстовые файлы?',q:'Опишите ключевые инструменты обработки текста с примерами.',a:'grep: grep -r "pattern" /path; grep -i "pattern" file; grep -E "regex" file; grep -v "pattern".\n\nsed: sed -n "10,20p" file; sed "s`/old/new/g`" file; sed -i. bak "s`/old/new/g`" file.\nawk: awk "{print $1, $3}" file; awk -F: "{print $1}" `/etc/passwd`; awk "$3 > 100 {print}" file.  sort`/uniq`: sort file | `uniq -c | sort -rn.`\n\n## Альтернативы\n\nАльтернативы 2026: ripgrep (rg) — быстрее grep; fd — замена find; jq`/yq` — JSON`/YAML`; mlr (Miller) — CSV`/TSV.`',d:'beginner',tags:['bash','обработка-текста','grep','awk','sed']},
{c:'bash',t:'Напишите надёжный шаблон Bash-скрипта',q:'Создайте шаблон Bash-скрипта продакшн-качества.',a:'Начните:\n\n#! `/usr/bin/env` bash; `set -euo pipefail; IFS=$"\\\n\\	".`\nКонстанты: readonly SCRIPT_NAME="$(basename "$0")"; readonly LOG_FILE="`/var/log/``${SCRIPT_NAME}`. log".\nЛогирование: log() { echo "[$(date +"%Y-%m-%d %H:%M:%S")] [$1] $2" | `tee -a "`$LOG_FILE`"; }.`  Очистка: cleanup() { `rm -f "`$TEMP_FILE`"; exit $?`\n; }; trap cleanup EXIT.  Парсинг: while [[ $# -gt 0 ]]; do case $1 in -v|--verbose) VERBOSE=true; shift ;; -h|--help) usage ;; *) INPUT="$1"; shift ;; esac; done.\nПрактики: set -euo pipefail; trap для очистки; логирование; readonly для констант.\n\n## Актуальность 2026\n\nВ 2026: shellcheck для анализа; shfmt для форматирования.',d:'intermediate',tags:['bash','скриптинг','лучшие-практики']},
{c:'docker',t:'Как написать оптимальный Dockerfile?',q:'Опишите лучшие практики: многоступенчатая сборка, минимизация слоёв, безопасность.',a:'Многоступенчатая:\n\nFROM node:20 AS builder; COPY . ; RUN npm ci && npm run build; FROM node:20-slim; COPY --from=builder `/app/dist` .\n`/dist.`  Минимизация: RUN apt-get update && apt-get `install -y pkg && rm -rf `/var/lib/apt/lists/`*.`\nБезопасность: USER 1000; COPY --chown=1000:1000; --secret для секретов; . dockerignore.\nОптимизация кэша: COPY package*. json; RUN npm ci; COPY .\n.  Базовые образы: alpine (5 МБ, musl); slim (glibc); distroless (без оболочки).\n\n## Актуальность 2026\n\nВ 2026: BuildKit — стандарт; --mount=type=cache; --mount=type=secret.',d:'intermediate',tags:['docker','dockerfile','оптимизация']},
{c:'docker',t:'Как настроить Docker Compose?',q:'Опишите структуру docker-compose.yml, сети, volumes, переменные.',a:'Структура:\n\nservices: web: build: . , ports: ["8080:80"], depends_on: [db], environment: DB_HOST: db; db: image: postgres:16, environment: POSTGRES_PASSWORD: secret, volumes: [db-data:`/var/lib/postgresql/data`].\nСети: networks: frontend:, backend:.  Volumes: именованные (db-data:), bind-mount (.\n`/src`:`/app/src`), tmpfs.  Переменные: .\nenv файл; environment в compose; env_file: . env.\nHealthcheck: healthcheck: test: ["CMD", "curl", "-f", "http:/`/localhost`"], interval: 30s.  Ресурсы: deploy: resources: limits: cpus: "0.\n5", memory: 512M.\n\n## Актуальность 2026\n\nВ 2026: docker compose V2 (Go); profiles; watch для автоперезагрузки.',d:'intermediate',tags:['docker','compose','оркестрация']},
{c:'kubernetes',t:'Объясните архитектуру Kubernetes',q:'Опишите компоненты control plane, worker node и поток запросов.',a:'Control Plane:\n\n## Основные элементы\n\n- **kube-apiserver** — REST API\n- **etcd** — хранилище состояния\n- **kube-scheduler** — назначение подов\n- **kube-controller-manager** — контроллеры\n- **cloud-controller-manager** — облако. Worker Node: kubelet — агент\n- **kube-proxy** — сетевой прокси\n- **containerd** — runtime. Поток: kubectl → apiserver (RBAC, admission) → etcd → scheduler → kubelet → container runtime → kube-proxy. В 2026: K8s 1.31+ с Gateway API, структурная авторизация, улучшенный HPA.',d:'intermediate',tags:['kubernetes','архитектура','control-plane']},
{c:'kubernetes',t:'Что такое Gateway API?',q:'Объясните Gateway API как замену Ingress, его ресурсы и преимущества.',a:'Gateway API — замена Ingress. Роли:\n\n## Основные элементы\n\n- **Cluster Admin** — GatewayClass, Gateway\n- **Operator** — Gateway\n- **Developer** — HTTPRoute. Ресурсы: GatewayClass — контроллер\n- **Gateway** — инфраструктура\n- **HTTPRoute** — маршрутизация\n- **TCPRoute, GRPCRoute. Преимущества**: ролевая модель, кросс-неймспейс, TCP`/UDP/gRPC`, traffic splitting, заголовки. Реализации: Istio, Contour, Envoy Gateway, Traefik.\n\n## Актуальность 2026\n\nВ 2026: GA для HTTPRoute.',d:'advanced',tags:['kubernetes','gateway-api','ingress']},
{c:'terraform',t:'Как работает Terraform и управление состоянием?',q:'Объясните HCL, провайдеры, ресурсы, state file и лучшие практики.',a:'Terraform — Infrastructure as Code. HCL описывает желаемое состояние. Провайдеры:\n\nprovider "aws" { region = "us-east-1" }.  Ресурсы: resource "aws_instance" "web" { ami = "ami-xxx", instance_type = "t3.\nmicro" }.  State file: отображает ресурсы между конфигурацией и облаком.\nRemote state: S3 + DynamoDB, Blob Storage, GCS, Terraform Cloud.  Лучшие практики: удалённый state с блокировкой; не редактируйте вручную; workspaces для сред; модули; plan перед apply.\n\n## Актуальность 2026\n\nВ 2026: OpenTofu — open-source форк.',d:'intermediate',tags:['terraform','iac','state','hcl']},
{c:'ansible',t:'Как работает Ansible и как написать плейбук?',q:'Объясните архитектуру, инвентарь, модули и структуру плейбука.',a:'Ansible — агентless через SSH. Инвентарь:\n\n`/etc/ansible/hosts`; [webservers] web1 ansible_host=192. 168.\n1. 10.\nМодули: apt`/yum`, copy`/template`, service, user, command`/shell.`  Плейбук: ---, hosts: webservers, become: yes, tasks: - name: Install Nginx, apt: name=nginx state=present.\nHandlers: handlers: - name: reload nginx, service: name=nginx state=reloaded.  Роли: tasks/, handlers/, templates/, files/, vars/, defaults/, meta/.\n\n## Актуальность 2026\n\nВ 2026: Ansible Navigator, AWX`/Tower`, Execution Environments.',d:'intermediate',tags:['ansible','плейбуки','автоматизация']},
{c:'devops',t:'Что такое CI/CD и как его реализовать?',q:'Объясните принципы Continuous Integration и Continuous Delivery.',a:'CI: частые коммиты, автоматическая сборка и тестирование.\n\n## Основные элементы\n\n- **CD (Delivery)**: автоматическая подготовка релиза, ручное подтверждение. CD (Deployment): полностью автоматический деплой. Инструменты: GitHub Actions — .github`/workflows/ci.yml`\n- **GitLab CI** — .gitlab-ci.yml\n- Jenkins\n- **ArgoCD** — GitOps для K8s. Практики: feature flags\n- canary deployments\n- blue-green\n- smoke tests\n- автоматический откат.\n\n## Актуальность 2026\n\nВ 2026: GitOps (ArgoCD, Flux) — стандарт; AI-powered test selection.',d:'intermediate',tags:['ci-cd','devops','pipeline']},
{c:'monitoring',t:'Как настроить Prometheus и Grafana?',q:'Опишите архитектуру Prometheus, типы метрик, PromQL и интеграцию с Grafana.',a:'Prometheus: pull-модель, метрики в text формате, TSDB, PromQL.\n\nТипы: Counter (растёт), Gauge (текущее), Histogram (распределение), Summary (квантили).  PromQL: rate(http_requests_total[5m]); histogram_quantile(0.\n95, rate(request_duration_bucket[5m])); sum(rate(http_requests_total[5m])) by (method).  Alertmanager: alert: HighErrorRate, expr: rate(http_requests_total{status=~"5..\n"}[5m]) / rate(http_requests_total[5m]) > 0. 1.\nGrafana: data source Prometheus; дашборды; переменные; алерты.\n\n## Актуальность 2026\n\nВ 2026: Grafana Mimir (масштабируемый Prometheus), Loki (логи), Tempo (трейсы).',d:'intermediate',tags:['prometheus','grafana','мониторинг','метрики']},
{c:'databases',t:'Как оптимизировать производительность PostgreSQL?',q:'Опишите методы оптимизации запросов, индексы и конфигурацию.',a:'Анализ:\n\n## Основные элементы\n\n- **EXPLAIN ANALYZE SELECT ... Внимание на Seq Scan, Nested Loop, Sort. Индексы**: B-tree (=, <, >, BETWEEN)\n- GIN (JSONB, массивы, полнотекстовый)\n- GiST (геометрия)\n- BRIN (огромные таблицы)\n- **CREATE INDEX CONCURRENTLY** — без блокировки. Конфигурация: shared_buffers = 25% RAM\n- effective_cache_size = 75% RAM\n- **work_mem = RAM / (max_connections * 3). Мониторинг**: pg_stat_activity\n- pg_stat_database\n- **pg_stat_user_indexes. Массовая загрузка**: отключите индексы\n- COPY вместо INSERT\n- увеличьте maintenance_work_mem.',d:'intermediate',tags:['postgresql','оптимизация','индексы']},
{c:'web-servers',t:'Как настроить балансировку нагрузки в Nginx?',q:'Опишите upstream, алгоритмы, health checks и сессии.',a:'Upstream: upstream backend { server 10.\n\n## Основные элементы\n\n- 0.0.1:8080\n- server 10.0.0.2:8080\n- **}. Алгоритмы**: round-robin\n- least_conn\n- ip_hash\n- **hash $request_uri consistent. Health checks: passive** — max_fails=3, fail_timeout=30s\n- **active (Plus)** — health_check. SSL-терминация: listen 443 ssl\n- **proxy_set_header X-Forwarded-Proto https. Rate limiting**: limit_req_zone $binary_remote_addr zone=api:10m rate=10r`/s.`\n\n## Актуальность 2026\n\nВ 2026: HTTP/3 (QUIC); gRPC-проксирование.',d:'intermediate',tags:['nginx','балансировка','прокси']},
{c:'aws',t:'Объясните VPC и сетевую архитектуру AWS',q:'Опишите VPC, подсети, Internet Gateway, NAT Gateway и Security Groups.',a:'VPC — изолированная облачная сеть (CIDR /16-/28). Публичные подсети:\n\nInternet Gateway в маршрутной таблице.  Приватные: NAT Gateway для исходящего.\nSecurity Groups: stateful, разрешающие правила, мгновенные изменения.  NACL: stateless на уровне подсети, разрешающие и запрещающие.\nVPC Peering: без транзитивности.  Transit Gateway: хаб для VPC и VPN.\n\n## Актуальность 2026\n\nВ 2026: VPC Lattice для маршрутизации между сервисами.',d:'intermediate',tags:['aws','vpc','сеть']},
{c:'ebpf',t:'Что такое eBPF и зачем он нужен?',q:'Объясните архитектуру eBPF и области применения.',a:'eBPF — запуск песочничных программ в ядре без модулей. Применение:\n\n## Основные элементы\n\n- наблюдаемость (трассировка)\n- сеть (XDP, Cilium)\n- **безопасность (мониторинг вызовов). Преимущества**: производительность (в ядре)\n- безопасность (верификатор)\n- **гибкость (без перезагрузки). Инструменты: bpftrace** — однострочники\n- **BCC** — библиотека\n- **libbpf** — C\n- **CO-RE** — переносимость.\n\n## Актуальность 2026\n\nВ 2026: Cilium (K8s), Pixie (трассировка), Tetragon (безопасность).',d:'intermediate',tags:['ebpf','наблюдаемость','ядро']},
{c:'cloud-security',t:'Что такое IAM и принцип наименьших привилегий?',q:'Объясните модели IAM в AWS/Azure/GCP.',a:'AWS IAM:\n\nполитики, роли, SCP.  Azure RBAC: встроенные и кастомные роли, Managed Identity.\nGCP IAM: принципалы, роли, Workload Identity.  Принцип наименьших привилегий: только необходимый минимум; конкретные действия вместо s3:*; условия (IPAddress, MFAAuthenticated).\nИнструменты: AWS Access Analyzer; Azure PIM; GCP Policy Intelligence.\n\n## Актуальность 2026\n\nВ 2026: Just-In-Time доступ; временные привилегии; AI-анализ политик.',d:'intermediate',tags:['iam','наименьшие-привилегии','облако']},
]

async function main() {
  console.log('Seeding database...')

  // Демо-пользователь — нужен, чтобы /api/progress мог сохранять и отдавать прогресс.
  // Без него endpoints прогресса возвращают пустой ответ.
  await prisma.user.upsert({
    where: { email: 'demo@sysadmin.academy' },
    update: { name: 'Демо' },
    create: {
      email: 'demo@sysadmin.academy',
      name: 'Демо',
      level: 'Beginner',
      xp: 0,
      role: 'user',
    },
  })
  console.log('Created demo user')

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, description: cat.description, icon: cat.icon, order: cat.order },
      create: cat,
    })
  }
  console.log(`Created ${categories.length} categories`)

  let created = 0
  for (const q of questions) {
    const category = await prisma.category.findUnique({ where: { slug: q.c } })
    if (!category) { console.error(`Category not found: ${q.c}`); continue }

    const slug = q.t.toLowerCase().replace(/[^a-zа-яё0-9\s-]/g, '').replace(/\s+/g, '-').slice(0, 100)

    const question = await prisma.question.upsert({
      where: { slug },
      update: { title: q.t, content: q.q, answer: q.a, difficulty: q.d, categoryId: category.id },
      create: {
        title: q.t, slug, content: q.q, answer: q.a, difficulty: q.d,
        source: 'academy', categoryId: category.id,
      },
    })

    for (const tagName of q.tags) {
      const tagSlug = tagName.toLowerCase().replace(/\s+/g, '-')
      const tag = await prisma.tag.upsert({
        where: { slug: tagSlug },
        update: { name: tagName },
        create: { name: tagName, slug: tagSlug },
      })
      await prisma.questionTag.upsert({
        where: { questionId_tagId: { questionId: question.id, tagId: tag.id } },
        update: {},
        create: { questionId: question.id, tagId: tag.id },
      })
    }

    await prisma.aiExplanation.upsert({
      where: { questionId: question.id },
      update: {},
      create: {
        questionId: question.id,
        // Объяснения оформлены в Markdown — фронтенд рендерит их через
        // компонент MarkdownContent с разделением на блоки (заголовки, списки, код).
        // Структура: краткое введение + ключевые пункты + практический совет.
        beginnerExplanation: `## Простыми словами

${q.t} — это базовая концепция, которую нужно понимать «на пальцах».

## Ключевые идеи

- Сосредоточьтесь на базовых принципах, прежде чем углубляться в детали
- Попробуйте применить концепцию на тестовом стенде
- Запомните 2-3 основные команды и их назначение

> Совет: разберитесь сначала с «что это делает», потом — «как это работает».`,
        intermediateExplanation: `## На среднем уровне

Здесь важно понимать внутренние механизмы и взаимосвязи с другими подсистемами.

## Что изучить

- Внутреннее устройство и архитектура
- Типовые сценарии использования
- Взаимодействие с соседними подсистемами
- Способы диагностики типичных проблем

\`\`\`bash
# Базовая команда для проверки состояния
systemctl status <service>
\`\`\`

> На этом уровне важно уметь объяснить «почему», а не только «что».`,
        advancedExplanation: `## Для продвинутых

Глубокое понимание реализации, нетривиальные сценарии и оптимизация.

## Темы для углубления

1. Внутренние механизмы и производительность
2. Краевые случаи и сценарии отказов
3. Стратегии оптимизации под нагрузкой
4. Архитектурные компромиссы (trade-offs)

## Что обсудить на ревью

- Метрики, которые стоит мониторить
- Лимиты и узкие места
- Планы масштабирования

> Senior-уровень — это умение предсказывать поведение системы при пиковых нагрузках.`,
        realWorldExample: `## Практический пример

В продакшн-среде **${q.t}** — типичная задача при администрировании систем в 2026 году.

## Сценарий из практики

- Возникает при росте нагрузки или расширении инфраструктуры
- Требует понимания как непосредственной команды, так и контекста
- Ошибки здесь ведут к простою сервиса и потере данных

## План действий при инциденте

1. Подтвердить симптомы и собрать логи
2. Изолировать проблемный компонент
3. Применить известный fix или откатить изменение
4. Провести post-mortem и обновить runbook

> При расследовании инцидента понимание этой темы помогает быстро определить корневую причину.`,
        interviewTips: `## Советы для собеседования

Будьте готовы объяснить **${q.t}** с примерами из реального опыта.

## Структура идеального ответа

1. **Определение** — чётко сформулируйте, что это такое
2. **Пример из практики** — конкретный случай с цифрами
3. **Краевые случаи** — что идёт не так и как чинить
4. **Связь с бизнесом** — влияние на надёжность/производительность

## Типичные вопросы

- «Расскажите о случае, когда вы это настраивали в продакшене»
- «Как бы вы отладили проблему с этой технологией?»
- «Какие альтернативы вы рассматривали и почему выбрали эту?»

> Главное правило: лучше честно сказать «не знаю, но вот как бы я подошёл», чем выдумывать.`,
        relatedTopics: q.tags.join(', '),
      },
    })
    created++
  }
  console.log(`Created ${created} questions with AI explanations`)

  await prisma.updateLog.create({
    data: {
      type: 'seed',
      status: 'completed',
      details: `Заполнение v3: ${categories.length} категорий, ${created} вопросов`,
      itemsCount: created,
    },
  })

  console.log('Seeding complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
