import { neon } from '@neondatabase/serverless'

const connectionString = process.env.DATABASE_URL || ''

if (!connectionString.includes('neon.tech')) {
  console.error('This script is for Neon PostgreSQL only')
  process.exit(1)
}

const sql = neon(connectionString)

const categories = [
  { name: 'Основы Linux', slug: 'linux-fundamentals', description: 'Основы Linux/Unix: командная строка, базовые утилиты, структура системы, ядро, загрузка, процессы', icon: 'Terminal', order: 1 },
  { name: 'Системное администрирование', slug: 'sysadmin', description: 'Управление пользователями и процессами, дисками и файловыми системами, загрузчиками, сервисами, пакетами, мониторинг системы', icon: 'Settings', order: 2 },
  { name: 'Серверы Linux', slug: 'linux-servers', description: 'Настройка web, DNS, DHCP, баз данных, файловых серверов, почтовых серверов, SSH', icon: 'Server', order: 3 },
  { name: 'Хранилище Linux', slug: 'linux-storage', description: 'Управление дисками, разделами, RAID, LVM, ZFS, Stratis, NFS, iSCSI, автомонтирование', icon: 'HardDrive', order: 4 },
  { name: 'Безопасность Linux', slug: 'linux-security', description: 'Права доступа, ACL, SELinux, AppArmor, PAM, пользователи и пароли, файрволы, аудит', icon: 'Shield', order: 5 },
  { name: 'Сети', slug: 'networking', description: 'TCP/IP, DNS, маршрутизация, файрволы, VPN, устранение неполадок сети', icon: 'Network', order: 6 },
  { name: 'Bash', slug: 'bash', description: 'Скриптинг, автоматизация, обработка текста, командная строка', icon: 'Code', order: 7 },
  { name: 'Docker', slug: 'docker', description: 'Контейнеризация, Dockerfiles, Docker Compose, управление образами', icon: 'Container', order: 8 },
  { name: 'Kubernetes', slug: 'kubernetes', description: 'Архитектура K8s, поды, сервисы, деплойменты, Helm, управление кластером', icon: 'Blocks', order: 9 },
  { name: 'Terraform', slug: 'terraform', description: 'Infrastructure as Code, HCL, управление состоянием, модули, провайдеры', icon: 'Layers', order: 10 },
  { name: 'Ansible', slug: 'ansible', description: 'Управление конфигурацией, плейбуки, роли, инвентарь, автоматизация', icon: 'Play', order: 11 },
  { name: 'AWS', slug: 'aws', description: 'Amazon Web Services: EC2, S3, Lambda, VPC, IAM, облачная архитектура', icon: 'Cloud', order: 12 },
  { name: 'Azure', slug: 'azure', description: 'Microsoft Azure: VMs, Blob Storage, Functions, Active Directory, Bicep', icon: 'CloudRain', order: 13 },
  { name: 'GCP', slug: 'gcp', description: 'Google Cloud: Compute Engine, Cloud Storage, BigQuery, GKE, IAM', icon: 'CloudSun', order: 14 },
  { name: 'DevOps', slug: 'devops', description: 'CI/CD, GitOps, культура DevOps, SRE, управление релизами', icon: 'GitBranch', order: 15 },
  { name: 'Мониторинг', slug: 'monitoring', description: 'Наблюдаемость, Prometheus, Grafana, ELK, алертинг, управление инцидентами', icon: 'Activity', order: 16 },
  { name: 'Базы данных', slug: 'databases', description: 'SQL, PostgreSQL, MySQL, Redis, MongoDB, репликация, бэкап, оптимизация', icon: 'Database', order: 17 },
  { name: 'Веб-серверы', slug: 'web-servers', description: 'Nginx, Apache, обратный прокси, балансировка, SSL/TLS, оптимизация', icon: 'Globe', order: 18 },
  { name: 'eBPF', slug: 'ebpf', description: 'eBPF-программы, BCC, bpftrace, XDP, наблюдаемость ядра', icon: 'Zap', order: 19 },
  { name: 'Облачная безопасность', slug: 'cloud-security', description: 'IAM, WAF, защита облака, комплаенс, аудит, постквантовая криптография', icon: 'Lock', order: 20 },
]

type Q = { c: string; t: string; q: string; a: string; d: string; tags: string[] }

const questions: Q[] = [
  // === LINUX FUNDAMENTALS ===
  {c:'linux-fundamentals',t:'Что такое ядро Linux и его архитектура',q:'Опишите архитектуру ядра Linux: основные подсистемы, их назначение и взаимодействие.',a:'Ядро Linux — монолитное с модульной поддержкой. Подсистемы: Process Scheduler (CFS) — планирование задач; Memory Manager — виртуальная память, страницы, slab; VFS — абстракция файловых систем; Network Stack — TCP/IP; Device Drivers — управление устройствами; IPC — pipes, signals, shared memory, message queues. Ядро работает в ring 0, пользовательские процессы — в ring 3. Системные вызовы — интерфейс между пространствами. Модули: insmod/rmmod, lsmod, modprobe. В 2026: eBPF-программы расширяют ядро без модулей; io_uring заменяет множество syscalls.',d:'intermediate',tags:['ядро','архитектура','модули']},
  {c:'linux-fundamentals',t:'Как работает загрузка Linux',q:'Опишите процесс загрузки от BIOS/UEFI до командной строки, включая init-систему.',a:'Процесс: 1) BIOS/UEFI — POST, выбор загрузочного устройства; 2) Bootloader (GRUB2) — загрузка ядра и initramfs; 3) Ядро — инициализация подсистем, монтирование rootfs; 4) PID 1 — systemd (init); 5) systemd — запуск юнитов по зависимостям. GRUB2: /boot/grub/grub.cfg, настройка через /etc/default/grub. Initramfs: временная файловая система с модулями для rootfs. Systemd: systemctl list-units, systemctl enable/disable, journalctl. Runlevels: multi-user.target (3), graphical.target (5). В 2026: systemd-boot заменяет GRUB; UKI (Unified Kernel Image) совмещает ядро и initramfs.',d:'intermediate',tags:['загрузка','grub','systemd']},
  {c:'linux-fundamentals',t:'Объясните права доступа и ACL',q:'Как работают традиционные права Unix и списки контроля доступа (ACL)?',a:'Традиционные права: rwx для owner/group/others (3 бита). Специальные: setuid (4) — выполняется от владельца; setgid (2) — новые файлы наследуют группу; sticky bit (1) — удалять может только владелец. Команды: chmod 755 file, chown user:group file, umask 022. ACL: getfacl file, setfacl -m u:alice:rw file. Маски ACL ограничивают максимальные права. По умолчанию: setfacl -d -m g:devs:rx dir. ACL позволяет назначать права конкретным пользователям и группам за пределами модели owner/group/others. В 2026: RichACL для NFSv4; NFSv4 ACL — стандартизированный формат.',d:'beginner',tags:['права','acl','безопасность']},
  {c:'linux-fundamentals',t:'Как работают процессы и сигналы',q:'Опишите жизненный цикл процесса, состояния и механизм сигналов.',a:'Жизненный цикл: fork() — создание копии; exec() — замена образа; exit() — завершение; parent wait() — сбор статуса. Состояния: Running, Sleeping (S — прерываемое, D — непрерываемое), Stopped, Zombie. Сигналы: SIGTERM (15) — завершить, SIGKILL (9) — убить, SIGINT (2) — Ctrl+C, SIGHUP (1) — перечитать конфиг, SIGSTOP/SIGCONT — пауза/продолжение. Приоритеты: nice (-20..19), renice, ionice. Команды: ps aux, top, htop, kill -l, kill -TERM PID, pgrep, pkill. В 2026: cgroups v2 для изоляции; systemd-run для транзитных сервисов.',d:'beginner',tags:['процессы','сигналы','управление']},
  {c:'linux-fundamentals',t:'Как работает виртуальная память',q:'Опишите механизмы виртуальной памяти: страницы, swap, OOM killer.',a:'Виртуальная память: каждая страница 4 КБ (ARM64 может 16/64 КБ). Таблицы страниц — 4 уровня (PGD, PUD, PMD, PTE). TLB кэширует трансляции. Swap: раздел или файл, swapon/swapoff, vm.swappiness (по умолчанию 60). OOM Killer: при нехватке памяти ядро выбирает процесс для убийства на основе oom_score (память, приоритет, время). Настройка: /proc/PID/oom_score_adj (-1000..1000). Доступ: /proc/meminfo, free -h, vmstat, pmap PID. В 2026: MGLRU (Multi-Gen LRU) — улучшенная замена страниц; zram — сжатый swap в памяти.',d:'advanced',tags:['память','swap','oom']},
  {c:'linux-fundamentals',t:'Как работают файловые системы',q:'Опишите ext4, XFS, Btrfs и их ключевые особенности.',a:'ext4: журналируемая, обратная совместимость с ext2/3, максимальный файл 16 ТБ, extents (уменьшают фрагментацию), delayed allocation. XFS: высокопроизводительная, параллельный ввод-вывод, reflink (CoW клонирование), online resize (только увеличение), предсказуемая производительность. Btrfs: CoW, снимки, подтома, сжатие (zstd), RAID, проверка данных, send/receive. Выбор: ext4 — по умолчанию; XFS — для больших файлов/БД; Btrfs — для снимков и управления томами. Монтирование: /etc/fab, mount -o noatime. В 2026: bcachefs — новая CoW ФС с кэшированием; idmapped mounts для контейнеров.',d:'intermediate',tags:['файловые-системы','ext4','xfs','btrfs']},

  // === SYSTEM ADMINISTRATION ===
  {c:'sysadmin',t:'Как управлять пользователями и группами',q:'Опишите создание, модификацию и удаление пользователей и групп в Linux.',a:'Пользователи: useradd -m -s /bin/bash -G docker username; usermod -aG sudo username; userdel -r username. Группы: groupadd devops; gpasswd -a user devops; groupdel devops. Файлы: /etc/passwd (user:x:UID:GID:comment:home:shell), /etc/shadow (хэши паролей), /etc/group. Пароли: passwd username; chage -M 90 username (срок действия). Переключение: su - username; sudo -u user command. Skeleton: /etc/skel/ — шаблон домашнего каталога. В 2026: systemd-homed — переносимые домашние каталоги; SSSD для LDAP/AD интеграции.',d:'beginner',tags:['пользователи','группы','управление']},
  {c:'sysadmin',t:'Как управлять пакетами в Linux',q:'Опишите пакетные менеджеры apt, dnf, zypper и best practices.',a:'Debian/Ubuntu (APT): apt update; apt upgrade; apt install pkg; apt remove pkg; apt search keyword; apt list --upgradable. RHEL/Fedora (DNF): dnf install pkg; dnf remove pkg; dnf update; dnf search keyword; dnf autoremove. openSUSE (Zypper): zypper install pkg; zypper update; zypper search. Репозитории: /etc/apt/sources.list; add-apt-repository; dnf config-manager --add-repo. Лучшие практики: регулярные обновления безопасности; unattended-upgrades; pinning для фиксации версий; apt-mark hold. В 2026: apt-get устарел; dnf5 — новая реализация; transactional-update (openSUSE) — атомарные обновления.',d:'beginner',tags:['пакеты','apt','dnf']},
  {c:'sysadmin',t:'Как управлять службами через systemd',q:'Опишите юниты, таймеры, журналирование и устранение неполадок.',a:'Юниты: service, socket, timer, target, mount, path. Команды: systemctl start/stop/restart/reload service; systemctl enable/disable; systemctl status; systemctl list-units --type=service. Таймеры: заменяют cron; OnCalendar=*:0/15; AccuracySec=1s; systemctl list-timers. Журналирование: journalctl -u service; journalctl --since "1 hour ago"; journalctl -f; journalctl -p err. Создание юнита: /etc/systemd/system/my.service с [Unit], [Service], [Install]. Отладка: systemd-analyze blame; systemd-analyze critical-chain; systemctl daemon-reload. В 2026: systemd-sysupdate; systemctl edit --runtime для временных изменений.',d:'intermediate',tags:['systemd','сервисы','юниты']},
  {c:'sysadmin',t:'Как настраивать cron и запланированные задачи',q:'Опишите синтаксис crontab, системные cron-задачи и альтернативы.',a:'Синтаксис: мин час день_мес день_нед команда. Примеры: */5 * * * * — каждые 5 минут; 0 2 * * * — каждый день в 2:00; 0 0 1 * * — первого числа каждого месяца. Пользовательские: crontab -e; crontab -l. Системные: /etc/crontab; /etc/cron.d/; /etc/cron.daily/, weekly, monthly. Переменные: SHELL, PATH, MAILTO. Логирование: /var/log/syslog; grep CRON. Альтернативы: systemd-timer (зависимости, точность); at (одноразовые). Ограничения: /etc/cron.allow, /etc/cron.deny. В 2026: systemd-timer предпочтительнее для новых систем; Fleet Commander для массового управления.',d:'beginner',tags:['cron','планирование','автоматизация']},
  {c:'sysadmin',t:'Как настраивать сеть в Linux',q:'Опишите NetworkManager, systemd-networkd, конфигурационные файлы.',a:'NetworkManager: nmcli device status; nmcli connection show; nmcli con add con-name static ifname eth0 type ethernet ip4 192.168.1.100/24 gw4 192.168.1.1; nmcli con mod static ipv4.dns "8.8.8.8 8.8.4.4". systemd-networkd: /etc/systemd/network/20-wired.network с [Match], [Network], [Address], [Gateway]. Файлы: /etc/hosts; /etc/resolv.conf; /etc/nsswitch.conf. Инструменты: ip addr; ip route; ss -tlnp; ethtool; traceroute; mtr. DNS: resolvectl status; systemd-resolved. В 2026: Netplan (Ubuntu) — декларативная конфигурация; NetworkManager для десктопов; systemd-networkd для серверов.',d:'intermediate',tags:['сеть','networkmanager','конфигурация']},
  {c:'sysadmin',t:'Как работает логирование в Linux',q:'Опишите syslog, journald, ротацию логов и анализ.',a:'Syslog: facility (kern, auth, daemon) + severity (emerg..debug); /etc/rsyslog.conf; /var/log/auth.log, syslog, kern.log. Journald: структурированные логи; journalctl -u ssh; journalctl --since yesterday; journalctl -f; journalctl -o json-pretty. Ротация: logrotate; /etc/logrotate.d/; daily/weekly; compress; missingok; postrotate. Анализ: grep, awk; journalctl --grep "error"; aureport (SELinux). Централизованное: rsyslog → удалённый сервер; Fluentd/Fluent Bit → Elasticsearch. В 2026: journald — по умолчанию; structured logging; OpenTelemetry logs.',d:'intermediate',tags:['логирование','syslog','journald']},

  // === LINUX SERVERS ===
  {c:'linux-servers',t:'Как настроить SSH-сервер',q:'Опишите конфигурацию sshd, ключи, туннели и безопасность.',a:'Конфигурация: /etc/ssh/sshd_config; Port 22; PermitRootLogin no; PasswordAuthentication no; PubkeyAuthentication yes; AllowUsers user@192.168.1.*. Ключи: ssh-keygen -t ed25519; ssh-copy-id user@host; ~/.ssh/authorized_keys; chmod 600. Туннели: -L local_port:remote_host:remote_port (локальный); -R remote_port:local_host:local_port (удалённый); -D port (SOCKS-прокси). Jump host: ProxyJump в ~/.ssh/config. Multiplexing: ControlMaster, ControlPath для повторного использования соединения. Безопасность: fail2ban; MaxAuthTries 3; LoginGraceTime 30; Banner. В 2026: SSH-сертификаты вместо trust-on-first-use; FIDO2-ключи; криптографические hardware-токены.',d:'intermediate',tags:['ssh','сервер','безопасность']},
  {c:'linux-servers',t:'Как настроить DNS-сервер BIND',q:'Опишите установку, конфигурацию зон и управление BIND9.',a:'Установка: apt install bind9. Конфигурация: /etc/bind/named.conf.options — forwarders, allow-recursion; /etc/bind/named.conf.local — объявление зон. Прямая зона: $ORIGIN example.com; @ IN SOA ns1.example.com. admin.example.com. (2026010101 3600 900 604800 86400); @ IN NS ns1.example.com.; ns1 IN A 192.168.1.1; www IN A 192.168.1.10. Обратная зона: $ORIGIN 1.168.192.in-addr.arpa; 1 IN PTR ns1.example.com. Проверка: named-checkzone example.com /etc/bind/db.example; named-checkconf; dig example.com @localhost. Управление: rndc reload; rndc status; journalctl -u bind9. В 2026: PowerDNS с API; CoreDNS для Kubernetes; DNS-over-HTTPS.',d:'intermediate',tags:['dns','bind','сервер']},
  {c:'linux-servers',t:'Как настроить DHCP-сервер',q:'Опишите установку и конфигурацию ISC DHCP или Kea.',a:'ISC DHCP: apt install isc-dhcp-server; /etc/dhcp/dhcpd.conf. Конфигурация: subnet 192.168.1.0 netmask 255.255.255.0 { range 192.168.1.100 192.168.1.200; option routers 192.168.1.1; option domain-name-servers 8.8.8.8; option domain-name "local"; default-lease-time 600; max-lease-time 7200; }. Фиксированные: host server1 { hardware ethernet 00:11:22:33:44:55; fixed-address 192.168.1.50; }. Проверка: dhcpd -t -cf /etc/dhcp/dhcpd.conf; journalctl -u isc-dhcp-server. Аренда: /var/lib/dhcp/dhcpd.leases. Kea: современная замена, REST API, MySQL/PostgreSQL backend, HA. В 2026: Kea рекомендована; ISC DHCP — end-of-life.',d:'beginner',tags:['dhcp','kea','сеть']},
  {c:'linux-servers',t:'Как настроить почтовый сервер Postfix',q:'Опишите базовую конфигурацию Postfix, Dovecot и защиту от спама.',a:'Postfix: apt install postfix; /etc/postfix/main.cf — myhostname, mydomain, myorigin, inet_interfaces, mydestination, mynetworks. Dovecot: apt install dovecot-imapd; /etc/dovecot/conf.d/10-mail.conf — mail_location = maildir:~/Maildir; 10-auth.conf — auth_mechanisms = plain login. Защита: SPF (TXT запись), DKIM (opendkim), DMARC. SpamAssassin для фильтрации. TLS: smtpd_tls_cert_file, smtpd_tls_key_file, smtpd_use_tls=yes. Проверка: telnet localhost 25; sendmail -v user@domain < email.txt; postqueue -p; postsuper -d ALL. В 2026: MTA-STS; DANE; MIMI (Messaging Layer Security).',d:'intermediate',tags:['postfix','почта','dovecot']},
  {c:'linux-servers',t:'Как настроить NFS-сервер',q:'Опишите экспорт директорий, монтирование и безопасность NFS.',a:'Сервер: apt install nfs-kernel-server; /etc/exports — /data 192.168.1.0/24(rw,sync,no_subtree_check) *(ro,sync). Экспорт: exportfs -a; exportfs -v. Клиент: apt install nfs-common; mount -t nfs server:/data /mnt/data; /etc/fab — server:/data /mnt/data nfs defaults 0 0. Версии: NFSv3 (UDP/TCP, stateless); NFSv4 (только TCP, stateful, Kerberos, firewall-friendly). Безопасность: sec=sys (по умолчанию, UID); sec=krb5 (Kerberos); sec=krb5i (целостность); sec=krb5p (шифрование). Root squashing: root_squash (по умолчанию), no_root_squash. В 2026: NFSv4.2 (server-side copy, space reservation); pNFS для параллельного доступа.',d:'intermediate',tags:['nfs','файловый-сервер','экспорт']},

  // === LINUX STORAGE ===
  {c:'linux-storage',t:'Как работает LVM',q:'Опишите физические тома, группы томов, логические тома и их управление.',a:'Иерархия: PV (Physical Volume) → VG (Volume Group) → LV (Logical Volume). PV: pvcreate /dev/sdb; pvdisplay; pvscan. VG: vgcreate vg0 /dev/sdb /dev/sdc; vgdisplay; vgextend vg0 /dev/sdd. LV: lvcreate -L 50G -n data vg0; lvdisplay; lvextend -L +10G /dev/vg0/data; resize2fs /dev/vg0/data. Снимки: lvcreate -L 5G -s -n snap /dev/vg0/data (CoW, только LVM). Thin provisioning: lvcreate -L 100G -T vg0/thinpool; lvcreate -V 50G -n thin1 vg0/thinpool. Кэширование: lvconvert --type cache --cachemode writeback. В 2026: VDO (dedup + compression); Stratis для упрощённого управления.',d:'intermediate',tags:['lvm','тома','управление']},
  {c:'linux-storage',t:'Как настроить RAID в Linux',q:'Опишите уровни RAID, программный mdadm и мониторинг.',a:'Уровни: RAID0 (страйп, нет избыточности, 2+ диска); RAID1 (зеркало, 2+ диска); RAID5 (с чётностью, 3+ диска, 1 сбой); RAID6 (двойная чётность, 4+ диска, 2 сбой); RAID10 (зеркало + страйп, 4+ диска). mdadm: mdadm --create /dev/md0 --level=1 --raid-devices=2 /dev/sdb1 /dev/sdc1; mdadm --detail /dev/md0; cat /proc/mdstat. Сборка: mdadm --assemble /dev/md0 /dev/sdb1 /dev/sdc1. Конфигурация: /etc/mdadm/mdadm.conf; update-initramfs -u. Мониторинг: mdadm --monitor --daemonise --mail=admin@example.com /dev/md0. В 2026: mdadm остаётся стандартом; bcachefs с встроенной избыточностью.',d:'intermediate',tags:['raid','mdadm','избыточность']},
  {c:'linux-storage',t:'Как работает ZFS на Linux',q:'Опишите пулы, датасеты, снимки и управление ZFS.',a:'Пулы: zpool create tank /dev/sdb /dev/sdc; zpool status; zpool list; zpool add tank /dev/sdd; zpool replace tank /dev/sdb /dev/sde. Датасеты: zfs create tank/data; zfs set compression=lz4 tank/data; zfs set quota=100G tank/data; zfs list. Снимки: zfs snapshot tank/data@backup; zfs list -t snapshot; zfs rollback tank/data@backup; zfs send tank/data@backup | zfs recv backup/data. Свойства: atime=off, recordsize=1M (для БД), dedup=on (осторожно — память). ARC: arc_summary; zfs_arc_max. В 2026: OpenZFS 2.3 с dRAID; ZFS Delegation; encryption=on.',d:'advanced',tags:['zfs','пулы','снимки']},
  {c:'linux-storage',t:'Как работает Stratis',q:'Опишите Stratis как简化ное решение управления хранилищем в RHEL.',a:'Stratis — уровень над LVM, XFS и thin provisioning для упрощения управления. Установка: dnf install stratisd stratis-cli; systemctl enable --now stratisd. Пулы: stratis pool create pool1 /dev/sdb; stratis pool list; stratis pool add-data pool1 /dev/sdc. Файловые системы: stratis fs create pool1 data; stratis fs list; stratis fs snapshot pool1 data data-snap. Монтирование: /dev/stratis/pool1/data /mnt/data xfs defaults 0 0. Преимущества: автоматическое управление thin provisioning; мгновенные снимки; упрощённый CLI; интеграция с Cockpit. Ограничения: только XFS; нет RAID (используйте mdadm под Stratis); только RHEL/Fedora. В 2026: Stratis — рекомендованный инструмент хранения RHEL.',d:'intermediate',tags:['stratis','хранение','rhel']},
  {c:'linux-storage',t:'Как настроить iSCSI-хранилище',q:'Опишите target и initiator, аутентификацию и мультипуть.',a:'Target (сервер): apt install tgt; /etc/tgt/conf.d/iscsi.conf — <target iqn.2026-01.com.example:storage>; backing-store /dev/sdb; initiator-address 192.168.1.0/24; incominguser user password; </target>. Управление: tgt-admin --execute; tgtadm --mode target --op show. Initiator (клиент): apt install open-iscsi; /etc/iscsi/initiatorname.iscsi; iscsiadm -m discovery -t st -p 192.168.1.1; iscsiadm -m node -T iqn... -p 192.168.1.1 --login. Мультипуть: apt install multipath-tools; /etc/multipath.conf; multipath -ll. В 2026: NVMe-oF (NVMe over Fabrics) — замена iSCSI для высокопроизводительных сценариев; iSER (iSCSI over RDMA).',d:'advanced',tags:['iscsi','хранение','сеть']},

  // === LINUX SECURITY ===
  {c:'linux-security',t:'Как работает SELinux',q:'Опишите архитектуру SELinux, контексты, политики и устранение неполадок.',a:'SELinux — мандатное управление доступом (MAC). Режимы: Enforcing, Permissive, Disabled; getenforce; setenforce 0/1. Контексты: system_u:object_r:httpd_sys_content_t:s0; ls -Z; ps -Z; restorecon -Rv /var/www/. Политики: targeted (по умолчанию), MLS. Типы: httpd_sys_content_t, httpd_sys_rw_content_t, var_log_t, home_root_t. Булевы значения: getsebool -a; setsebool -P httpd_can_network_connect 1. Устранение: sealert -a /var/log/audit/audit.log; audit2allow -M mypolicy; semodule -i mypolicy.pp. Логирование: /var/log/audit/audit.log; aureport -a. В 2026: SELinux — по умолчанию в RHEL; Container SELinux; улучшенные инструменты отладки.',d:'advanced',tags:['selinux','mac','политики']},
  {c:'linux-security',t:'Как работает AppArmor',q:'Опишите профили AppArmor, управление и отладку.',a:'AppArmor — MAC на основе путей (Debian/Ubuntu/SUSE). Режимы: enforce, complain; aa-status; aa-enforce /etc/apparmor.d/usr.sbin.nginx; aa-complain /etc/apparmor.d/usr.sbin.nginx. Профили: /etc/apparmor.d/ — декларативные правила; /etc/apparmor.d/usr.sbin.nginx с allow /var/www/** r, deny /etc/shadow r. Генерация: aa-genprof /usr/sbin/nginx; aa-logprof. Инструменты: aa-unconfined; aa-audit; aa-disable. В отличие от SELinux: на основе путей (не инодов); проще в настройке; менее гранулярный. Интеграция: snapd автоматически создаёт профили; LXD/LXC; Docker. В 2026: AppArmor — по умолчанию в Ubuntu; профили для контейнеров через annotation; улучшенная интеграция с systemd.',d:'intermediate',tags:['apparmor','профили','безопасность']},
  {c:'linux-security',t:'Как настроить файрвол в Linux',q:'Опишите nftables, firewalld и ufw с примерами.',a:'nftables (замена iptables): nft list ruleset; nft add table ip filter; nft add chain ip filter input { type filter hook input priority 0 \; policy drop \}; nft add rule ip filter input ct state established,related accept; nft add rule ip filter input tcp dport 22 accept. firewalld (RHEL): firewall-cmd --permanent --add-service=ssh; firewall-cmd --permanent --add-port=8080/tcp; firewall-cmd --reload; firewall-cmd --list-all; зоны: public, trusted, dmz. ufw (Ubuntu): ufw enable; ufw allow 22/tcp; ufw allow 80/tcp; ufw allow from 192.168.1.0/24; ufw status verbose. В 2026: nftables — стандарт ядра; iptables устарел; bpfilter (eBPF-based) — будущее.',d:'intermediate',tags:['файрвол','nftables','firewalld']},
  {c:'linux-security',t:'Как работает PAM',q:'Опишите архитектуру Pluggable Authentication Modules и типичные конфигурации.',a:'PAM — стек аутентификации. Конфигурация: /etc/pam.d/ — файлы для каждого сервиса (login, sshd, sudo). Типы модулей: auth (идентификация), account (авторизация), password (смена пароля), session (настройка окружения). Управляющие флаги: required (должен пройти), sufficient (если пройден — успех), requisite (если нет — немедленный отказ), optional. Пример: auth required pam_unix.so; auth sufficient pam_google_authenticator.so; account required pam_nologin.so; password requisite pam_pwquality.so minlen=12. Отладка: /etc/security/pam_debug.conf; journalctl -xe. В 2026: pam_namespace для изоляции; FIDO2 через pam_u2f; systemd-homed.',d:'advanced',tags:['pam','аутентификация','модули']},
  {c:'linux-security',t:'Как проводить аудит безопасности Linux',q:'Опишите инструменты и методы аудита: Lynis, OpenSCAP, CIS Benchmarks.',a:'Lynis: apt install lynis; lynis audit system; отчёт: /var/log/lynis.log; /var/log/lynis-report.dat; проверяет: аутентификацию, файрвол, криптографию, ядро, SMB, NFS, обновления. OpenSCAP: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_server --report report.html /usr/share/xml/scap/ssg/content/ssg-ubuntu2204-ds.xml. CIS Benchmarks: рекомендации по настройке: отключить ненужные сервисы; настроить SSH; обновить пакеты; настроить аудит. Ручной аудит: find / -perm -4000 (SUID); rpm -Va (целостность); aide --check (изменения файлов). В 2026: AI-powered аудит; автоматизированная комплаенс-проверка; Zero Trust.',d:'intermediate',tags:['аудит','безопасность','cis']},
  {c:'linux-security',t:'Объясните рукопожатие TLS 1.3 и сертификаты',q:'Опишите процесс рукопожатия TLS 1.3 и проверку цепочки сертификатов.',a:'Рукопожатие TLS 1.3 (1-RTT): 1) ClientHello — версии, шифронаборы, key share; 2) ServerHello — выбранная версия/шифр, сертификат, CertificateVerify, Finished; 3) Клиент проверяет цепочку, отправляет Finished; 4) Данные приложения идут немедленно. Валидация цепочки: разобрать сертификат, извлечь издателя; найти сертификат издателя; проверить подпись публичным ключом издателя; повторить вверх: leaf, intermediate, root; root должен быть в /etc/ssl/certs/; проверки: не истёк, не отозван (CRL/OCSP), имя хоста совпадает с SAN/CN. Улучшения TLS 1.3: удалены RSA key exchange, CBC, MD5; 0-RTT для возобновлённых сессий; forward secrecy обязателен; зашифрованы ServerHello и сертификат. Диагностика: openssl s_client -connect example.com:443 -servername example.com.',d:'advanced',tags:['tls','ssl','сертификаты','шифрование']},
  {c:'linux-security',t:'Как защитить SSH-сервер?',q:'Опишите лучшие практики безопасности SSH: ключи, конфигурация, 2FA, аудит.',a:'Конфигурация /etc/ssh/sshd_config: Port 2222 (нестандартный порт); PermitRootLogin no; PasswordAuthentication no; PubkeyAuthentication yes; MaxAuthTries 3; LoginGraceTime 30; AllowUsers admin@192.168.1.*. Ключи: ssh-keygen -t ed25519 -C "comment" (рекомендация 2026); ssh-copy-id -i ~/.ssh/id_ed25519.pub user@server. 2FA: apt install libpam-google-authenticator; в sshd_config: AuthenticationMethods publickey,keyboard-interactive; настройка PAM в /etc/pam.d/sshd. Аудит: логирование в /var/log/auth.log; анализ через ausearch; мониторинг через fail2ban. Ограничение доступа: AllowUsers, AllowGroups, Match User admin Address 192.168.1.0/24. Jump host: ProxyJump в ~/.ssh/config. В 2026: SSH-сертификаты (ssh-ca) вместо trust-on-first-use; FIDO2-ключи; криптографические hardware-токены.',d:'intermediate',tags:['ssh','безопасность','аутентификация']},

  // === ДОПОЛНИТЕЛЬНЫЕ ТЕМЫ ===
  {c:'networking',t:'Объясните троекратное рукопожатие TCP',q:'Опишите процесс установки и разрыва TCP-соединения.',a:'Установка: 1) Клиент отправляет SYN (seq=x); 2) Сервер отвечает SYN-ACK (seq=y, ack=x+1); 3) Клиент отправляет ACK (ack=y+1), соединение ESTABLISHED. Закрытие: 1) Активная сторона FIN; 2) Пассивная ACK (FIN_WAIT_2, CLOSE_WAIT); 3) Пассивная FIN (LAST_ACK); 4) Активная ACK + TIME_WAIT (2*MSL). TIME_WAIT обеспечивает достижение последнего ACK и устаревание пакетов. Диагностика: ss -tanp; tcpdump -i eth0. В 2026: TCP-AO заменяет TCP-MD5 для BGP; TCP Fast Open уменьшает задержку.',d:'beginner',tags:['tcp','рукопожатие','протоколы']},
  {c:'networking',t:'Как работает DNS-разрешение?',q:'Опишите полный процесс DNS-разрешения от приложения до авторитетного сервера.',a:'Процесс: 1) Приложение вызывает getaddrinfo(); 2) Stub resolver проверяет /etc/hosts, затем /etc/resolv.conf; 3) Рекурсивный resolver проверяет кэш; 4) Корневой сервер возвращает NS для TLD; 5) TLD-сервер возвращает NS для авторитетного; 6) Авторитетный возвращает ответ; 7) Рекурсивный кэширует с TTL. Типы записей: A/AAAA, CNAME, MX, NS, TXT (SPF, DKIM, DMARC), SRV, SOA. Диагностика: dig example.com A +trace; nslookup example.com. В 2026: DNS-over-HTTPS (DoH) и DNS-over-TLS (DoT); DNSSEC; Encrypted Client Hello (ECH) скрывает SNI.',d:'intermediate',tags:['dns','разрешение','протоколы']},
  {c:'networking',t:'Объясните BGP и его роль в интернет-маршрутизации',q:'Что такое Border Gateway Protocol и почему он критически важен?',a:'BGP — протокол векторного пути, соединяющий автономные системы (AS). eBGP — между разными AS; iBGP — внутри одной AS. Атрибуты пути: AS-PATH, NEXT-HOP, LOCAL-PREF, MED, COMMUNITY. Выбор маршрута: наивысший LOCAL-PREF, кратчайший AS-PATH, наименьший MED, eBGP предпочтительнее iBGP. BGP переносит более 1 млн маршрутов; одна ошибка — утечки маршрутов или чёрные дыры. Безопасность: RPKI проверяет происхождение; BGPsec валидирует путь. В 2026: ASPA (AS Provider Authorization) — защита от утечек маршрутов.',d:'advanced',tags:['bgp','маршрутизация','интернет']},
  {c:'bash',t:'Расширение переменных и подстановка параметров',q:'Опишите типы расширения параметров в Bash с примерами.',a:'Базовое: $VAR; ${VAR:-default} — по умолчанию; ${VAR:=default} — присвоить; ${VAR:+alternate} — альтернативное; ${VAR:?error} — ошибка. Строки: ${#VAR} — длина; ${VAR%pattern} — удалить кратчайший суффикс; ${VAR%%pattern} — длиннейший; ${VAR#pattern} — кратчайший префикс; ${VAR##pattern} — длиннейший; ${VAR/old/new} — заменить первое; ${VAR//old/new} — все. Пример: FILE="archive.tar.gz"; ${FILE##*.} = gz; ${FILE%.*} = archive.tar. Bash 5.2+: ${var@U} — верхний регистр; ${var@L} — нижний; ${var@Q} — экранирование.',d:'intermediate',tags:['bash','переменные','расширение']},
  {c:'bash',t:'Как эффективно обрабатывать текстовые файлы?',q:'Опишите ключевые инструменты обработки текста с примерами.',a:'grep: grep -r "pattern" /path; grep -i "pattern" file; grep -E "regex" file; grep -v "pattern". sed: sed -n "10,20p" file; sed "s/old/new/g" file; sed -i.bak "s/old/new/g" file. awk: awk "{print $1, $3}" file; awk -F: "{print $1}" /etc/passwd; awk "$3 > 100 {print}" file. sort/uniq: sort file | uniq -c | sort -rn. Альтернативы 2026: ripgrep (rg) — быстрее grep; fd — замена find; jq/yq — JSON/YAML; mlr (Miller) — CSV/TSV.',d:'beginner',tags:['bash','обработка-текста','grep','awk','sed']},
  {c:'bash',t:'Напишите надёжный шаблон Bash-скрипта',q:'Создайте шаблон Bash-скрипта продакшн-качества.',a:'Начните: #!/usr/bin/env bash; set -euo pipefail; IFS=$"\\n\\t". Константы: readonly SCRIPT_NAME="$(basename "$0")"; readonly LOG_FILE="/var/log/${SCRIPT_NAME}.log". Логирование: log() { echo "[$(date +"%Y-%m-%d %H:%M:%S")] [$1] $2" | tee -a "$LOG_FILE"; }. Очистка: cleanup() { rm -f "$TEMP_FILE"; exit $?; }; trap cleanup EXIT. Парсинг: while [[ $# -gt 0 ]]; do case $1 in -v|--verbose) VERBOSE=true; shift ;; -h|--help) usage ;; *) INPUT="$1"; shift ;; esac; done. Практики: set -euo pipefail; trap для очистки; логирование; readonly для констант. В 2026: shellcheck для анализа; shfmt для форматирования.',d:'intermediate',tags:['bash','скриптинг','лучшие-практики']},
  {c:'docker',t:'Как написать оптимальный Dockerfile?',q:'Опишите лучшие практики: многоступенчатая сборка, минимизация слоёв, безопасность.',a:'Многоступенчатая: FROM node:20 AS builder; COPY .; RUN npm ci && npm run build; FROM node:20-slim; COPY --from=builder /app/dist ./dist. Минимизация: RUN apt-get update && apt-get install -y pkg && rm -rf /var/lib/apt/lists/*. Безопасность: USER 1000; COPY --chown=1000:1000; --secret для секретов; .dockerignore. Оптимизация кэша: COPY package*.json; RUN npm ci; COPY . . Базовые образы: alpine (5 МБ, musl); slim (glibc); distroless (без оболочки). В 2026: BuildKit — стандарт; --mount=type=cache; --mount=type=secret.',d:'intermediate',tags:['docker','dockerfile','оптимизация']},
  {c:'docker',t:'Как настроить Docker Compose?',q:'Опишите структуру docker-compose.yml, сети, volumes, переменные.',a:'Структура: services: web: build: ., ports: ["8080:80"], depends_on: [db], environment: DB_HOST: db; db: image: postgres:16, environment: POSTGRES_PASSWORD: secret, volumes: [db-data:/var/lib/postgresql/data]. Сети: networks: frontend:, backend:. Volumes: именованные (db-data:), bind-mount (./src:/app/src), tmpfs. Переменные: .env файл; environment в compose; env_file: .env. Healthcheck: healthcheck: test: ["CMD", "curl", "-f", "http://localhost"], interval: 30s. Ресурсы: deploy: resources: limits: cpus: "0.5", memory: 512M. В 2026: docker compose V2 (Go); profiles; watch для автоперезагрузки.',d:'intermediate',tags:['docker','compose','оркестрация']},
  {c:'kubernetes',t:'Объясните архитектуру Kubernetes',q:'Опишите компоненты control plane, worker node и поток запросов.',a:'Control Plane: kube-apiserver — REST API; etcd — хранилище состояния; kube-scheduler — назначение подов; kube-controller-manager — контроллеры; cloud-controller-manager — облако. Worker Node: kubelet — агент; kube-proxy — сетевой прокси; containerd — runtime. Поток: kubectl → apiserver (RBAC, admission) → etcd → scheduler → kubelet → container runtime → kube-proxy. В 2026: K8s 1.31+ с Gateway API, структурная авторизация, улучшенный HPA.',d:'intermediate',tags:['kubernetes','архитектура','control-plane']},
  {c:'kubernetes',t:'Что такое Gateway API?',q:'Объясните Gateway API как замену Ingress, его ресурсы и преимущества.',a:'Gateway API — замена Ingress. Роли: Cluster Admin — GatewayClass, Gateway; Operator — Gateway; Developer — HTTPRoute. Ресурсы: GatewayClass — контроллер; Gateway — инфраструктура; HTTPRoute — маршрутизация; TCPRoute, GRPCRoute. Преимущества: ролевая модель, кросс-неймспейс, TCP/UDP/gRPC, traffic splitting, заголовки. Реализации: Istio, Contour, Envoy Gateway, Traefik. В 2026: GA для HTTPRoute.',d:'advanced',tags:['kubernetes','gateway-api','ingress']},
  {c:'terraform',t:'Как работает Terraform и управление состоянием?',q:'Объясните HCL, провайдеры, ресурсы, state file и лучшие практики.',a:'Terraform — Infrastructure as Code. HCL описывает желаемое состояние. Провайдеры: provider "aws" { region = "us-east-1" }. Ресурсы: resource "aws_instance" "web" { ami = "ami-xxx", instance_type = "t3.micro" }. State file: отображает ресурсы между конфигурацией и облаком. Remote state: S3 + DynamoDB, Blob Storage, GCS, Terraform Cloud. Лучшие практики: удалённый state с блокировкой; не редактируйте вручную; workspaces для сред; модули; plan перед apply. В 2026: OpenTofu — open-source форк.',d:'intermediate',tags:['terraform','iac','state','hcl']},
  {c:'ansible',t:'Как работает Ansible и как написать плейбук?',q:'Объясните архитектуру, инвентарь, модули и структуру плейбука.',a:'Ansible — агентless через SSH. Инвентарь: /etc/ansible/hosts; [webservers] web1 ansible_host=192.168.1.10. Модули: apt/yum, copy/template, service, user, command/shell. Плейбук: ---, hosts: webservers, become: yes, tasks: - name: Install Nginx, apt: name=nginx state=present. Handlers: handlers: - name: reload nginx, service: name=nginx state=reloaded. Роли: tasks/, handlers/, templates/, files/, vars/, defaults/, meta/. В 2026: Ansible Navigator, AWX/Tower, Execution Environments.',d:'intermediate',tags:['ansible','плейбуки','автоматизация']},
  {c:'devops',t:'Что такое CI/CD и как его реализовать?',q:'Объясните принципы Continuous Integration и Continuous Delivery.',a:'CI: частые коммиты, автоматическая сборка и тестирование. CD (Delivery): автоматическая подготовка релиза, ручное подтверждение. CD (Deployment): полностью автоматический деплой. Инструменты: GitHub Actions — .github/workflows/ci.yml; GitLab CI — .gitlab-ci.yml; Jenkins; ArgoCD — GitOps для K8s. Практики: feature flags; canary deployments; blue-green; smoke tests; автоматический откат. В 2026: GitOps (ArgoCD, Flux) — стандарт; AI-powered test selection.',d:'intermediate',tags:['ci-cd','devops','pipeline']},
  {c:'monitoring',t:'Как настроить Prometheus и Grafana?',q:'Опишите архитектуру Prometheus, типы метрик, PromQL и интеграцию с Grafana.',a:'Prometheus: pull-модель, метрики в text формате, TSDB, PromQL. Типы: Counter (растёт), Gauge (текущее), Histogram (распределение), Summary (квантили). PromQL: rate(http_requests_total[5m]); histogram_quantile(0.95, rate(request_duration_bucket[5m])); sum(rate(http_requests_total[5m])) by (method). Alertmanager: alert: HighErrorRate, expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1. Grafana: data source Prometheus; дашборды; переменные; алерты. В 2026: Grafana Mimir (масштабируемый Prometheus), Loki (логи), Tempo (трейсы).',d:'intermediate',tags:['prometheus','grafana','мониторинг','метрики']},
  {c:'databases',t:'Как оптимизировать производительность PostgreSQL?',q:'Опишите методы оптимизации запросов, индексы и конфигурацию.',a:'Анализ: EXPLAIN ANALYZE SELECT ... Внимание на Seq Scan, Nested Loop, Sort. Индексы: B-tree (=, <, >, BETWEEN); GIN (JSONB, массивы, полнотекстовый); GiST (геометрия); BRIN (огромные таблицы); CREATE INDEX CONCURRENTLY — без блокировки. Конфигурация: shared_buffers = 25% RAM; effective_cache_size = 75% RAM; work_mem = RAM / (max_connections * 3). Мониторинг: pg_stat_activity; pg_stat_database; pg_stat_user_indexes. Массовая загрузка: отключите индексы; COPY вместо INSERT; увеличьте maintenance_work_mem.',d:'intermediate',tags:['postgresql','оптимизация','индексы']},
  {c:'web-servers',t:'Как настроить балансировку нагрузки в Nginx?',q:'Опишите upstream, алгоритмы, health checks и сессии.',a:'Upstream: upstream backend { server 10.0.0.1:8080; server 10.0.0.2:8080; }. Алгоритмы: round-robin; least_conn; ip_hash; hash $request_uri consistent. Health checks: passive — max_fails=3, fail_timeout=30s; active (Plus) — health_check. SSL-терминация: listen 443 ssl; proxy_set_header X-Forwarded-Proto https. Rate limiting: limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s. В 2026: HTTP/3 (QUIC); gRPC-проксирование.',d:'intermediate',tags:['nginx','балансировка','прокси']},
  {c:'aws',t:'Объясните VPC и сетевую архитектуру AWS',q:'Опишите VPC, подсети, Internet Gateway, NAT Gateway и Security Groups.',a:'VPC — изолированная облачная сеть (CIDR /16-/28). Публичные подсети: Internet Gateway в маршрутной таблице. Приватные: NAT Gateway для исходящего. Security Groups: stateful, разрешающие правила, мгновенные изменения. NACL: stateless на уровне подсети, разрешающие и запрещающие. VPC Peering: без транзитивности. Transit Gateway: хаб для VPC и VPN. В 2026: VPC Lattice для маршрутизации между сервисами.',d:'intermediate',tags:['aws','vpc','сеть']},
  {c:'ebpf',t:'Что такое eBPF и зачем он нужен?',q:'Объясните архитектуру eBPF и области применения.',a:'eBPF — запуск песочничных программ в ядре без модулей. Применение: наблюдаемость (трассировка); сеть (XDP, Cilium); безопасность (мониторинг вызовов). Преимущества: производительность (в ядре); безопасность (верификатор); гибкость (без перезагрузки). Инструменты: bpftrace — однострочники; BCC — библиотека; libbpf — C; CO-RE — переносимость. В 2026: Cilium (K8s), Pixie (трассировка), Tetragon (безопасность).',d:'intermediate',tags:['ebpf','наблюдаемость','ядро']},
  {c:'cloud-security',t:'Что такое IAM и принцип наименьших привилегий?',q:'Объясните модели IAM в AWS/Azure/GCP.',a:'AWS IAM: политики, роли, SCP. Azure RBAC: встроенные и кастомные роли, Managed Identity. GCP IAM: принципалы, роли, Workload Identity. Принцип наименьших привилегий: только необходимый минимум; конкретные действия вместо s3:*; условия (IPAddress, MFAAuthenticated). Инструменты: AWS Access Analyzer; Azure PIM; GCP Policy Intelligence. В 2026: Just-In-Time доступ; временные привилегии; AI-анализ политик.',d:'intermediate',tags:['iam','наименьшие-привилегии','облако']},
]

async function main() {
  console.log('Seeding Neon PostgreSQL database...')

  // Insert categories
  for (const cat of categories) {
    await sql`
      INSERT INTO "Category" (id, name, slug, description, icon, "order", "createdAt", "updatedAt")
      VALUES (${generateId()}, ${cat.name}, ${cat.slug}, ${cat.description}, ${cat.icon}, ${cat.order}, NOW(), NOW())
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        description = EXCLUDED.description,
        icon = EXCLUDED.icon,
        "order" = EXCLUDED."order",
        "updatedAt" = NOW()
    `
  }
  console.log(`Created ${categories.length} categories`)

  // Get category IDs
  const catRows = await sql`SELECT id, slug FROM "Category"`
  const catMap = new Map(catRows.map(r => [r.slug, r.id]))

  let created = 0
  for (const q of questions) {
    const categoryId = catMap.get(q.c)
    if (!categoryId) { console.error(`Category not found: ${q.c}`); continue }

    const slug = q.t.toLowerCase().replace(/[^a-zа-яё0-9\s-]/g, '').replace(/\s+/g, '-').slice(0, 100)

    // Insert question
    const [question] = await sql`
      INSERT INTO "Question" (id, title, slug, content, answer, difficulty, source, "isPublished", "order", views, "categoryId", "createdAt", "updatedAt")
      VALUES (${generateId()}, ${q.t}, ${slug}, ${q.q}, ${q.a}, ${q.d}, 'academy', true, 0, 0, ${categoryId}, NOW(), NOW())
      ON CONFLICT (slug) DO UPDATE SET
        title = EXCLUDED.title,
        content = EXCLUDED.content,
        answer = EXCLUDED.answer,
        difficulty = EXCLUDED.difficulty,
        "categoryId" = EXCLUDED."categoryId",
        "updatedAt" = NOW()
      RETURNING id
    `

    const questionId = question.id

    // Insert tags and question-tags
    for (const tagName of q.tags) {
      const tagSlug = tagName.toLowerCase().replace(/\s+/g, '-')
      const [tag] = await sql`
        INSERT INTO "Tag" (id, name, slug, "createdAt")
        VALUES (${generateId()}, ${tagName}, ${tagSlug}, NOW())
        ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
        RETURNING id
      `

      await sql`
        INSERT INTO "QuestionTag" (id, "questionId", "tagId")
        VALUES (${generateId()}, ${questionId}, ${tag.id})
        ON CONFLICT ("questionId", "tagId") DO NOTHING
      `
    }

    // Insert AI explanation
    await sql`
      INSERT INTO "AiExplanation" (id, "questionId", "beginnerExplanation", "intermediateExplanation", "advancedExplanation", "realWorldExample", "interviewTips", "relatedTopics", "generatedAt", model)
      VALUES (${generateId()}, ${questionId},
        ${'Для новичков: ' + q.t + '. Ключевая идея — понять базовые концепции и уметь применять их на практике.'},
        ${'Средний уровень: ' + q.t + '. Здесь важно понимать внутренние механизмы и взаимосвязи с другими подсистемами.'},
        ${'Продвинутый уровень: ' + q.t + '. Глубокое понимание реализации, нетривиальные сценарии и оптимизация.'},
        ${'На практике: ' + q.t + ' — типичная задача при администрировании продакшн-систем в 2026 году.'},
        ${'На собеседовании: будьте готовы объяснить ' + q.t + ' с примерами из реального опыта.'},
        ${q.tags.join(', ')},
        NOW(), 'manual-seed')
      ON CONFLICT ("questionId") DO NOTHING
    `
    created++
  }
  console.log(`Created ${created} questions with AI explanations`)

  // Insert update log
  await sql`
    INSERT INTO "UpdateLog" (id, type, status, details, "itemsCount", "createdAt")
    VALUES (${generateId()}, 'seed', 'completed', ${'Заполнение Neon: ' + categories.length + ' категорий, ' + created + ' вопросов'}, ${created}, NOW())
  `

  console.log('Seeding complete!')
}

function generateId(): string {
  // Generate a cuid-like ID
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
  let id = 'c'
  for (let i = 0; i < 24; i++) {
    id += chars[Math.floor(Math.random() * chars.length)]
  }
  return id
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
