import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const categories = [
  { name: 'Linux', slug: 'linux', description: 'Linux system administration, kernel, file systems, processes, and package management', icon: 'Terminal', order: 1 },
  { name: 'Networking', slug: 'networking', description: 'TCP/IP, DNS, routing, firewalls, VPNs, and network troubleshooting', icon: 'Network', order: 2 },
  { name: 'Bash', slug: 'bash', description: 'Shell scripting, automation, text processing, and command-line mastery', icon: 'Code', order: 3 },
  { name: 'Security', slug: 'security', description: 'System hardening, authentication, encryption, vulnerability management, and compliance', icon: 'Shield', order: 4 },
  { name: 'Docker', slug: 'docker', description: 'Containerization, Dockerfiles, Docker Compose, image management, and container orchestration', icon: 'Container', order: 5 },
  { name: 'Kubernetes', slug: 'kubernetes', description: 'K8s architecture, pods, services, deployments, Helm charts, and cluster management', icon: 'Blocks', order: 6 },
  { name: 'Terraform', slug: 'terraform', description: 'Infrastructure as Code, HCL, state management, modules, and provider configuration', icon: 'Layers', order: 7 },
  { name: 'Ansible', slug: 'ansible', description: 'Configuration management, playbooks, roles, inventory, and automation workflows', icon: 'Play', order: 8 },
  { name: 'AWS', slug: 'aws', description: 'Amazon Web Services: EC2, S3, Lambda, VPC, IAM, and cloud architecture', icon: 'Cloud', order: 9 },
  { name: 'Azure', slug: 'azure', description: 'Microsoft Azure: VMs, Blob Storage, Azure Functions, Active Directory, and ARM templates', icon: 'CloudRain', order: 10 },
  { name: 'GCP', slug: 'gcp', description: 'Google Cloud Platform: Compute Engine, Cloud Storage, BigQuery, GKE, and IAM', icon: 'CloudSun', order: 11 },
  { name: 'DevOps', slug: 'devops', description: 'CI/CD pipelines, GitOps, DevOps culture, SRE practices, and release management', icon: 'GitBranch', order: 12 },
  { name: 'Monitoring', slug: 'monitoring', description: 'Observability, Prometheus, Grafana, ELK stack, alerting, and incident management', icon: 'Activity', order: 13 },
  { name: 'Databases', slug: 'databases', description: 'SQL, PostgreSQL, MySQL, Redis, MongoDB, replication, backup, and performance tuning', icon: 'Database', order: 14 },
  { name: 'Web Servers', slug: 'web-servers', description: 'Nginx, Apache, reverse proxy, load balancing, SSL/TLS, and web server optimization', icon: 'Globe', order: 15 },
]

const questions: { categorySlug: string; title: string; content: string; answer: string; difficulty: string; tags: string[] }[] = [
  // Linux
  { categorySlug: 'linux', title: 'What is the difference between a process and a thread?', content: 'Explain the fundamental differences between processes and threads in Linux, including memory model, context switching, and communication mechanisms.', answer: 'A process is an independent execution unit with its own memory space (code, data, heap, stack). A thread is a lightweight subprocess that shares the process memory space but has its own stack and registers. Key differences:\n\n1. **Memory**: Processes have separate address spaces; threads share the same address space\n2. **Context switching**: Thread switching is faster (less state to save/restore)\n3. **Communication**: Threads communicate via shared memory; processes use IPC (pipes, sockets, shared memory, signals)\n4. **Creation**: Creating a thread (clone/fork with shared memory) is cheaper than creating a process (fork)\n5. **Safety**: A crashed thread can corrupt the entire process; a crashed process does not affect others\n6. **Scheduling**: Both are scheduled by the Linux kernel as "tasks" via the CFS scheduler', difficulty: 'beginner', tags: ['processes', 'threads', 'kernel'] },
  { categorySlug: 'linux', title: 'How does the Linux boot process work?', content: 'Describe the complete Linux boot sequence from power-on to user space initialization.', answer: 'The Linux boot process follows these stages:\n\n1. **BIOS/UEFI POST**: Power-on self-test checks hardware\n2. **Boot loader (GRUB2)**: Located in MBR or EFI partition, loads kernel and initramfs into memory\n3. **Kernel initialization**: Decompresses, detects hardware, loads drivers (from initramfs), mounts root filesystem\n4. **PID 1 (systemd)**: First userspace process starts\n5. **systemd targets**: Sequentially activates units - mounts filesystems, starts services, reaches default.target\n6. **Getty/Login**: TTY or display manager presents login prompt\n\nKey files: `/boot/grub2/grub.cfg`, `/etc/default/grub`, `/etc/systemd/system/default.target`, `journalctl -b`', difficulty: 'intermediate', tags: ['boot', 'grub', 'systemd', 'kernel'] },
  { categorySlug: 'linux', title: 'Explain the Linux virtual memory model and OOM killer', content: 'How does virtual memory work in Linux? What triggers the OOM killer and how does it select victims?', answer: 'Linux virtual memory provides each process an isolated address space through page tables managed by the MMU. Physical RAM is mapped to virtual addresses in 4KB pages (or huge pages).\n\n**Key concepts:**\n- **Swap**: Pages not recently used are swapped to disk\n- **Page cache**: Recently accessed file data cached in RAM\n- **Overcommit**: Linux allows allocating more virtual memory than physical RAM (controlled by vm.overcommit_memory)\n\n**OOM Killer** triggers when:\n- No memory available and swap exhausted\n- Overcommit ratio exceeded\n- No reclaimable pages\n\n**Victim selection**: The OOM killer scores processes (oom_score) based on:\n- Memory usage (higher = more likely killed)\n- Process priority (oom_score_adj, -1000 to +1000)\n- Nice value and CPU time\n- Children count\n\nPrevention: Set oom_score_adj=-1000 on critical processes, use cgroups memory limits, tune vm.overcommit_ratio.', difficulty: 'advanced', tags: ['memory', 'oom', 'kernel', 'virtual-memory'] },
  { categorySlug: 'linux', title: 'What are Linux namespaces and cgroups?', content: 'Explain Linux namespaces and cgroups, their types, and how they enable containerization.', answer: '**Namespaces** isolate what a process can see:\n1. PID - Process IDs\n2. NET - Network stack\n3. MNT - Mount points\n4. UTS - Hostname\n5. IPC - Inter-process communication\n6. USER - User/group IDs\n7. CGROUP - Cgroup root directory\n8. TIME - Boot and monotonic clocks\n\n**Cgroups** limit what a process can use:\n- CPU (cpu, cpuset)\n- Memory (memory)\n- I/O (blkio)\n- Devices (devices)\n- PIDs (pids)\n- Network (net_cls, net_prio)\n\nTogether they form the foundation of Linux containers (Docker, Podman). Namespaces provide isolation; cgroups provide resource limits.\n\nCommands: `unshare --pid --mount --net`, `lsns`, `cat /proc/<pid>/cgroup`, `systemd-run --property=MemoryMax=512M`', difficulty: 'intermediate', tags: ['namespaces', 'cgroups', 'containers', 'kernel'] },
  { categorySlug: 'linux', title: 'How do you troubleshoot high CPU usage on a Linux server?', content: 'A Linux server is experiencing high CPU usage. Walk through the systematic troubleshooting approach.', answer: 'Systematic troubleshooting steps:\n\n1. **Identify the process**: `top`, `htop`, `ps aux --sort=-%cpu | head -20`\n2. **Analyze CPU breakdown**: `mpstat -P ALL 1` (user vs system vs iowait vs steal)\n3. **Per-process details**: `pidstat -p <pid> 1`, `strace -c -p <pid>`\n4. **Check system-wide**: `vmstat 1`, `sar -u 1 5` (from sysstat package)\n5. **Flame graphs**: `perf record -g -p <pid>`, `perf script | stackcollapse-perf.pl | flamegraph.pl`\n6. **Application profiling**: For Java: jstack, jmap; For Python: py-spy; For Node: --prof\n\n**Common causes:**\n- Infinite loops or CPU-bound algorithms\n- Garbage collection storms (Java, Go)\n- Cryptographic operations\n- Compiling/transpiling\n- Kernel issues (soft lockups, driver bugs)\n\n**Quick fixes**: `renice`, `cpulimit`, cgroup CPU limits, `taskset` (CPU pinning)', difficulty: 'intermediate', tags: ['cpu', 'troubleshooting', 'performance'] },
  { categorySlug: 'linux', title: 'Explain Linux file permissions and ACLs', content: 'Describe the Linux permission model including traditional permissions, special bits, and ACLs.', answer: '**Traditional permissions** (rwx for user/group/other):\n- Read (r=4), Write (w=2), Execute (x=1)\n- Example: chmod 755 = rwxr-xr-x\n\n**Special bits:**\n- **SUID (4000)**: Execute as file owner (e.g., /usr/bin/passwd)\n- **SGID (2000)**: Execute as group / new files inherit group\n- **Sticky bit (1000)**: Only owner can delete (e.g., /tmp)\n\n**ACLs** (Access Control Lists) go beyond traditional rwx:\n```bash\n# View ACLs\ngetfacl file.txt\n\n# Grant user bob read/write\nsetfacl -m u:bob:rw file.txt\n\n# Default ACL for new files in directory\nsetfacl -d -m u:bob:rw directory/\n\n# Remove ACL\nsetfacl -x u:bob file.txt\n```\n\nACLs are stored as extended attributes (user.posix_acl_access). They are checked before traditional permissions when present.', difficulty: 'beginner', tags: ['permissions', 'acl', 'security'] },
  { categorySlug: 'linux', title: 'What is systemd and how does it manage services?', content: 'Explain systemd architecture, unit files, targets, and common service management commands.', answer: '**systemd** is the init system (PID 1) for modern Linux distributions.\n\n**Unit types**: service, socket, timer, target, mount, path, slice, scope\n\n**Key directories:**\n- `/etc/systemd/system/` - local overrides\n- `/lib/systemd/system/` - package units\n- `/run/systemd/system/` - runtime units\n\n**Common commands:**\n```bash\nsystemctl start/stop/restart/reload <service>\nsystemctl enable/disable <service>   # boot persistence\nsystemctl status <service>\njournalctl -u <service> -f           # follow logs\nsystemctl list-units --type=service\nsystemctl list-timers --all\n```\n\n**Targets** (replacing runlevels):\n- multi-user.target (runlevel 3)\n- graphical.target (runlevel 5)\n- rescue.target, emergency.target\n\n**Custom overrides** (recommended method):\n```bash\nsystemctl edit <service>  # creates drop-in override\n```\nThis creates `/etc/systemd/system/<service>.service.d/override.conf` without modifying the package unit.', difficulty: 'beginner', tags: ['systemd', 'services', 'init'] },
  { categorySlug: 'linux', title: 'Explain LVM (Logical Volume Manager)', content: 'What is LVM, its components, and how to manage logical volumes?', answer: 'LVM provides flexible disk management by abstracting physical storage.\n\n**Components (bottom-up):**\n1. **PV (Physical Volume)**: Actual disk/partition (`pvcreate /dev/sdb1`)\n2. **VG (Volume Group)**: Pool of PVs (`vgcreate vg0 /dev/sdb1 /dev/sdc1`)\n3. **LV (Logical Volume)**: Logical partition from VG (`lvcreate -L 50G -n data vg0`)\n\n**Common operations:**\n```bash\n# Extend LV\ylvextend -L +10G /dev/vg0/data\nresize2fs /dev/vg0/data        # ext4\nxfs_growfs /mnt/data           # XFS\n\n# Reduce LV (ext4 only, unmount first)\numount /mnt/data\ne2fsck -f /dev/vg0/data\nresize2fs /dev/vg0/data 40G\nlvreduce -L 40G /dev/vg0/data\n\n# Snapshot\nlvcreate -L 5G -s -n backup /dev/vg0/data\n\n# Thin provisioning\nlvcreate -T vg0/thinpool -L 100G\nlvcreate -V 50G -T vg0/thinpool -n thinvol\n```\n\n**Advantages**: Resize online, snapshots, thin provisioning, spanning multiple disks, easy migration with pvmove.', difficulty: 'intermediate', tags: ['lvm', 'storage', 'filesystem'] },

  // Networking
  { categorySlug: 'networking', title: 'Explain the TCP three-way handshake and connection teardown', content: 'Describe the TCP connection establishment and termination process with flags and state transitions.', answer: '**Three-way handshake (connection establishment):**\n1. Client → SYN (seq=x) → Server (state: SYN_SENT)\n2. Server → SYN-ACK (seq=y, ack=x+1) → Client (state: SYN_RCVD)\n3. Client → ACK (seq=x+1, ack=y+1) → Server (state: ESTABLISHED)\n\n**Connection teardown (four-way handshake):**\n1. Active side → FIN → Passive side (state: FIN_WAIT_1)\n2. Passive side → ACK → Active side (state: FIN_WAIT_2, CLOSE_WAIT)\n3. Passive side → FIN → Active side (state: LAST_ACK, TIME_WAIT)\n4. Active side → ACK → Passive side (state: CLOSED)\n\n**TIME_WAIT** (2*MSL, typically 60s) ensures:\n- Last ACK reaches the passive side\n- Delayed/duplicate packets from the old connection are discarded\n\nTroubleshooting: `ss -tanp`, `tcpdump -i eth0 tcp`, `netstat -antp`', difficulty: 'beginner', tags: ['tcp', 'handshake', 'protocols'] },
  { categorySlug: 'networking', title: 'How does DNS resolution work end-to-end?', content: 'Walk through the complete DNS resolution process from application to authoritative server.', answer: 'DNS resolution flow:\n\n1. **Application** calls getaddrinfo() / resolver\n2. **Stub resolver** checks `/etc/hosts`, then `/etc/resolv.conf` for nameserver\n3. **Recursive resolver** (e.g., 8.8.8.8) checks its cache\n4. If cache miss → **Root server** (.) returns NS for TLD\n5. **TLD server** (.com) returns NS for authoritative\n6. **Authoritative server** returns the final answer (A, AAAA, CNAME, etc.)\n7. Recursive resolver caches the result with TTL and returns to client\n\n**Record types:**\n- A/AAAA - IP addresses\n- CNAME - Canonical name (alias)\n- MX - Mail exchange\n- NS - Name server\n- TXT - Text (SPF, DKIM, DMARC)\n- SRV - Service locator\n- SOA - Start of authority\n\n**Troubleshooting:**\n```bash\ndig example.com A +trace     # full resolution path\nnslookup example.com\nhost -t MX example.com\nrndc trace 3                  # increase BIND logging\n```\n\n**DNS caching layers**: Browser → OS → Router → ISP → Recursive resolver', difficulty: 'intermediate', tags: ['dns', 'resolution', 'protocols'] },
  { categorySlug: 'networking', title: 'Explain BGP and its role in internet routing', content: 'What is Border Gateway Protocol, how does it work, and why is it critical for internet operation?', answer: '**BGP** is the path-vector protocol that interconnects Autonomous Systems (AS) on the internet.\n\n**Key concepts:**\n- **AS (Autonomous System)**: A network under single administrative control with a unique AS number\n- **eBGP**: Between different ASes (external)\n- **iBGP**: Within the same AS (internal)\n- **Path attributes**: AS-PATH, NEXT-HOP, LOCAL-PREF, MED, COMMUNITY\n\n**Route selection** (simplified priority):\n1. Highest LOCAL-PREF\n2. Shortest AS-PATH\n3. Lowest MED\n4. eBGP over iBGP\n5. Lowest IGP metric to NEXT-HOP\n6. Oldest route (for stability)\n7. Lowest router ID\n\n**Why BGP matters:**\n- Carries ~900K+ routes on the internet\n- One misconfiguration can cause route leaks or blackholes\n- BGP hijacking is a real attack vector\n\n**Troubleshooting:**\n```bash\n# Show BGP summary\nshow ip bgp summary\n# Show specific prefix\nshow ip bgp 8.8.8.0/24\n# Looking glasses: bgp.he.net, route-views\n```\n\n**Security**: RPKI (Resource Public Key Infrastructure) validates route origins; BGPsec provides path validation.', difficulty: 'advanced', tags: ['bgp', 'routing', 'internet'] },
  { categorySlug: 'networking', title: 'What is the difference between NAT, PAT, and DNAT?', content: 'Explain Network Address Translation variants and their use cases.', answer: '**NAT (Network Address Translation)** maps private IPs to public IPs:\n- **SNAT/Source NAT**: Changes source address (outbound traffic)\n- **DNAT/Destination NAT**: Changes destination address (port forwarding, load balancing)\n- **PAT/Port Address Translation** (NAT Overload): Many private IPs share one public IP using unique port numbers\n\n**How PAT works:**\n```\nPrivate: 192.168.1.10:54321 → Public: 203.0.113.1:54321 → Internet\nPrivate: 192.168.1.11:54321 → Public: 203.0.113.1:54322 → Internet (different port)\n```\n\n**iptables examples:**\n```bash\n# SNAT (outbound)\niptables -t nat -A POSTROUTING -s 192.168.1.0/24 -o eth0 -j SNAT --to 203.0.113.1\n\n# MASQUERADE (dynamic SNAT)\niptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE\n\n# DNAT (port forwarding)\niptables -t nat -A PREROUTING -d 203.0.113.1 -p tcp --dport 80 -j DNAT --to 192.168.1.10:80\n```\n\n**NAT traversal issues**: Breaks end-to-end connectivity; solutions include STUN, TURN, ICE for peer-to-peer protocols.', difficulty: 'intermediate', tags: ['nat', 'firewall', 'routing'] },

  // Bash
  { categorySlug: 'bash', title: 'Explain Bash variable expansion and parameter substitution', content: 'Describe the different types of parameter expansion in Bash with examples.', answer: '**Basic expansion:**\n- `$VAR` or `${VAR}` - value of VAR\n- `${VAR:-default}` - use default if unset or null\n- `${VAR:=default}` - assign default if unset or null\n- `${VAR:+alternate}` - use alternate if VAR is set\n- `${VAR:?error}` - print error and exit if unset\n\n**String manipulation:**\n- `${#VAR}` - string length\n- `${VAR%pattern}` - remove shortest suffix match\n- `${VAR%%pattern}` - remove longest suffix match\n- `${VAR#pattern}` - remove shortest prefix match\n- `${VAR##pattern}` - remove longest prefix match\n- `${VAR/old/new}` - replace first match\n- `${VAR//old/new}` - replace all matches\n- `${VAR^}` / `${VAR^^}` - uppercase first/all chars\n- `${VAR,}` / `${VAR,,}` - lowercase first/all chars\n\n**Examples:**\n```bash\nFILE="archive.tar.gz"\necho ${FILE##*.}     # gz (longest prefix removal)\necho ${FILE%.*}      # archive.tar (shortest suffix removal)\necho ${FILE/.tar/.zip}  # archive.zip.tar.gz\n```\n\n**Arrays:**\n- `${arr[@]}` - all elements\n- `${#arr[@]}` - array length\n- `${arr[*]:2:3}` - slice from index 2, 3 elements', difficulty: 'intermediate', tags: ['bash', 'variables', 'expansion'] },
  { categorySlug: 'bash', title: 'How to process text files efficiently in Bash?', content: 'Describe the key text processing tools (grep, sed, awk, sort, uniq) with practical examples.', answer: '**grep** - Pattern matching:\n```bash\ngrep -r "error" /var/log/          # recursive\ngrep -i "warning" file.log         # case-insensitive\ngrep -E "err|warn|crit" file.log   # extended regex\ngrep -c "pattern" file             # count matches\ngrep -v "debug" file               # invert match\n```\n\n**sed** - Stream editor:\n```bash\nsed -n "10,20p" file               # print lines 10-20\nsed "s/old/new/g" file             # global substitution\nsed -i.bak "s/old/new/g" file      # in-place with backup\nsed "/^$/d" file                   # delete blank lines\n```\n\n**awk** - Field processing:\n```bash\nawk "{print \$1, \$3}" file               # print columns\nawk -F: "{print \$1}" /etc/passwd         # custom delimiter\nawk "\$3 > 100 {print \$0}" file          # conditional\nawk "{sum += \$1} END {print sum}" file   # aggregation\n```\n\n**sort/uniq** - Sorting and deduplication:\n```bash\nsort -t: -k3 -n /etc/passwd       # numeric sort on field 3\nsort file | uniq -c | sort -rn    # frequency count\n```\n\n**Performance tips**: Use LC_ALL=C for faster grep, LC_ALL=C sort is 10x faster, prefer grep over awk for simple matching, use `ripgrep` (rg) for large codebases.', difficulty: 'beginner', tags: ['bash', 'text-processing', 'grep', 'awk', 'sed'] },
  { categorySlug: 'bash', title: 'Write a robust Bash script template', content: 'Create a production-ready Bash script template with proper error handling, logging, and argument parsing.', answer: '```bash\n#!/usr/bin/env bash\nset -euo pipefail\nIFS=$\'\\n\\t\'\n\n# Script metadata\nreadonly SCRIPT_NAME="$(basename "\$0")"\nreadonly SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"\nreadonly LOG_FILE="/var/log/\${SCRIPT_NAME}.log"\n\n# Logging\nlog() { echo "[$(date +\'%Y-%m-%d %H:%M:%S\')] [\$1] \$2" | tee -a "\$LOG_FILE"; }\ninfo()  { log "INFO"  "\$1"; }\nwarn()  { log "WARN"  "\$1"; }\nerror() { log "ERROR" "\$1"; }\n\n# Cleanup on exit\ncleanup() {\n  local exit_code=\$?\n  if [[ \$exit_code -ne 0 ]]; then\n    error "Script failed with exit code \$exit_code"\n  fi\n  # Remove temp files, release locks, etc.\n  rm -f "\$TEMP_FILE" 2>/dev/null || true\n  exit \$exit_code\n}\ntrap cleanup EXIT\n\n# Argument parsing\nusage() {\n  cat <<EOF\nUsage: \$SCRIPT_NAME [OPTIONS] <input>\nOptions:\n  -v, --verbose    Enable verbose output\n  -n, --dry-run    Show what would be done\n  -h, --help       Show this help\nEOF\n  exit 1\n}\n\nVERBOSE=false\nDRY_RUN=false\n\nwhile [[ $# -gt 0 ]]; do\n  case \$1 in\n    -v|--verbose) VERBOSE=true; shift ;;\n    -n|--dry-run) DRY_RUN=true; shift ;;\n    -h|--help)    usage ;;\n    -*)           error "Unknown option: \$1"; usage ;;\n    *)            INPUT="\$1"; shift ;;\n  esac\ndone\n\n[[ -z "\${INPUT:-}" ]] && { error "Input required"; usage; }\n\ninfo "Starting \$SCRIPT_NAME"\n# ... main logic ...\ninfo "Completed successfully"\n```\n\n**Key practices:** set -euo pipefail for safety, trap for cleanup, logging with timestamps, proper argument parsing, readonly for constants.', difficulty: 'intermediate', tags: ['bash', 'scripting', 'best-practices'] },

  // Security
  { categorySlug: 'security', title: 'How do you harden a Linux server?', content: 'Provide a comprehensive checklist for hardening a production Linux server.', answer: '**OS Level:**\n- Keep packages updated: `unattended-upgrades` or `dnf-automatic`\n- Remove unnecessary packages and services\n- Disable root SSH login, use key-based auth only\n- Set `PermitRootLogin no`, `PasswordAuthentication no` in sshd_config\n- Configure firewall: `ufw` or `iptables` / `nftables`\n- Enable automatic security updates\n\n**Authentication:**\n- Enforce SSH key authentication (ed25519 preferred)\n- Implement 2FA (google-authenticator-libpam or Duo)\n- Use `Fail2ban` or `CrowdSec` for brute-force protection\n- Set `umask 027` for tighter default permissions\n- Configure PAM modules for password policies\n\n**Kernel:**\n- Set `kernel.randomize_va_space = 2` (ASLR)\n- Disable unused kernel modules\n- Enable `SELinux` or `AppArmor` in enforcing mode\n- Set `kernel.kptr_restrict = 1`\n\n**Network:**\n- Close all inbound ports except required ones\n- Use VPN for administrative access\n- Enable SYN cookies: `net.ipv4.tcp_syncookies = 1`\n- Disable IP forwarding if not a router\n\n**Audit & Monitoring:**\n- Install and configure `auditd`\n- Enable process accounting (`psacct`)\n- Centralize logs (rsyslog to remote, or journald + log forwarding)\n- Set up integrity checking: `AIDE` or `Tripwire`\n- Use `Lynis` for automated security auditing', difficulty: 'intermediate', tags: ['hardening', 'security', 'linux'] },
  { categorySlug: 'security', title: 'Explain SSL/TLS handshake and certificate chain validation', content: 'Describe the TLS 1.3 handshake process and how certificate chains are validated.', answer: '**TLS 1.3 Handshake** (1-RTT, improved from TLS 1.2\'s 2-RTT):\n1. **ClientHello**: Supported versions, cipher suites, key share (DH public key), supported groups\n2. **ServerHello**: Chosen version/cipher, key share, certificate, CertificateVerify, Finished\n3. **Client**: Verifies certificate chain, sends Finished\n4. **Application data** flows immediately\n\n**Certificate chain validation:**\n1. Parse certificate, extract issuer\n2. Find issuer certificate in chain or trust store\n3. Verify signature of leaf cert using issuer\'s public key\n4. Repeat up the chain: leaf → intermediate → root\n5. Root must be in system trust store (/etc/ssl/certs/)\n6. Check: not expired, not revoked (CRL/OCSP), hostname matches SAN/CN\n7. Check extensions: Key Usage, Extended Key Usage, Basic Constraints\n\n**Key improvements in TLS 1.3:**\n- Removed insecure algorithms (RSA key exchange, CBC mode, MD5, SHA-224)\n- 0-RTT for resumed sessions (with replay risk)\n- Forward secrecy mandatory (ephemeral DH)\n- Encrypted ServerHello and certificate\n\n**Troubleshooting:**\n```bash\nopenssl s_client -connect example.com:443 -servername example.com\nopenssl x509 -in cert.pem -text -noout\ncurl -vI https://example.com 2>&1 | grep -i ssl\n```', difficulty: 'advanced', tags: ['tls', 'ssl', 'certificates', 'encryption'] },
  { categorySlug: 'security', title: 'What is the principle of least privilege and how to implement it?', content: 'Explain the principle of least privilege and practical implementation strategies in a Linux/Cloud environment.', answer: '**Principle of Least Privilege (PoLP)**: Every user, process, and system should have only the minimum privileges necessary to perform its function.\n\n**Linux implementation:**\n- Use `sudo` with specific commands: `user ALL=(ALL) /usr/bin/systemctl restart nginx`\n- Configure `polkit` rules for fine-grained access\n- Use SELinux/AppArmor mandatory access control\n- Run services as non-root with dedicated users\n- Use capabilities instead of full root: `setcap cap_net_bind_service=+ep /usr/bin/node`\n- File permissions: 600 for secrets, 750 for dirs, avoid 777\n\n**Cloud implementation:**\n- IAM policies: Use specific resources and actions, never `*:*`\n- Service accounts per application with scoped roles\n- Temporary credentials (STS AssumeRole) instead of long-lived keys\n- Resource tags for conditional access\n- SCPs (Service Control Policies) in AWS Organizations\n\n**Container implementation:**\n- Run as non-root: `USER 1000` in Dockerfile\n- Read-only root filesystem: `securityContext.readOnlyRootFilesystem: true`\n- Drop all capabilities, add back only needed: `drop: ["ALL"], add: ["NET_BIND_SERVICE"]`\n- Use Pod Security Standards (restricted profile)\n\n**Kubernetes:**\n- RBAC with specific verbs and resources\n- NetworkPolicies to restrict pod communication\n- OPA/Gatekeeper for policy enforcement', difficulty: 'intermediate', tags: ['least-privilege', 'iam', 'security', 'rbac'] },

  // Docker
  { categorySlug: 'docker', title: 'Explain Docker architecture and the layered filesystem', content: 'Describe Docker\'s client-server architecture, image layers, and how the union filesystem works.', answer: '**Docker Architecture:**\n- **Docker Client**: CLI (docker) communicates with daemon via REST API\n- **Docker Daemon (dockerd)**: Manages images, containers, networks, volumes\n- **containerd**: Container runtime supervisor (shim, runc)\n- **runc**: OCI runtime that actually creates containers\n\n**Layered Filesystem:**\n- Each Dockerfile instruction creates a read-only layer\n- Layers are shared between images (space efficient)\n- Container layer: writable overlay on top of read-only layers\n- **OverlayFS** (overlay2) is the default storage driver\n- `docker history <image>` shows all layers\n\n**Copy-on-Write (CoW):**\n- When a container modifies a file from a lower layer, it copies the file to its writable layer first\n- Reading from lower layers is direct (no copy)\n\n**Multi-stage builds** reduce final image size:\n```dockerfile\nFROM node:20 AS builder\nWORKDIR /app\nCOPY . .\nRUN npm ci && npm run build\n\nFROM node:20-slim\nCOPY --from=builder /app/dist ./dist\nCMD ["node", "dist/server.js"]\n```\n\n**Inspect layers:**\n```bash\ndocker inspect <image> --format \'{{json .RootFS.Layers}}\'\ndocker save <image> -o image.tar  # export all layers\ndive <image>  # explore each layer (tool: dive)\n```', difficulty: 'intermediate', tags: ['docker', 'architecture', 'layers', 'overlayfs'] },
  { categorySlug: 'docker', title: 'What are Docker networking modes and when to use each?', content: 'Explain Docker network drivers (bridge, host, overlay, macvlan) and their use cases.', answer: '**Network drivers:**\n\n1. **bridge** (default): Container gets private IP on docker0 bridge\n   - Port mapping: `-p 8080:80`\n   - Container-to-container: use `--network mynet` for DNS-based discovery\n   - Use case: Single-host applications\n\n2. **host**: Container shares host network stack\n   - No network isolation, best performance\n   - No port mapping needed\n   - Use case: High-performance networking, monitoring agents\n\n3. **overlay**: Multi-host networking (Swarm/K8s)\n   - Encrypted VXLAN tunnels between hosts\n   - Built-in service discovery\n   - Use case: Docker Swarm, multi-host communication\n\n4. **macvlan**: Container gets real MAC on physical network\n   - Appears as physical device on LAN\n   - No NAT overhead\n   - Use case: Legacy applications requiring direct network presence\n\n5. **none**: No networking\n   - Use case: Batch jobs, security-sensitive tasks\n\n**Custom bridge network (recommended):**\n```bash\ndocker network create --driver bridge \\\n  --subnet 172.20.0.0/16 \\\n  --gateway 172.20.0.1 \\\n  myapp-net\n\ndocker run --network myapp-net --name api myimage\ndocker run --network myapp-net --name db myimage\n# api can reach db via hostname "db"\n```\n\n**DNS resolution**: Custom bridges provide automatic DNS; default bridge requires `--link` (deprecated) or manual IP references.', difficulty: 'intermediate', tags: ['docker', 'networking', 'bridge', 'overlay'] },
  { categorySlug: 'docker', title: 'Optimize Docker image size and build performance', content: 'Provide strategies for reducing Docker image size and speeding up builds.', answer: '**Image size optimization:**\n\n1. **Use minimal base images**:\n   - `alpine` (~5MB) vs `debian` (~80MB)\n   - `distroless` (no shell, minimal) for production\n   - `scratch` for static binaries (Go)\n\n2. **Multi-stage builds** (biggest win):\n```dockerfile\nFROM rust:1.75 AS builder\nCOPY . .\nRUN cargo build --release\n\nFROM gcr.io/distroless/cc\nCOPY --from=builder /app/target/release/app /app\n```\n\n3. **Layer caching**: Order instructions least→most changing\n```dockerfile\nCOPY package.json package-lock.json ./\nRUN npm ci\nCOPY . .\n```\n\n4. **Combine RUN commands** to reduce layers:\n```dockerfile\nRUN apt-get update && \\\n    apt-get install -y --no-install-recommends curl && \\\n    rm -rf /var/lib/apt/lists/*\n```\n\n5. **.dockerignore** (like .gitignore for builds):\n```\nnode_modules\ngit\ndockerignore\n*.md\n```\n\n6. **BuildKit** features:\n```dockerfile\n# syntax=docker/dockerfile:1\nRUN --mount=type=cache,target=/root/.npm npm ci\nRUN --mount=type=secret,id=npmrc npm ci\n```\n\n**Build performance:**\n- BuildKit: `DOCKER_BUILDKIT=1 docker build .`\n- Cache mounts for package managers\n- Parallel builds with `--build-arg BUILDKIT_SANDBOX_HOSTNAME`\n- Remote cache: `--cache-from registry/image:cache`', difficulty: 'advanced', tags: ['docker', 'optimization', 'buildkit', 'multi-stage'] },

  // Kubernetes
  { categorySlug: 'kubernetes', title: 'Explain Kubernetes architecture and component roles', content: 'Describe the Kubernetes control plane and worker node components and how they interact.', answer: '**Control Plane (Master):**\n\n1. **kube-apiserver**: REST API entry point, validates and stores state in etcd\n2. **etcd**: Distributed key-value store, the single source of truth\n3. **kube-scheduler**: Assigns pods to nodes based on resources, taints, affinity\n4. **kube-controller-manager**: Runs controllers (Deployment, ReplicaSet, Node, Job)\n5. **cloud-controller-manager**: Cloud-specific controllers (LB, routes, volumes)\n\n**Worker Node:**\n\n1. **kubelet**: Agent that ensures containers run as per PodSpec, reports status\n2. **kube-proxy**: Maintains network rules (iptables/IPVS) for Service routing\n3. **Container Runtime**: containerd or CRI-O runs containers\n\n**Request flow:**\n```\nkubectl → apiserver → etcd (store)\n                  → scheduler (assign node)\n                  → kubelet (create pod)\n                  → kube-proxy (update network rules)\n```\n\n**High availability:**\n- etcd cluster: 3 or 5 nodes (quorum-based)\n- Multiple API servers behind LB\n- Leader election for scheduler and controllers\n\n**Key add-ons:**\n- CNI (Calico, Cilium, Flannel) for pod networking\n- CoreDNS for service discovery\n- Ingress Controller (nginx, traefik) for external access\n- Metrics Server for HPA\n- cert-manager for TLS automation', difficulty: 'intermediate', tags: ['kubernetes', 'architecture', 'control-plane'] },
  { categorySlug: 'kubernetes', title: 'What are Kubernetes Services and how do they work?', content: 'Explain Kubernetes Service types, selectors, and traffic routing mechanisms.', answer: '**Service types:**\n\n1. **ClusterIP** (default): Internal IP only\n   - Accessible within cluster: `my-svc.my-ns.svc.cluster.local`\n   - Use case: Internal microservice communication\n\n2. **NodePort**: Exposes on each node\'s IP at a port (30000-32767)\n   - Use case: Development, simple external access\n\n3. **LoadBalancer**: Provisions cloud provider LB\n   - Use case: Production external access on cloud\n\n4. **ExternalName**: CNAME to external DNS\n   - Use case: Alias to external service\n\n5. **Headless** (ClusterIP: None): No proxy, returns pod IPs directly\n   - Use case: StatefulSets (databases), service discovery\n\n**Traffic routing:**\n- kube-proxy maintains iptables/IPVS rules\n- iptables mode: random pod selection (no session affinity by default)\n- IPVS mode: multiple algorithms (rr, lc, wrr, sh)\n\n**Session affinity:**\n```yaml\nspec:\n  sessionAffinity: ClientIP\n  sessionAffinityConfig:\n    clientIP:\n      timeoutSeconds: 3600\n```\n\n**Topology-aware routing** (K8s 1.22+):\n```yaml\nspec:\n  topologyKeys: [\"kubernetes.io/hostname\", \"topology.kubernetes.io/zone\"]\n```\n\n**Troubleshooting:**\n```bash\nkubectl get svc,endooints\nkubectl describe svc my-svc\nkubectl get endpoints my-svc  # check if pods are backing the service\nnslookup my-svc.my-ns.svc.cluster.local\n```', difficulty: 'intermediate', tags: ['kubernetes', 'services', 'networking'] },
  { categorySlug: 'kubernetes', title: 'How to troubleshoot a CrashLoopBackOff pod?', content: 'Walk through the systematic approach to diagnose and fix a pod stuck in CrashLoopBackOff.', answer: '**CrashLoopBackOff** means the container starts, crashes, and Kubernetes restarts it repeatedly.\n\n**Step-by-step troubleshooting:**\n\n1. **Get pod status:**\n```bash\nkubectl get pods\nkubectl describe pod <pod-name>  # Look at Events and Last State\n```\n\n2. **Check logs:**\n```bash\nkubectl logs <pod-name>              # current container\nkubectl logs <pod-name> --previous    # previous crashed container\nkubectl logs <pod-name> -c <container> # specific container\n```\n\n3. **Common causes & fixes:**\n\n| Cause | Symptom | Fix |\n|-------|---------|----|\n| Missing config/secrets | Exit 1, "file not found" | Check ConfigMap/Secret mounts |\n| OOMKilled | Last State: OOMKilled | Increase resources.limits.memory |\n| Failed health check | "unhealthy" in events | Fix probe path/timing |\n| App startup error | Stack trace in logs | Fix application code |\n| Permission denied | Exit 1, "permission denied" | Fix SecurityContext, file permissions |\n| Missing env vars | Exit 1, "required variable" | Add to container spec |\n\n4. **Debug interactively:**\n```bash\n# Override entrypoint to get shell\nkubectl run debug --image=busybox --rm -it --restart=Never -- sh\n\n# Ephemeral debug container (K8s 1.25+)\nkubectl debug <pod-name> -it --image=busybox\n```\n\n5. **Check resource limits:**\n```bash\nkubectl describe pod <pod-name> | grep -A5 Limits\n```\n\n6. **Watch events in real-time:**\n```bash\nkubectl get events --sort-by=.metadata.creationTimestamp -w\n```', difficulty: 'beginner', tags: ['kubernetes', 'troubleshooting', 'pods'] },

  // Terraform
  { categorySlug: 'terraform', title: 'Explain Terraform state and its management', content: 'What is Terraform state, why is it important, and how to manage it in a team environment?', answer: '**Terraform state** maps real-world resources to your configuration. It\'s the source of truth for what Terraform has created.\n\n**Why state matters:**\n- Tracks resource IDs and metadata\n- Stores computed attributes (IPs, ARNs)\n- Enables `terraform plan` to show diffs\n- Maps config resources to real resources\n\n**State management best practices:**\n\n1. **Remote state** (mandatory for teams):\n```hcl\nterraform {\n  backend "s3" {\n    bucket = "tf-state-prod"\n    key    = "infra/terraform.tfstate"\n    region = "us-east-1"\n    dynamodb_table = "tf-lock"  # state locking\n    encrypt = true\n  }\n}\n```\n\n2. **State locking**: Prevent concurrent operations (DynamoDB for S3, native for GCS)\n\n3. **State isolation**: Separate state per environment (dev/staging/prod)\n\n4. **State manipulation commands:**\n```bash\nterraform state list                    # list resources\nterraform state show aws_instance.web   # show attributes\nterraform state mv aws_instance.a aws_instance.b  # rename\nterraform state rm aws_instance.old     # unlink (doesn\'t destroy)\nterraform import aws_instance.web i-12345  # import existing\n```\n\n5. **Sensitive data**: State stores secrets in plain text. Use encryption at rest and restrict access.\n\n6. **State drift detection**: `terraform refresh` updates state from real infrastructure. Run `terraform plan` regularly.', difficulty: 'intermediate', tags: ['terraform', 'state', 'iac'] },
  { categorySlug: 'terraform', title: 'What are Terraform modules and how to structure them?', content: 'Explain Terraform module architecture, composition patterns, and directory structure best practices.', answer: '**Module structure:**\n```\nmodules/\n  vpc/\n    main.tf       # primary resources\n    variables.tf   # input variables\n    outputs.tf     # output values\n    versions.tf    # provider version constraints\n    README.md      # module documentation\n```\n\n**Module sources:**\n```hcl\nmodule "vpc" {\n  source = "./modules/vpc"                    # local\n  source = "terraform-aws-modules/vpc/aws"     # registry\n  source = "git::https://github.com/org/terraform-modules.git//vpc"  # git\n  source = "github.com/org/terraform-modules"  # GitHub\n\n  version = "~> 5.0"  # version constraint\n}\n```\n\n**Composition patterns:**\n1. **Flat**: All modules in one level\n2. **Nested**: Modules calling modules\n3. **Composition root**: Root orchestrates modules\n\n**Best practices:**\n- Each module should be reusable and self-contained\n- Use `for_each` and `count` for dynamic resources\n- Provide sensible defaults in variables\n- Use `output` to expose values needed by other modules\n- Version pin modules in production\n- Use `tflint` and `terraform validate` in CI\n\n**Terragrunt** (wrapper): Keeps DRY by extracting provider/backend config:\n```hcl\nterraform {\n  source = "git::https://github.com/org/modules.git//vpc?ref=v2.0"\n}\ninputs = {\n  cidr = "10.0.0.0/16"\n}\n```\n\n**Testing**: Use `terraform test` (1.6+), Terratest (Go), or kitchen-terraform for integration tests.', difficulty: 'advanced', tags: ['terraform', 'modules', 'iac', 'architecture'] },

  // Ansible
  { categorySlug: 'ansible', title: 'Explain Ansible architecture and execution flow', content: 'Describe how Ansible works agentlessly, its inventory system, and playbook execution.', answer: '**Ansible Architecture:**\n- **Control node**: Where Ansible runs (no daemon needed)\n- **Managed nodes**: Target hosts (need only Python + SSH)\n- **Inventory**: Host list (INI/YAML/dynamic)\n- **Modules**: Units of work (copy, yum, systemd, etc.)\n- **Playbooks**: YAML orchestrations of tasks\n\n**Execution flow:**\n1. Read inventory and playbook\n2. Generate Python script from module\n3. SCP script to target host (~/.ansible/tmp/)\n4. Execute script on target via SSH\n5. Return JSON output\n6. Delete script from target\n\n**Inventory examples:**\n```ini\n[webservers]\nweb[01:03].example.com\n\n[dbservers]\ndb01.example.com ansible_host=10.0.1.50\n\n[production:children]\nwebservers\ndbservers\n\n[production:vars]\nansible_user=deploy\nansible_python_interpreter=/usr/bin/python3\n```\n\n**Dynamic inventory** for cloud:\n```bash\nansible-inventory -i aws_ec2.yaml --list\nansible-inventory -i aws_ec2.yaml --graph\n```\n\n**Ad-hoc commands:**\n```bash\nansible all -m ping\nansible webservers -m shell -a "uptime"\nansible dbservers -m copy -a "src=conf.cnf dest=/etc/mysql/conf.cnf"\n```\n\n**Key config**: `ansible.cfg` (current dir > ~/.ansible.cfg > /etc/ansible/ansible.cfg)', difficulty: 'beginner', tags: ['ansible', 'architecture', 'inventory'] },
  { categorySlug: 'ansible', title: 'How to write idempotent Ansible playbooks?', content: 'Explain idempotency in Ansible and best practices for writing reliable playbooks.', answer: '**Idempotency**: Running a playbook multiple times produces the same result. Ansible modules are inherently idempotent when used correctly.\n\n**Idempotent patterns:**\n\n1. **Use modules instead of command/shell:**\n```yaml\n# Bad - not idempotent\n- name: Install nginx\n  command: apt install nginx -y\n\n# Good - idempotent\n- name: Install nginx\n  apt:\n    name: nginx\n    state: present\n    update_cache: yes\n```\n\n2. **When you must use command, add changed_when/failed_when:**\n```yaml\n- name: Check if database exists\n  command: psql -lqt -d mydb\n  register: db_check\n  changed_when: db_check.rc != 0\n  failed_when: false\n\n- name: Create database\n  command: createdb mydb\n  when: db_check.rc != 0\n```\n\n3. **Use handlers for service restarts:**\n```yaml\n- name: Configure nginx\n  template:\n    src: nginx.conf.j2\n    dest: /etc/nginx/nginx.conf\n  notify: Restart nginx\n\nhandlers:\n  - name: Restart nginx\n    service:\n      name: nginx\n      state: restarted\n```\n\n4. **Use assert for validation:**\n```yaml\n- name: Verify minimum disk space\n  assert:\n    that:\n      - ansible_mounts | selectattr(\'mount\', \'equalto\', \'/\') | list | first | json_query(\'size_available\') > 1000000000\n    fail_msg: "Not enough disk space"\n```\n\n5. **Lock step versions with roles:**\n```yaml\n- name: Apply role\n  include_role:\n    name: nginx\n  vars:\n    nginx_version: "1.24.0"\n```', difficulty: 'intermediate', tags: ['ansible', 'idempotency', 'playbooks'] },

  // AWS
  { categorySlug: 'aws', title: 'Explain AWS VPC architecture and subnet design', content: 'Describe VPC components, subnet types, routing, and best practices for network design in AWS.', answer: '**VPC Components:**\n- **VPC**: Isolated virtual network (CIDR block, e.g., 10.0.0.0/16)\n- **Subnets**: Segments of VPC CIDR\n  - Public: Internet Gateway route\n  - Private: No direct internet access\n  - Isolated: No internet or NAT\n- **Route Tables**: Direct traffic between subnets and gateways\n- **Internet Gateway (IGW)**: Connect VPC to internet\n- **NAT Gateway**: Allow private subnets outbound internet access\n- **Security Groups**: Stateful instance-level firewall\n- **NACLs**: Stateless subnet-level firewall\n\n**Best practice architecture:**\n```\nVPC 10.0.0.0/16\n├── AZ-a\n│   ├── Public  10.0.1.0/24  (ALB, Bastion)\n│   ├── Private 10.0.2.0/24  (App servers)\n│   └── Data    10.0.3.0/24  (RDS, ElastiCache)\n├── AZ-b\n│   ├── Public  10.0.11.0/24\n│   ├── Private 10.0.12.0/24\n│   └── Data    10.0.13.0/24\n```\n\n**Key differences SG vs NACL:**\n| Feature | Security Group | NACL |\n|---------|---------------|------|\n| Level | Instance | Subnet |\n| State | Stateful | Stateless |\n| Rules | Allow only | Allow + Deny |\n| Evaluation | All rules | In order |\n\n**VPC Peering & Transit Gateway** for multi-VPC connectivity. **VPC Endpoints** (PrivateLink) for AWS service access without NAT.', difficulty: 'intermediate', tags: ['aws', 'vpc', 'networking'] },
  { categorySlug: 'aws', title: 'What are the AWS IAM best practices?', content: 'Describe AWS IAM security best practices including policies, roles, and access management.', answer: '**IAM Best Practices:**\n\n1. **Root account**: Never use access keys, enable MFA, create IAM user for daily work\n\n2. **Principle of least privilege:**\n```json\n{\n  "Version": "2012-10-17",\n  "Statement": [{\n    "Effect": "Allow",\n    "Action": [\n      "s3:GetObject",\n      "s3:PutObject"\n    ],\n    "Resource": "arn:aws:s3:::my-bucket/data/*"\n  }]\n}\n```\n\n3. **Use roles, not users** for services (EC2, Lambda, ECS)\n4. **Temporary credentials** via STS AssumeRole instead of long-lived keys\n5. **IAM Access Analyzer** to identify unused/overly permissive policies\n6. **Policy variables** for dynamic access:\n```json\n"Resource": "arn:aws:s3:::bucket-${aws:username}/*"\n```\n\n7. **Permission boundaries** to limit max permissions a role can have\n8. **Service Control Policies (SCPs)** at organization level\n9. **Rotate access keys** regularly (90 days)\n10. **CloudTrail** for API audit logging\n\n**IAM Identity Center** (successor to SSO): Centralized access management across multiple AWS accounts.\n\n**Tools**: `aws iam simulate-principal-policy`, IAM Access Analyzer, `cloudsplaining` (policy analysis)', difficulty: 'intermediate', tags: ['aws', 'iam', 'security'] },

  // Azure
  { categorySlug: 'azure', title: 'Compare Azure Resource Manager vs Classic deployment', content: 'Explain the Azure Resource Manager (ARM) model and how it differs from the classic deployment model.', answer: '**ARM (Azure Resource Manager):**\n- Resource Groups for logical grouping\n- Declarative templates (ARM JSON, Bicep)\n- Role-Based Access Control (RBAC) at resource group level\n- Tags for organization and billing\n- Consistent management plane (REST API, CLI, Portal, SDK)\n- Parallel resource deployment\n- Dependency management\n\n**Classic (ASM):**\n- Single VM as management unit\n- Imperative management only\n- Limited RBAC (co-admin only)\n- No resource groups, no tags\n- Sequential deployment\n\n**Why ARM is superior:**\n1. **Infrastructure as Code**: ARM templates/Bicep enable repeatable deployments\n2. **Access control**: Fine-grained RBAC per resource\n3. **Cost management**: Tags + resource groups for chargeback\n4. **Consistency**: Same API across all Azure services\n5. **Automation**: CI/CD integration\n\n**Bicep** (preferred over ARM JSON):\n```bicep\nresource storageAccount \'Microsoft.Storage/storageAccounts@2023-01-01\' = {\n  name: \'st${uniqueString(resourceGroup().id)}\'\n  location: resourceGroup().location\n  sku: { name: \'Standard_LRS\' }\n  kind: \'StorageV2\'\n}\n```\n\nClassic is deprecated - all new resources must use ARM.', difficulty: 'beginner', tags: ['azure', 'arm', 'deployment'] },

  // GCP
  { categorySlug: 'gcp', title: 'Explain GCP IAM and organization hierarchy', content: 'Describe Google Cloud IAM model, organization/folder/project hierarchy, and access control patterns.', answer: '**GCP Organization Hierarchy:**\n```\nOrganization (domain)\n  └── Folders (optional, grouping)\n       └── Projects\n            └── Resources (VMs, buckets, etc.)\n```\n\n**IAM Model:**\n- **Who**: Member (user, service account, group, domain)\n- **Can do what**: Role (primitive, predefined, custom)\n- **On which resource**: Resource (org, folder, project, resource)\n\n**Role types:**\n1. **Primitive**: Owner, Editor, Viewer (avoid in production)\n2. **Predefined**: roles/storage.objectAdmin, roles/compute.instanceAdmin\n3. **Custom**: Fine-grained, org-level only\n\n**Best practices:**\n- Use **groups** for member management\n- Grant roles at the **highest appropriate level** (inheritance)\n- Use **service accounts** for workloads, not user accounts\n- **Workload Identity** for GKE pods (no service account keys)\n- **Organization Policy** constraints (restrict resource types, locations)\n\n**Key IAM commands:**\n```bash\ngcloud iam service-accounts create my-sa\ngcloud projects add-iam-policy-binding my-project \\\n  --member="serviceAccount:my-sa@my-project.iam.gserviceaccount.com" \\\n  --role="roles/storage.objectViewer"\n```\n\n**IAM Recommender**: Analyzes last 90 days of access and suggests removing excess permissions.', difficulty: 'intermediate', tags: ['gcp', 'iam', 'organization'] },

  // DevOps
  { categorySlug: 'devops', title: 'Explain CI/CD pipeline design patterns', content: 'Describe common CI/CD pipeline architectures, anti-patterns, and best practices for reliable deployments.', answer: '**Pipeline patterns:**\n\n1. **Sequential Pipeline**:\nBuild → Test → Staging → Production\nSimple but slow; each stage waits for the previous\n\n2. **Parallel Testing**:\nBuild → [Unit Tests | Integration Tests | Security Scans] → Deploy\nFaster feedback by running independent tests concurrently\n\n3. **Matrix Builds**:\nBuild for [Linux | macOS | Windows] × [Node 18 | Node 20]\nEnsures compatibility across platforms/versions\n\n4. **GitOps Pipeline**:\nPR → CI (build + test) → Merge → CD (argocd syncs from git)\nGit is the single source of truth for desired state\n\n**Deployment strategies:**\n- **Rolling update**: Gradual replacement\n- **Blue/Green**: Two identical environments, switch traffic\n- **Canary**: Route small % traffic to new version\n- **Feature flags**: Toggle features without deployment\n\n**Anti-patterns:**\n- Flaky tests in CI (fix immediately or quarantine)\n- Deploying on Fridays\n- Manual approval gates that block for days\n- Not versioning infrastructure alongside code\n- Monolithic pipelines (one pipeline for all services)\n\n**Best practices:**\n- Fail fast: lint → unit → integration → e2e\n- Artifact promotion (build once, deploy to each env)\n- Observability: metrics, logs, traces in every stage\n- Rollback automation\n- Pipeline as code (version controlled)\n- Security scanning (SAST, DAST, SCA) in CI', difficulty: 'intermediate', tags: ['ci-cd', 'devops', 'pipelines', 'deployment'] },

  // Monitoring
  { categorySlug: 'monitoring', title: 'Design a monitoring and alerting strategy', content: 'How to design effective monitoring, alerting, and observability for production systems?', answer: '**Three pillars of observability:**\n1. **Metrics**: Numeric time-series data (CPU, latency, error rate)\n2. **Logs**: Event records with context (structured JSON preferred)\n3. **Traces**: Request flow across distributed services\n\n**Alerting design principles:**\n1. Alert on symptoms, not causes (user-facing impact)\n2. Every alert should be actionable (if not, it\'s noise)\n3. Use severity levels: P1 (page) vs P2 (ticket) vs P3 (log)\n4. Set thresholds on SLIs (latency p99, error rate >1%)\n5. Avoid alert fatigue: tune thresholds, use anomaly detection\n\n**RED method** (for services):\n- **R**ate: Requests per second\n- **E**rrors: Failed requests percentage\n- **D**uration: Latency distribution (p50, p95, p99)\n\n**USE method** (for resources):\n- **U**tilization: Percentage of capacity used\n- **S**aturation: Queue depth / wait time\n- **E**rrors: Error count\n\n**Tool stack:**\n- Metrics: Prometheus + Grafana (or Datadog)\n- Logs: ELK Stack or Loki + Grafana\n- Traces: Jaeger or Tempo\n- Alerting: Alertmanager (Prometheus) or PagerDuty\n- Uptime: Blackbox exporter, Synthetic monitoring\n\n**SLO framework:**\nSLI (metric) → SLO (target) → Error budget (1 - SLO)\nWhen error budget exhausted → freeze deploys, focus on reliability', difficulty: 'advanced', tags: ['monitoring', 'alerting', 'observability', 'slo'] },

  // Databases
  { categorySlug: 'databases', title: 'Explain PostgreSQL MVCC and vacuum', content: 'How does PostgreSQL handle concurrent access with MVCC? Why is VACUUM important?', answer: '**MVCC (Multi-Version Concurrency Control):**\nEach transaction sees a consistent snapshot of the database at a specific point in time.\n\n**How it works:**\n1. Every row has xmin (inserting tx ID) and xmax (deleting/updating tx ID)\n2. A transaction sees a row if: xmin is committed AND (xmax is null OR xmax is not committed)\n3. UPDATE = DELETE old row + INSERT new row (creates new version)\n4. This means readers never block writers and vice versa\n\n**Problem: Dead tuples**\n- Deleted/updated rows leave behind "dead tuples" (old versions)\n- These consume disk space and slow down scans\n- This is where VACUUM comes in\n\n**VACUUM:**\n- **Regular VACUUM**: Marks dead tuple space as reusable (no table lock)\n- **VACUUM FULL**: Rebuilds table, reclaims disk to OS (exclusive lock!)\n- **Autovacuum**: Runs automatically based on thresholds\n  - `autovacuum_vacuum_scale_factor` (default 0.2 = 20% changed)\n  - `autovacuum_analyze_scale_factor` (default 0.1 = 10% changed)\n\n**Tuning autovacuum:**\n```sql\n-- For frequently updated tables\nALTER TABLE my_table SET (autovacuum_vacuum_scale_factor = 0.05);\nALTER TABLE my_table SET (autovacuum_vacuum_cost_delay = 10);  -- ms\n\n-- Monitor dead tuples\nSELECT relname, n_dead_tup, n_live_tup FROM pg_stat_user_tables;\n```\n\n**Transaction ID wraparound**: If autovacuum can\'t keep up, XID wraparound can make the database read-only. Monitor `pg_database.datfrozenxid`.', difficulty: 'advanced', tags: ['postgresql', 'mvcc', 'vacuum', 'databases'] },
  { categorySlug: 'databases', title: 'Database backup and disaster recovery strategies', content: 'Describe comprehensive database backup strategies and disaster recovery planning.', answer: '**Backup types:**\n1. **Full backup**: Complete copy of all data (daily/weekly)\n2. **Incremental**: Only changes since last backup (hourly)\n3. **Differential**: Changes since last full backup\n4. **Continuous/WAL**: Point-in-time recovery (PITR)\n\n**PostgreSQL:**\n```bash\n# Logical backup\npg_dump -Fc mydb > mydb.dump          # custom format\npg_dumpall --globals-only > globals.sql\n\n# Physical backup (PITR)\npg_basebackup -D /backup/base -Ft -z -P\n# Archive WAL: archive_mode = on, archive_command\n\n# Restore\ngunzip -c base.tar.gz | tar xf -\npg_ctl start  # recovery.target_time = \'2024-01-15 10:30:00\'\n```\n\n**MySQL:**\n```bash\nmysqldump --single-transaction --all-databases > backup.sql\n# Binary log for PITR: log_bin = mysql-bin\nmysqlbinlog --start-datetime="2024-01-15 10:00:00" mysql-bin.000123 | mysql\n```\n\n**RPO/RTO targets:**\n| Strategy | RPO | RTO |\n|----------|-----|-----|\n| Daily full | 24h | Hours |\n| WAL streaming | Seconds | Minutes |\n| Sync replication | Zero | Seconds |\n| Hot standby | Zero | Seconds |\n\n**DR planning:**\n- Define RPO (max data loss) and RTO (max downtime) per application\n- Test restores regularly (monthly)\n- Automate failover with Patroni (PostgreSQL) or Orchestrator (MySQL)\n- Cross-region replication for geographic redundancy\n- Document and rehearse failover procedures', difficulty: 'intermediate', tags: ['databases', 'backup', 'disaster-recovery'] },

  // Web Servers
  { categorySlug: 'web-servers', title: 'Configure Nginx as a reverse proxy with load balancing', content: 'Set up Nginx as a reverse proxy with multiple upstream servers and load balancing configuration.', answer: '**Basic reverse proxy:**\n```nginx\nupstream backend {\n    least_conn;  # or round_robin (default), ip_hash, random\n    server 10.0.1.10:8080 weight=3;\n    server 10.0.1.11:8080 weight=2;\n    server 10.0.1.12:8080 backup;\n\n    keepalive 32;  # connection pool\n}\n\nserver {\n    listen 80;\n    server_name app.example.com;\n\n    location / {\n        proxy_pass http://backend;\n        proxy_http_version 1.1;\n        proxy_set_header Connection "";\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n\n        # Timeouts\n        proxy_connect_timeout 5s;\n        proxy_read_timeout 30s;\n        proxy_send_timeout 30s;\n\n        # Buffering\n        proxy_buffering on;\n        proxy_buffer_size 4k;\n        proxy_buffers 8 4k;\n    }\n\n    # Health check endpoint\n    location /health {\n        proxy_pass http://backend/health;\n    }\n}\n```\n\n**Load balancing methods:**\n- `round_robin` (default): Sequential\n- `least_conn`: Fewest active connections\n- `ip_hash`: Session affinity by client IP\n- `hash $request_uri`: Cache-friendly\n- `random two least_conn`: Best of two random\n\n**Health checks (NGINX Plus):**\n```nginx\nupstream backend {\n    server 10.0.1.10:8080;\n    health_check interval=5s fails=3 passes=2 uri=/health;\n}\n```\n\nFor OSS Nginx, use `max_fails=2 fail_timeout=30s` on server directives.', difficulty: 'intermediate', tags: ['nginx', 'reverse-proxy', 'load-balancing'] },
  { categorySlug: 'web-servers', title: 'SSL/TLS configuration best practices for web servers', content: 'Configure secure SSL/TLS settings for Nginx and Apache with modern security standards.', answer: '**Nginx TLS configuration (Mozilla Modern):**\n```nginx\nserver {\n    listen 443 ssl http2;\n    server_name example.com;\n\n    # Certificates\n    ssl_certificate /etc/ssl/certs/example.com.crt;\n    ssl_certificate_key /etc/ssl/private/example.com.key;\n\n    # TLS versions\n    ssl_protocols TLSv1.3;\n    ssl_prefer_server_ciphers off;\n\n    # OCSP Stapling\n    ssl_stapling on;\n    ssl_stapling_verify on;\n    resolver 1.1.1.1 8.8.8.8 valid=300s;\n\n    # Security headers\n    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;\n    add_header X-Content-Type-Options nosniff;\n    add_header X-Frame-Options SAMEORIGIN;\n\n    # Session\n    ssl_session_timeout 1d;\n    ssl_session_cache shared:SSL:50m;\n    ssl_session_tickets off;\n\n    # DH params (if still using TLS 1.2)\n    ssl_dhparam /etc/ssl/dhparam.pem;\n}\n```\n\n**For TLS 1.2 compatibility (Mozilla Intermediate):**\n```nginx\nssl_protocols TLSv1.2 TLSv1.3;\nssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;\n```\n\n**Certificate automation:**\n```bash\n# certbot (Let\'s Encrypt)\ncertbot --nginx -d example.com\ncertbot renew --dry-run\n\n# cert-manager (Kubernetes)\napiVersion: cert-manager.io/v1\nkind: Certificate\n```\n\n**Testing**: `ssllabs.com`, `testssl.sh`, `nmap --script ssl-enum-ciphers -p 443 example.com`', difficulty: 'intermediate', tags: ['nginx', 'ssl', 'tls', 'security'] },
]

async function main() {
  console.log('🌱 Seeding database...')

  // Create categories
  for (const cat of categories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {},
      create: cat,
    })
  }
  console.log(`✅ Created ${categories.length} categories`)

  // Create tags
  const allTags = new Set<string>()
  questions.forEach(q => q.tags.forEach(t => allTags.add(t)))
  for (const tagName of allTags) {
    await prisma.tag.upsert({
      where: { slug: tagName },
      update: {},
      create: {
        name: tagName,
        slug: tagName,
      },
    })
  }
  console.log(`✅ Created ${allTags.size} tags`)

  // Create questions
  let created = 0
  for (const q of questions) {
    const category = await prisma.category.findUnique({ where: { slug: q.categorySlug } })
    if (!category) continue

    const slug = q.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

    const question = await prisma.question.upsert({
      where: { slug },
      update: {},
      create: {
        title: q.title,
        slug,
        content: q.content,
        answer: q.answer,
        difficulty: q.difficulty,
        source: 'github',
        categoryId: category.id,
      },
    })

    // Connect tags
    for (const tagName of q.tags) {
      const tag = await prisma.tag.findUnique({ where: { slug: tagName } })
      if (tag) {
        await prisma.questionTag.upsert({
          where: {
            questionId_tagId: { questionId: question.id, tagId: tag.id },
          },
          update: {},
          create: { questionId: question.id, tagId: tag.id },
        })
      }
    }
    created++
  }
  console.log(`✅ Created ${created} questions`)

  // Create a demo user
  await prisma.user.upsert({
    where: { email: 'demo@sysadmin.academy' },
    update: {},
    create: {
      email: 'demo@sysadmin.academy',
      name: 'Demo User',
      level: 'Beginner',
      xp: 0,
      role: 'admin',
    },
  })
  console.log('✅ Created demo user')

  // Create some AI explanations for first few questions
  const firstQuestions = await prisma.question.findMany({ take: 5 })
  for (const q of firstQuestions) {
    await prisma.aiExplanation.upsert({
      where: { questionId: q.id },
      update: {},
      create: {
        questionId: q.id,
        beginnerExplanation: `Think of this like building blocks - ${q.title.toLowerCase()} is a fundamental concept that helps you understand how systems work together. Start with the basics and gradually build up your understanding.`,
        intermediateExplanation: `${q.title} involves several key components working together. Understanding the interactions between these components is essential for effective system administration.`,
        advancedExplanation: `At an advanced level, ${q.title} requires deep understanding of internal mechanisms, performance implications, and edge cases. Focus on optimization and architectural decisions.`,
        realWorldExample: `In a production environment, this concept directly impacts system reliability and performance. For example, when troubleshooting a production incident, understanding this topic helps you quickly identify root causes.`,
        interviewTips: `When asked about this in an interview, start with a clear definition, then provide a practical example. Mention common pitfalls and how to avoid them. Show that you understand both theory and practice.`,
        relatedTopics: 'system-design, performance, troubleshooting',
        model: 'demo',
      },
    })
  }
  console.log('✅ Created AI explanations')

  // Create initial sync state
  await prisma.syncState.create({
    data: {
      repoUrl: 'https://github.com/trimstray/test-your-sysadmin-skills',
      status: 'idle',
    },
  })
  console.log('✅ Created sync state')

  console.log('\n🎉 Seeding complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
